### ISSUE TITLE
[Bug]: visual regression introduced in 1.18.3

### ISSUE THREAD

**Issue by jbroma** [web-infra-dev/rspress#1011]
### Version

```sh
n/a
```

### Details

https://github.com/web-infra-dev/rspress/pull/989 introduced few visual regressions.
It seems to be entirely tied to `background-color` on `button` elements, here are few examples:

- SearchBox background & CodeBlock action buttons
<img width="812" alt="image" src="https://github.com/web-infra-dev/rspress/assets/20626315/c77d0502-13dd-4956-9d6c-b11f8e244408">

- Mobile hamburger
<img width="446" alt="image" src="https://github.com/web-infra-dev/rspress/assets/20626315/a6c0e3c6-3c53-4676-83e1-df45575b54db">

- Language switch
<img width="446" alt="image" src="https://github.com/web-infra-dev/rspress/assets/20626315/c5e96432-95cb-4452-8890-0e4a835beeab">

### Reproduce link

https://rspress.dev

### Reproduce Steps

n/a

**Comment by Timeless0911** [comment]
Thanks, we will fix it later.
