### ISSUE TITLE
[Feature]: Automatically analyze code block language to generate highlight configuration

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#1043]
### What problem does this feature solve?

see details in #419 

We can automatically analyze code block language to generate highlight configuration.

### What does the proposed API look like?

none

**Comment by shulaoda** [comment]
I will try to implement this feature.

**Comment by shulaoda** [comment]
I need some discussion. @Timeless0911 
If I use the `compile` of `mdxRs` in the `loader` to obtain the code language used on the page, I can directly import the corresponding highlight method, which is faster but not suitable for `disabledMdxRs`. 
Another way is to scan all the MD files before the compilation of `Rspack` and extract the code languages, but this means it consumes more performance, which requires providing a parameter called `auto` on the `highlighter` for users to choose. Is a certain performance loss necessary for such a feature?

**Comment by Timeless0911** [comment]
just consider mdxrs scene, it should be option-in and we can specify limitations in doc.

**Comment by shulaoda** [comment]
> just consider mdxrs scene, it should be option-in and we can specify limitations in doc.

How about automatically recognizing highlight languages in `mdxRs` mode, and the highlighter option only serves as an alias?

**Comment by Timeless0911** [comment]
> > just consider mdxrs scene, it should be option-in and we can specify limitations in doc.
> 
> How about automatically recognizing highlight languages in `mdxRs` mode, and the highlighter option only serves as an alias?

LGTM
