### ISSUE TITLE
[Bug]: Why is there no introduction to the replaceRules option in the document?

### ISSUE THREAD

**Issue by shulaoda** [web-infra-dev/rspress#1048]
### Version

```sh
-
```

### Details

This option is used in many parts of the code, which is a `basic config`, but there is no relevant introduction in the documentation.
![image](https://github.com/web-infra-dev/rspress/assets/165626830/6abaa531-db06-4388-a6f9-4b5282e92ad3)

### Reproduce link

https://github.com/web-infra-dev/rspress/blob/main/packages/shared/src/types/index.ts

### Reproduce Steps

declared in `packages/shared/src/types`

**Comment by Timeless0911** [comment]
bump, we should mention it in our docs.
