### ISSUE TITLE
[Feature]: ensure equal padding width on both sides of the content

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#105]
### What problem does this feature solve?

On my 14-inch Macbook, the left side padding width is `140px`, the right side padding width is `120px`. This causes the page to look asymmetrical.

![image](https://github.com/web-infra-dev/rspress/assets/7237365/6e82ec69-a6f8-4d7c-b2a2-f1ce233b996b)

### What does the proposed API look like?

Can we keep the padding width consistent on both sides of the content?

**Comment by Vayras** [comment]
@chenjiahan I would like to work on this isssue

**Comment by chenjiahan** [comment]
Thanks!

**Comment by citrus327** [comment]
This issue seems already fixed.
