### ISSUE TITLE
[Bug]: @rspress/plugin-preview Dependency error

### ISSUE THREAD

**Issue by mobei12** [web-infra-dev/rspress#1058]
### 版本信息

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 16.38 GB / 31.82 GB
  Browsers:
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspress/plugin-preview: ^1.19.2 => 1.19.2
    rspress: ^1.19.2 => 1.19.2
```

### 问题详情

Use the @ rspress/plugin-preview plug-in to start the error report locally. 
![图片](https://github.com/web-infra-dev/rspress/assets/15901240/d0955f22-fd2e-4130-b1db-e7331a9e18a5)

Gitaction also failed to pack.
![图片](https://github.com/web-infra-dev/rspress/assets/15901240/9bc06b84-8f5b-4042-90c4-16fc1224fe9a)

### 复现链接

https://github.com/mobei12/mobei12

### 复现步骤

1. Installation depends on `pnpm install`. 
2. Run `pnpm run dev`

**Comment by SoonIter** [comment]
pluginPreview will render your codeblock as component and you have not installed the relevant dependencies for runtime.

add this line and cooperate with \`\`\`tsx preview

```ts
    pluginPreview({
      defaultRenderMode: 'pure',
    }),
```

https://rspress.dev/zh/plugin/official-plugins/preview#defaultrendermode

**Comment by mobei12** [comment]
o)(o
