### ISSUE TITLE
[Bug]: Install dependencies error

### ISSUE THREAD

**Issue by PuffMeow** [web-infra-dev/rspress#1106]
### Version

```sh
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 136.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh

The version of rspress is 1.21.1
```

### Details

 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @rspress/plugin-auto-nav-sidebar@1.21.1

This error happened while installing the dependencies of rspress@1.21.1
 at @rspress/core@1.21.1

The latest release of @rspress/plugin-auto-nav-sidebar is "1.21.0".

Other releases are:
  * beta: 1.1.1-beta.0
  * next: 0.0.0-next-20240517095525
  * nightly: 0.0.0-nightly-20240519160122

### Reproduce link

none

### Reproduce Steps

I met this error when I followed the step in the official doc to init a project.

1. pnpm create rspress@latest
2. pnpm install
3. error occurs

**Comment by Timeless0911** [comment]
Please check your npm registry, `@rspress/plugin-auto-nav-sidebar@1.21.1` already published in NPM, see https://www.npmjs.com/package/@rspress/plugin-auto-nav-sidebar

**Comment by PuffMeow** [comment]
> Please check your npm registry, `@rspress/plugin-auto-nav-sidebar@1.21.1` already published in NPM, see https://www.npmjs.com/package/@rspress/plugin-auto-nav-sidebar

Ok, I got it. I use the registry of intranet.
