### ISSUE TITLE
[Bug]: Don't support hot updates yet?

### ISSUE THREAD

**Issue by yiliang114** [web-infra-dev/rspress#111]
### Version

```sh
System:
    OS: macOS 13.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.31 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 117.0.5938.92
    Firefox: 111.0
    Safari: 16.6
```

### Details

![Kapture 2023-09-24 at 21 23 43](https://github.com/web-infra-dev/rspress/assets/11473889/959bf0aa-0eea-45e8-ae04-ffbe0dea8574)

### Reproduce link

https://codesandbox.io/p/sandbox/condescending-jackson-pwx966?file=%2Fdocs%2Findex.md%3A12%2C17-13%2C19

### Reproduce Steps

1. yarn i 
2. yarn run dev
3. change some code in index.md 
4. no change in preview page until active refresh once

**Comment by sanyuan0704** [comment]
The hmr of home page frontmatter does not work yet but the other pages is fine. I will fix it.
