### ISSUE TITLE
[Bug]: Aside activate wrongly when refresh page which contain anchor hash in URL

### ISSUE THREAD

**Issue by declanchiu** [web-infra-dev/rspress#1154]
### 版本信息

```sh
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 146.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    rspress: ^1.23.0 => 1.23.0
```

### 问题详情

![image](https://github.com/web-infra-dev/rspress/assets/55419399/fa797823-aa10-4789-b9c9-c9538eb2bc89)

After memorizing an anchor point, why doesn't it jump to the specific anchor point after refreshing, and why is the right side highlighted in the wrong place?

### 复现链接

https://rspress.dev/guide/advanced/custom-search#aftersearch

### 复现步骤

1. Click on one of the document's anchor points

2. The current url records the anchor.

3. Refresh the page according to the current url

4. Finds the problem mentioned above

**Comment by Timeless0911** [comment]
I can't reproduce.

![20240605191321_rec_](https://github.com/web-infra-dev/rspress/assets/50201324/9780fb5a-7e10-44e8-a8c0-8335a76ce2ab)

**Comment by declanchiu** [comment]
> I can't reproduce. 我无法重现。
> 
> ![20240605191321_rec_](https://private-user-images.githubusercontent.com/50201324/336812505-9780fb5a-7e10-44e8-a8c0-8335a76ce2ab.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzg0MzAsIm5iZiI6MTcxNzYzODEzMCwicGF0aCI6Ii81MDIwMTMyNC8zMzY4MTI1MDUtOTc4MGZiNWEtN2UxMC00NGU4LWE4YzAtODMzNWE3NmNlMmFiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxNDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMmMwMmM5NWFlY2I0NWQwODc4NmM2YzBjNzE4MDYyZmEwN2JhNjJiMjQzYmI1MGJkMWUzMDgzODllM2U4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyEBoHNEQqXg5YRG5rnHwjD9iHI6D1-8e05m6Ee0lIg) [ ![20240605191321_rec_](https://private-user-images.githubusercontent.com/50201324/336812505-9780fb5a-7e10-44e8-a8c0-8335a76ce2ab.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzg0MzAsIm5iZiI6MTcxNzYzODEzMCwicGF0aCI6Ii81MDIwMTMyNC8zMzY4MTI1MDUtOTc4MGZiNWEtN2UxMC00NGU4LWE4YzAtODMzNWE3NmNlMmFiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxNDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMmMwMmM5NWFlY2I0NWQwODc4NmM2YzBjNzE4MDYyZmEwN2JhNjJiMjQzYmI1MGJkMWUzMDgzODllM2U4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyEBoHNEQqXg5YRG5rnHwjD9iHI6D1-8e05m6Ee0lIg) ](https://private-user-images.githubusercontent.com/50201324/336812505-9780fb5a-7e10-44e8-a8c0-8335a76ce2ab.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzg0MzAsIm5iZiI6MTcxNzYzODEzMCwicGF0aCI6Ii81MDIwMTMyNC8zMzY4MTI1MDUtOTc4MGZiNWEtN2UxMC00NGU4LWE4YzAtODMzNWE3NmNlMmFiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxNDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMmMwMmM5NWFlY2I0NWQwODc4NmM2YzBjNzE4MDYyZmEwN2JhNjJiMjQzYmI1MGJkMWUzMDgzODllM2U4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyEBoHNEQqXg5YRG5rnHwjD9iHI6D1-8e05m6Ee0lIg) [ ](https://private-user-images.githubusercontent.com/50201324/336812505-9780fb5a-7e10-44e8-a8c0-8335a76ce2ab.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzg0MzAsIm5iZiI6MTcxNzYzODEzMCwicGF0aCI6Ii81MDIwMTMyNC8zMzY4MTI1MDUtOTc4MGZiNWEtN2UxMC00NGU4LWE4YzAtODMzNWE3NmNlMmFiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxNDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMmMwMmM5NWFlY2I0NWQwODc4NmM2YzBjNzE4MDYyZmEwN2JhNjJiMjQzYmI1MGJkMWUzMDgzODllM2U4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyEBoHNEQqXg5YRG5rnHwjD9iHI6D1-8e05m6Ee0lIg)

Thanks for trying to reproduce it, but the way I see it in the gif is a bit different, the correct way to do it is to click on an anchor and then scroll away from the current anchor, for example after clicking on the last anchor, the url is spliced with the anchor, then scroll to the top of the page, then refresh the page and you can see that the url with the anchor doesn't scroll to the bottom after refreshing! The

**Comment by declanchiu** [comment]
> > I can't reproduce. 我无法重现。
> 

> 
> Thanks for trying to reproduce it, but the way I see it in the gif is a bit different, the correct way to do it is to click on an anchor and then scroll away from the current anchor, for example after clicking on the last anchor, the url is spliced with the anchor, then scroll to the top of the page, then refresh the page and you can see that the url with the anchor doesn't scroll to the bottom after refreshing! The感谢您尝试重现它，但我在 gif 中看到的方式有点不同，正确的方法是单击锚点，然后滚动远离当前锚点，例如单击最后一个锚点后，url与anchor拼接，然后滚动到页面顶部，然后刷新页面可以看到刷新后带anchor的url并没有滚动到底部！这

**Comment by Timeless0911** [comment]
Thanks. From your gif, I see two main issues you want to point it out.

1. After scrolling to the top, refreshing the page again does not redirect to the corresponding anchor position. This should be a bug
2. Clicking the `Differences from VitePress` label in aside component, the highlighted label is `Try Rspress`. This is the expected behavior because it has reached the bottom of the page and the content of the two labels fills the screen, so the last label `Try Rspress` is highlighted. You can try it at https://vitepress.dev/reference/runtime-api#frontmatter, and the same behaviour when in this scene.

**Comment by Timeless0911** [comment]
This bug is caused by extra `setActiveLink()` which is implemented to fix right aside nav item doesn't highlight automatically while opening in a new tab in #319 

https://github.com/web-infra-dev/rspress/blob/90fc852c04a63e48d1cf2e489dcf5d03b7c2bfec/packages/theme-default/src/logic/sideEffects.ts#L168

We need to deal both same page refresh and open new tab well.
