### ISSUE TITLE
[Feature]: linting, formatting, husky, eslint and prettier

### ISSUE THREAD

**Issue by zmzlois** [web-infra-dev/rspress#1165]
### What problem does this feature solve?

when we create a rspress project, can we have eslint + prettier + default template comes with it to run through all the components and frontmatter? 

ex: I would like husky to run `npm run format` for precommit message check 

### What does the proposed API look like?

Should comes with CLI

**Comment by Timeless0911** [comment]
We do not expect to maintain these in the template, and users can choose any solutions and using them according to the corresponding official documents.

**Comment by chenjiahan** [comment]
Agree, ESLint already provides a pretty nice initializer: `npm init @eslint/config@latest`

https://eslint.org/docs/latest/use/getting-started

And prettier setup is quite easy
