### ISSUE TITLE
[Feature]: support divider type in _meta.json

### ISSUE THREAD

**Issue by sanyuan0704** [web-infra-dev/rspress#120]
### What problem does this feature solve?

Currently we use _meta.json to generate sidebar automatically. Sometimes, we need to specify a divider between two sidebar items.

### What does the proposed API look like?

The content of `_meta.json` can be like this:

```json
[
  {
    "type": "dir",
    "name": "guide",
    "label": "Guide"
  },
  { "type": "divider" },
  {
    "type": "dir",
    "name": "advanced",
    "label": "Advanced"
  },
]
```
Then rspress will render a divider between the two sidebar group.

**Comment by Yukiniro** [comment]
Hey. I hope to be able to handle this issue, but there is a question that needs to be confirmed: Do I need to create a new type, such as `SidebarDivider`, or add a new attribute in `SidebarItem`, such as `isDivider?: boolean;`?

**Comment by sanyuan0704** [comment]
Yeah, in my opinion, add a new type `SidebarDivider` would be better
