### ISSUE TITLE
[Feature]: Improve the transition when navigating to an URL with anchor

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#123]
### What problem does this feature solve?

When navigating to an URL with anchor, the page will move up and down once, which looks a bit strange:

https://github.com/web-infra-dev/rspress/assets/7237365/3be5e9a3-cb62-4ba6-9d41-cb41f7af8f46

Reproduce steps:

- Open https://deploy-preview-121--aquamarine-blini-95325f.netlify.app/api/config/config-build#builderconfig
- Click "builderConfig" link.

### What does the proposed API look like?

Provide a more natural transition effects.

**Comment by zoolsher** [comment]
I'll try to fix this
