### ISSUE TITLE
[Feature]: 能否提供访问构建配置的接口

### ISSUE THREAD

**Issue by hooozen** [web-infra-dev/rspress#1238]
### 这个功能解决了什么问题？

对于主题开发来说，不同的用户可能会部署到不同的 `base` url 上（或者多环境使用不用的路径）。虽然构建过程中会通过配置的 `base` 字段自动处理一些静态文件，但在组件开发时 jsx 里的一些变量保存的路径不会被处理。
如果提供了访问构建配置的接口，就可以在组件中根据 `base` 配置去组装 url。当然如果能直接提供相关的工具函数就更好了，例如通过 `url_for(path)` 函数直接可以组装 `base` 和 `path`.
虽然现在仍可以各种方法去读取和暴露配置，但封装好的API总归能更方便用户使用。

### 你期望的 API 是什么样子的？

例如通过 `url_for('/people/')` 可以根据不同配置的 `base` 来组装成 `http://example/people` 或者 `http://example/test/people`

**Comment by Timeless0911** [comment]
You can use `normalizeImagePath`, see https://rspress.dev/zh/guide/basic/static-assets#mdx-%E4%B8%AD%E4%BD%BF%E7%94%A8%E7%9A%84%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90 for details.

**Comment by hooozen** [comment]
Thank you for your prompt response. I believe there might have been a misunderstanding regarding my initial issue. However, I’ve found a resolution in the source code: https://github.com/web-infra-dev/rspress/blob/b68fc9c2bd6b9ff06f180bc4b15d54c4bd4fa328/packages/theme-default/src/components/Nav/index.tsx#L28.

Clearly, according to the source code, exposing `siteData` is crucial for theme development. You might now understand why I was requesting a utility function.

**Comment by Timeless0911** [comment]
So you solved this issue at runtime now?

**Comment by hooozen** [comment]
I can create a function myself to solve this problem, but I believe using a pre-packaged function would be a better choice. In any case, it's just a suggestion.

**Comment by Timeless0911** [comment]
Can you give a demo to show how you solve this issue?

**Comment by hooozen** [comment]
I haven't completed it yet, but I believe a simpler version like the following could work.

```jsx
 const { siteData } = usePageData()
 
 const url_for = (path:string) => {
   if () {
       // path is already a full url, like https://example.com/xxx 
       return path
   } else {
     return resolve(siteData.base, path)
   }
}
```

**Comment by Timeless0911** [comment]
> You can use `normalizeImagePath`, see https://rspress.dev/zh/guide/basic/static-assets#mdx-%E4%B8%AD%E4%BD%BF%E7%94%A8%E7%9A%84%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90 for details.

This function can not solve?

**Comment by hooozen** [comment]
Ah, now I get it! I believe the function have already provided a suitable approach. thank you very  much for your patience.
