### ISSUE TITLE
[Bug]: npm run dev --config 指定配置文件报错

### ISSUE THREAD

**Issue by hooozen** [web-infra-dev/rspress#1239]
### 版本信息

```sh
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 1.92 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  npmPackages:
    rspress: ^1.25.0 => 1.25.2
```

### 问题详情

命令行指定 --config 报错

（另外，bug report 的模版流程设计不太合理，请自行体验一下）

### 复现链接

https://codesandbox.io/p/devbox/wyj8dd

### 复现步骤

 npm run dev --config rspress.config.ts

**Comment by Timeless0911** [comment]
> 命令行指定 --config 报错

Your codesandbox cannot be accessed. Please post your error screenshot and error stack information.

> bug report 的模版流程设计不太合理，请自行体验一下

You can directly tell us about the problem to help us improve, thank you.

**Comment by hooozen** [comment]
sry about that. I think it can be accessed now. https://codesandbox.io/p/devbox/wyj8dd

**Comment by Timeless0911** [comment]
You should use `npm run dev -- --config rspress.config.ts` to pass `--config` param to npm scripts, it's standard behaviour of npm, see https://docs.npmjs.com/cli/v8/commands/npm-run-script#description for details.
