### ISSUE TITLE
[Feature]: 实现丝滑的动态切换主题 (using view transitions API on appearance toggle)

### ISSUE THREAD

**Issue by ayangweb** [web-infra-dev/rspress#1270]
### 这个功能解决了什么问题？

大佬，如果想给站点实现如下效果，有什么方法吗？

我试了 globalUIComponents + globalStyles + 自定义监听点击事件，然后执行动画方法，并没有达到理想的效果！有什么方法能够拦截切换主题的事件，然后执行自定义事件吗？

https://github.com/user-attachments/assets/77c1d069-589b-4220-94f6-8c7c9e9b6829

### 你期望的 API 是什么样子的？

https://github.com/user-attachments/assets/77c1d069-589b-4220-94f6-8c7c9e9b6829

**Comment by Timeless0911** [comment]
This is a nice feature, but we don't support it yet.

Rspress now support [Built-in Smooth Transition Animation](https://rspress.dev/guide/start/introduction#built-in-smooth-transition-animation) on route change, we can also support using view transitions API on appearance toggle in the future and PR is welcome for that.

**Comment by ayangweb** [comment]
我可以提供 pr，能给我一个 pr 的思路吗？我应该提供一个 api 来实现它吗？

**Comment by Timeless0911** [comment]
> 我可以提供 pr，能给我一个 pr 的思路吗？我应该提供一个 api 来实现它吗？

This may be a little difficult to implement, we hope to make it as opt-in like below.

```ts
export default defineConfig({
  themeConfig: {
    // on route change
    enableContentAnimation: true,
    // on appearance toggle
    enableAppearanceAnimation: true,
  },
});
```

`enableContentAnimation` has been implemented, but the effect is not particularly good right now.

Or maybe we can do it simply, add a slot in [SwitchAppearance](https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/components/SwitchAppearance/index.tsx) to let users inject some logic.

I prefer the former solution, as a built-in optimization that can be turned on and off.

**Comment by ayangweb** [comment]
> > 我可以提供 pr，能给我一个 pr 的思路吗？我应该提供一个 api 来实现它吗？
> 
> This may be a little difficult to implement, we hope to make it as opt-in like below.
> 
> ```ts
> export default defineConfig({
>   themeConfig: {
>     // on route change
>     enableContentAnimation: true,
>     // on appearance toggle
>     enableAppearanceAnimation: true,
>   },
> });
> ```
> 
> `enableContentAnimation` has been implemented, but the effect is not particularly good right now.
> 
> Or maybe we can do it simply, add a slot in [SwitchAppearance](https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/components/SwitchAppearance/index.tsx) to let users inject some logic.
> 
> I prefer the former solution, as a built-in optimization that can be turned on and off.

OK，和我的想法一样，我先熟悉下项目，空了提一个 pr 上来！

**Comment by ayangweb** [comment]
[`packages/theme-default/src/components/SwitchAppearance`](https://github.com/web-infra-dev/rspress/tree/main/packages/theme-default/src/components/SwitchAppearance)

我修改了文件内容，但是我不知道为啥它没有工作！

```tsx
import { type MouseEvent, useContext } from 'react';
import { ThemeContext } from '@rspress/runtime';
import SunSvg from '@theme-assets/sun';
import MoonSvg from '@theme-assets/moon';
import { SvgWrapper } from '../SvgWrapper';
import siteData from 'virtual-site-data';
import { isUndefined } from 'lodash-es';

export function SwitchAppearance({ onClick }: { onClick?: () => void }) {
  const { theme, setTheme } = useContext(ThemeContext);

  const supportAppearanceTransition = () => {
    return (
      !isUndefined(document) &&
      document.startViewTransition &&
      !window.matchMedia('(prefers-reduced-motion: reduce)').matches
    );
  };

  const handleClick = (event: MouseEvent) => {
    const supported = supportAppearanceTransition();
    const enabled = siteData.themeConfig.enableAppearanceAnimation;

    console.log('supported', supported);
    console.log('enabled', enabled);

    const nextTheme = theme === 'dark' ? 'light' : 'dark';
    const isDark = nextTheme === 'dark';

    console.log('nextTheme', nextTheme);
    console.log('isDark', isDark);

    if (supported && enabled) {
      console.log('进来了');

      const x = event.clientX;
      const y = event.clientY;

      const endRadius = Math.hypot(
        Math.max(x, innerWidth - x),
        Math.max(y, innerHeight - y),
      );

      const transition: any = document.startViewTransition(() => {
        setTheme(nextTheme);
        onClick?.();
      });

      console.log('到这了');

      transition.ready.then(() => {
        const clipPath = [
          `circle(0px at ${x}px ${y}px)`,
          `circle(${endRadius}px at ${x}px ${y}px)`,
        ];

        document.documentElement.animate(
          {
            clipPath: isDark ? [...clipPath].reverse() : clipPath,
          },
          {
            duration: 400,
            easing: 'ease-in',
            pseudoElement: isDark
              ? '::view-transition-old(root)'
              : '::view-transition-new(root)',
          },
        );
      });
    } else {
      setTheme(nextTheme);
      onClick?.();
    }
  };

  return (
    <div onClick={handleClick} className="md:mr-2 rspress-nav-appearance">
      <div className="p-1 border border-solid border-gray-300 text-gray-400  cursor-pointer rounded-md hover:border-gray-600 hover:text-gray-600 dark:hover:border-gray-200 dark:hover:text-gray-200 transition-all duration-300 w-7 h-7">
        <SvgWrapper
          className="dark:hidden"
          icon={SunSvg}
          width="18"
          height="18"
          fill="currentColor"
        />
        <SvgWrapper
          className="hidden dark:block"
          icon={MoonSvg}
          width="18"
          height="18"
          fill="currentColor"
        />
      </div>
    </div>
  );
}
```

```scss
.sun {
  opacity: 1;
}

.moon {
  opacity: 0;
}

:global(.dark) .sun {
  opacity: 0;
}

:global(.dark) .moon {
  opacity: 1;
}

:global(html) {
  &::view-transition-old(root),
  &::view-transition-new(root) {
    animation: none;

    mix-blend-mode: normal;
  }

  &::view-transition-old(root) {
    z-index: 1;
  }

  &::view-transition-new(root) {
    z-index: 9999;
  }
}

:global(.dark) {
  &::view-transition-old(root) {
    z-index: 9999;
  }

  &::view-transition-new(root) {
    z-index: 1;
  }
}
```

<img width="261" alt="image" src="https://github.com/user-attachments/assets/e6d98c58-9d35-4f43-9ef8-f3660806be17">

**Comment by Timeless0911** [comment]
You can push your code and draft a PR, can you help with him? @SoonIter

**Comment by SoonIter** [comment]
push your code

> You can push your code and draft a PR, can you help with him? @SoonIter

yeah, of course

**Comment by ayangweb** [comment]
> > You can push your code and draft a PR, can you help with him? @SoonIter
> 
> yeah, of course

https://github.com/web-infra-dev/rspress/pull/1272
