### ISSUE TITLE
[docs]: Add a separate section to describe how to use shared mdx as components in other mdx files

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#1284]
### What problem does this feature solve?

Add a separate section to describe how to use shared mdx as components in other mdx files. 
like https://rspress.dev/guide/basic/use-mdx#use-component

### What does the proposed API look like?

-

**Comment by chenjiahan** [comment]
Add users should configure `route.exclude` too

https://github.com/web-infra-dev/rspress/blob/main/packages/document/rspress.config.ts#L42
