### ISSUE TITLE
[Feature]: Unify the logger style

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#129]
### What problem does this feature solve?

The logger style of Rspress and Modern.js Builder are different now:

<img width="449" alt="Screenshot 2023-09-28 at 14 58 42" src="https://github.com/web-infra-dev/rspress/assets/7237365/c48dceb9-cf00-4752-9b60-0b51dd80305e">

### What does the proposed API look like?

@sanyuan0704 Do you want Rspress's logger style to be consistent with Modern.js?

If so, I can release the `@modern-js/utils/logger` module as a separate package, and let Rspress / Rsbuild / Modern.js to use it.

**Comment by sanyuan0704** [comment]
Yeah, no problem.

**Comment by chenjiahan** [comment]
I will work on it, and the package name will be `rslog` 😄

**Comment by zoolsher** [comment]
cool name

**Comment by chenjiahan** [comment]
rslog has been released: https://github.com/rspack-contrib/rslog

**Comment by sanyuan0704** [comment]
Awesome! I will add it in rspress.
