### ISSUE TITLE
[Bug]: 图片放在文档目录时，图片文件会出现在侧边栏中

### ISSUE THREAD

**Issue by stevobm** [web-infra-dev/rspress#1292]
### 版本信息

```sh
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 67.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 17.5
  npmPackages:
    rspress: ^1.22.0 => 1.22.0
```

### 问题详情

图片在文档目录中的位置如下：
<img width="255" alt="image" src="https://github.com/user-attachments/assets/b9e0082b-9593-4985-89e7-f42d62bda302">
图片文件会出现在侧边导航栏中：
<img width="417" alt="image" src="https://github.com/user-attachments/assets/c605cfa5-d631-4902-85e2-b83ea1d5c582">
点击该文件，页面会出现404

期待结果：除了文档、代码类文件之外，其他文件不会在侧边导航栏出现

### 复现链接

无

### 复现步骤

无

**Comment by Timeless0911** [comment]
You should put your static resouces in `public` folder and use absolute path `/rspress.png` to import.

Or you can use `_meta.json` to define sidebar https://rspress.dev/guide/basic/auto-nav-sidebar

**Comment by stevobm** [comment]
> You should put your static resouces in `public` folder and use absolute path `/rspress.png` to import.
> 
> Or you can use `_meta.json` to define sidebar https://rspress.dev/guide/basic/auto-nav-sidebar

这样确实可以实现。但是绝大部分知识库(如Notion)批量导出文档的时候，文档内引用的图片等资源都会放在相对路径下，如果这样一个个修改工作量会非常大。如果这个bug得以修复，那么就可以实现知识库无缝迁移到RsPress，这不是非常棒吗？

**Comment by Timeless0911** [comment]
Tracking in #1327
