### ISSUE TITLE
[Bug]: 使用了@rspress/plugin-typedoc 之后编译报错

### ISSUE THREAD

**Issue by pcdeng** [web-infra-dev/rspress#1306]
### 版本信息

```sh
System:
  OS: Windows 11 10.0.22621
  CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
  Memory: 2.81 GB / 15.30 GB
Browsers:
  Edge: Chromium (127.0.2651.74)
  Internet Explorer: 11.0.22621.1
npmPackages:
  @rspress/plugin-typedoc: ^1.27.0 => 1.27.0
  rspress: ^1.27.0 => 1.27.0
```

node -v 
v16.14.2

pnpm -v
8.6.0

### 问题详情

node_modules/.pnpm/@rspack+core@1.0.0-beta.1_@swc+helpers@0.5.11/node_modules/@rspack/core/dist/Watching.d.ts:7:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

7     #private;
      ~~~~~~~~

node:internal/process/promises:279

### 复现链接

https://github.com/pcdeng/rspress-typedoc-demo

### 复现步骤

1、pnpm i
2、pnpm dev

**Comment by SoonIter** [comment]
could you please try below?

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["DOM", "ES2020"],
    "module": "ESNext",
    "jsx": "react-jsx",
    "noEmit": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "resolveJsonModule": true,
    "moduleResolution": "bundler"
  },
  "mdx": {
    "checkMdx": true
  }
}

```

**Comment by pcdeng** [comment]
> could you please try below?
> 
> ```js
> // tsconfig.json
> {
>   "compilerOptions": {
>     "target": "ES2020",
>     "lib": ["DOM", "ES2020"],
>     "module": "ESNext",
>     "jsx": "react-jsx",
>     "noEmit": true,
>     "skipLibCheck": true,
>     "isolatedModules": true,
>     "resolveJsonModule": true,
>     "moduleResolution": "bundler"
>   },
>   "mdx": {
>     "checkMdx": true
>   }
> }
> ```

works good now
