### ISSUE TITLE
[Bug] Auto generated sidebar should consider `route.excludes` when `_meta.json` do not exists

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#1327]
> You should put your static resouces in `public` folder and use absolute path `/rspress.png` to import.
> 
> Or you can use `_meta.json` to define sidebar https://rspress.dev/guide/basic/auto-nav-sidebar

这样确实可以实现。但是绝大部分知识库(如Notion)批量导出文档的时候，文档内引用的图片等资源都会放在相对路径下，如果这样一个个修改工作量会非常大。如果这个bug得以修复，那么就可以实现知识库无缝迁移到RsPress，这不是非常棒吗？

_Originally posted by @stevobm in https://github.com/web-infra-dev/rspress/issues/1292#issuecomment-2286524759_

**Comment by Timeless0911** [comment]
We should do some filter logic to exclude items which not ended with [route.extensions](https://rspress.dev/zh/api/config/config-basic#routeextensions) in https://github.com/web-infra-dev/rspress/blob/906dcba4dc846607a69588c7065fab0f53e53d73/packages/plugin-auto-nav-sidebar/src/walk.ts#L40-L92

**Comment by shulaoda** [comment]
I will try to implement this feature.
