### ISSUE TITLE
[Bug]: 无法设置 output.distPath

### ISSUE THREAD

**Issue by ianzone** [web-infra-dev/rspress#1335]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Memory: 12.48 GB / 15.45 GB
    Container: Yes
    Shell: 5.9 - /home/linuxbrew/.linuxbrew/bin/zsh
  npmPackages:
    rspress: ^1.27.0 => 1.28.0
```

### Details

根据[这个文档](https://rspress.dev/zh/api/config/config-build#builderconfig)我将产出路径设置为`dist`，但是无论设置成什么，实际输出路径总是`doc_build`

### Reproduce link

https://codesandbox.io/p/devbox/epic-chatterjee-cp7pqr

### Reproduce Steps

打开终端执行 npm run build

**Comment by Timeless0911** [comment]
use https://rspress.dev/zh/api/config/config-basic#outdir

**Comment by ianzone** [comment]
那 builderConfig 这个选项有歧义

**Comment by Timeless0911** [comment]
文档里缺少了一些不能通过 `builderConfig` 修改的 Rsbuild 配置的描述，感谢指出~
