### ISSUE TITLE
[Docs] The documentation is missing some descriptions of Rsbuild configurations that cannot be modified via `builderConfig`

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#1336]
文档里缺少了一些不能通过 `builderConfig` 修改的 Rsbuild 配置的描述，感谢指出~

_Originally posted by @Timeless0911 in https://github.com/web-infra-dev/rspress/issues/1335#issuecomment-2293222251_

**Comment by ianzone** [comment]
除了修改文档，最好是在 rspress/config 的接口中屏蔽掉
