### ISSUE TITLE
[Docs]: 官网增加展示页面

### ISSUE THREAD

**Issue by ianzone** [web-infra-dev/rspress#1337]
### 这个功能解决了什么问题？

看看大家是怎么使用 repress 的

### 你期望的 API 是什么样子的？

类似 https://docusaurus.io/showcase

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspress/discussions/607

**Comment by ianzone** [comment]
或许可以用自动手段收集，如果用户打开了非回环地址的rspress站点，就向你们服务器发送站点域名，这样还可以根据访问量进行排序。

**Comment by Timeless0911** [comment]
> 或许可以用自动手段收集，如果用户打开了非回环地址的rspress站点，就向你们服务器发送站点域名，这样还可以根据访问量进行排序。

我们不能做收集数据上报的工作哈
