### ISSUE TITLE
[Bug]: 非markdown文件在特定情况下会被写入到侧边栏目录中

### ISSUE THREAD

**Issue by KunerRick** [web-infra-dev/rspress#1349]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 8.22 GB / 15.83 GB
  Browsers:
    Edge: Spartan (44.18362.1533.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    rspress: ^1.28.0 => 1.28.1
```

### 背景
因为现有markdown文档较多，我在尝试通过Typescript 脚本来遍历 docs下的文档，然后动态更新 目录下的_meta.json中的配置。
### 出现问题
部分markdown文档目录下，单独创建了imgs目录来存放所要引用的图片，此时外层目录已经生成了_meta.json，而imgs目录中由于没有markdown文档，因此并未生成_meta.json，结构大致如下：
![image](https://github.com/user-attachments/assets/b04271e8-f3af-478a-b98c-b867c124858e)
其中_meta.json 如下
```json
[
  "index",
  {
    "type": "dir",
    "name": "imgs",
    "label": "没有Markdown"
  }
]

```
构建完成后，侧边栏目录表现为
![image](https://github.com/user-attachments/assets/835749c5-7b8e-4cb2-8d68-9e003ffb886d)
但这个1其实 是 图片。
### 期望

类似的，子级目录如果没有指定_meta.json ，是否也不应该将 里面的非md文件添加到侧边目录呢？
或者有没有什么配置可以规避此类问题？

### 复现链接

https://codesandbox.io/p/devbox/bold-dew-dyn243

### 复现步骤

1. 调整目录 和 _meta.json 如下图
2. ![image](https://github.com/user-attachments/assets/b04271e8-f3af-478a-b98c-b867c124858e)
3. 执行构建
4. 查看侧边栏目录
5.在 codeSandbox 中表现如下
![image](https://github.com/user-attachments/assets/8cb857da-5df8-4f32-9b6a-3e5ac63611ae)

**Comment by Timeless0911** [comment]
same as https://github.com/web-infra-dev/rspress/issues/1327
