### ISSUE TITLE
[Bug]: `checkDeadLinks` is unavailable for custom react components

### ISSUE THREAD

**Issue by zmzlois** [web-infra-dev/rspress#1355]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 45.59 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.85
    Edge: 128.0.2739.42
    Safari: 17.2.1
  npmPackages:
    @rspress/mdx-rs: ^0.5.7 => 0.5.7 
    @rspress/plugin-shiki: ^1.23.1 => 1.23.1 
    rspress: ^1.18.1 => 1.18.1
```

### Details

We have some custom react components on our website, but the `checkDeadLinks` seemed to be unavailable for links in these components

### Reproduce link

https://github.com/ZephyrCloudIO/zephyr-documentation

### Reproduce Steps

1. run `npm run install && npm run dev` 
2. Click on cards on `Recipes` page 
3. links are broken but nothings shows up on console

**Comment by Timeless0911** [comment]
This is as expected. `checkDeadLinks ` only statically parse the link syntax `[xx](xx)`directly in the mdx file and cannot dynamically analyze the component props of tsx.
