### ISSUE TITLE
[Bug]: yarn create rspress@latest Failed

### ISSUE THREAD

**Issue by Alkaidcc** [web-infra-dev/rspress#1357]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M2
    Memory: 532.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.122
    Safari: 17.6
```

### Details

yarn create rspress@latest
yarn create v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-rspress@1.28.2" with binaries:
      - create-rspress
/bin/sh: /Users/.yarn/bin/create-rspress@latest: No such file or directory
error Command failed.
Exit code: 127
Command: /Users/.yarn/bin/create-rspress@latest
Arguments:
Directory: /Users/playground
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

yarn version: 1.22.22

### Reproduce link

https://rspress.dev/zh/guide/start/getting-started

### Reproduce Steps

1. run `yarn create rspress@latest`

**Comment by Timeless0911** [comment]
You can use `yarn create rspress` for yarn especially, I will update the docs soon, thank you!
