### ISSUE TITLE
[Bug]: 搜索功能在通过键盘的方向键切换数据时，切换到可视区的最后一项数据，继续切换，会导致数据定位错乱

### ISSUE THREAD

**Issue by asyncguo** [web-infra-dev/rspress#1364]
### 版本信息

```sh
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 147.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.86
    Chrome Canary: 121.0.6125.0
    Edge: 128.0.2739.42
    Safari: 16.5
  npmPackages:
    rspress: ^1.26.1 => 1.26.3
```

### 问题详情

搜索功能在通过键盘的方向键进行上下切换数据时，在滚动到可视区最后一项数据时，继续往下切换时，数据定位发生错乱，不是继续往下定位下一个筛选项，而是自动滚动到了上面的某一项。

具体现象：
1. 当通过方向键向下切换时，定位数据为可视区最后一项数据时
2. 继续向下切换时，定位数据跑到了上面的某一项，而不是当前筛选项的下一个
![image](https://github.com/user-attachments/assets/7b665797-c3c2-4797-91b3-e25d00bbe20d)
![image](https://github.com/user-attachments/assets/51ea1115-1638-420a-8246-7bd13ef16e4b)

原因分析：在切换到可视区最后一个数据时，再往下切换时，导致了页面的滚动，从而同时触发了键盘事件与鼠标事件，进而导致高亮的筛选项设置了两遍
1. 切换到最后一项时，继续切换时，触发键盘事件 [KEY_CODE.ARROW_DOWN](https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/components/Search/SearchPanel.tsx#L165)
```tsx
case KEY_CODE.ARROW_DOWN:
    if (focused) {
      e.preventDefault();
      if (
        currentSuggestions &&
        currentRenderType === RenderType.Default
      ) {
        setCanScroll(true);
        setCurrentSuggestionIndex(
          (currentSuggestionIndex + 1) % currentSuggestions.length,
        );
      }
    }
    break;
```
2. 此时页面会自动向上滚动，而滚动时，由于鼠标现在浮现在【筛选项A】，此时会触发【筛选项A+1】的[onMouseEnter](https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/components/Search/SuggestItem.tsx#L120) 事件，进而又一次更新了高亮的筛选项，所以最后真正高亮的不是键盘控制的筛选项
```tsx
<li
    key={suggestion.link}
    className={`${styles.suggestItem} ${isCurrent ? styles.current : ''}`}
    onMouseEnter={setCurrentSuggestionIndex}
    ref={selfRef}
  >
  // ...
</li>
```

尝试解法：记录鼠标位置信息，onMouseEnter 事件触发时判断位置是否一致，不一致才进行更新
1. 记录鼠标在筛选项 onMouseMove 时的坐标，触发 onMouseEnter  时判断鼠标和上次的位置信息是否一致
2. 同时还需要取消筛选项 hover 时的效果，否则会出现高亮效果比较割裂的体验（其实 current 类的效果就是高亮的效果 ）

### 复现链接

https://rspress.dev/zh/guide/advanced/custom-search

### 复现步骤

前提条件是当鼠标浮动在某一个筛选项上时，再通过键盘的方向键向下切换时，切换到可视区最后一项数据时，就会复现

**Comment by Timeless0911** [comment]
Nice catch, but I think we still need to keep the highlight when the mouse hovers over it since we need to let the user know the selected block when clicking with the mouse.

**Comment by asyncguo** [comment]
> Nice catch, but I think we still need to keep the highlight when the mouse hovers over it since we need to let the user know the selected block when clicking with the mouse.

即使去掉 `:hover` 选择器，也会有高亮效果的，因为 `onMouseMove` 时会通过 `setCurrentSuggestionIndex`更新 `currentSuggestionIndex`，从而触发[`.current `](https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/components/Search/index.module.scss#L176)选择器的高亮样式，所以不会丢失筛选项的高亮效果。
![image](https://github.com/user-attachments/assets/172f202f-e474-441b-a499-48b73b2cbed2)
![image](https://github.com/user-attachments/assets/fc2e40a0-f89c-4939-84ad-70d4a7af9d38)

**Comment by Timeless0911** [comment]
Great, can you implement a PR to achieve your goal？

**Comment by asyncguo** [comment]
> Great, can you implement a PR to achieve your goal？

ok，let me try it
