### ISSUE TITLE
[Bug]: 自动生成目录没有过滤非md和mdx之外的文件

### ISSUE THREAD

**Issue by bosens-China** [web-infra-dev/rspress#1365]
### 版本信息

```sh
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 64.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.85
    Safari: 17.6
```

### 问题详情

例如我放置了一个data.json，页面还渲染了这个
![image](https://github.com/user-attachments/assets/b163d07c-4b73-48f7-b841-66e23a009dac)
![image](https://github.com/user-attachments/assets/b2a63962-4393-4923-906f-76b636fc45a3)

### 复现链接

none

### 复现步骤

none

**Comment by Timeless0911** [comment]
Duplicate of https://github.com/web-infra-dev/rspress/issues/1327
