### ISSUE TITLE
[Feature][@rspress/plugin-rss]: Support RSS html feedline for Rspack/Rstack toolings blog

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspress#1405]
### What problem does this feature solve?

At present, the document of Rspack or Rsbuild website is in md format, which makes us unable to browse normally in the Rss reader

https://rspack.dev/rss/blog-rss.xml
https://rspack.dev/rss/blog-rss-zh.xml

<img width="400" alt="image" src="https://github.com/user-attachments/assets/536f2d0e-264d-43bb-9c20-89671b5fe770">

our expected behavior is output the html format

related to https://github.com/web-infra-dev/rspress/pull/851

### What does the proposed API look like?

support html and can be viewed in rss reader like https://github.com/RSSNext/Follow

**Comment by seeintea** [comment]
Is it possible to throw `html` data? The `content` currently used is processed.

https://github.com/web-infra-dev/rspress/blob/main/packages/core/src/node/runtimeModule/siteData/extractPageData.ts#L92

```ts
content = htmlToText(String(html), {
  wordwrap: 80,
  selectors: [
    /* ... */
    {
      selector: 'img',
      format: 'skip',
    },
    {
      // Skip code blocks
      selector: 'pre > code',
      format: 'skip',
    },
    /* ... */
  ],
  tables: true,
  longWordSplit: {
    forceWrapOnLimit: true,
  },
});
```

**Comment by SoonIter** [comment]
> Is it possible to throw `html` data? The `content` currently used is processed.

Yeah, just do it
