### ISSUE TITLE
[Feature]: Use font awesome `title: <title>` as H1 heading if no H1 heading is added

### ISSUE THREAD

**Issue by o-l-a-v** [web-infra-dev/rspress#1440]
### What problem does this feature solve?

Given following example `index.md` file:

```md
---
title: Heading 1
---

## Heading 2

Some content
```

In Docusaurus this would add `Heading 1` as the title of the document. But in RSPress:

![Image](https://github.com/user-attachments/assets/0712c69e-3c7c-4f46-9cf8-507508dd4533)

One can add an additional `Heading 1` in the document, but then markdownlint will complain about the document having two top-level headings, MD025.

* <https://github.com/DavidAnson/markdownlint/blob/main/doc/md025.md>

![Image](https://github.com/user-attachments/assets/8dff6692-1cdd-4ed6-abfe-d85776a126cf)

### What does the proposed API look like?

I have no idea.

**Comment by Yukiniro** [comment]
If the `overview` of frontmatter is `true`, the page will use [`Overview`](https://rspress.dev/api/client-api/api-components#overview) component to render. And Overview component will not render the h1 title if `title` is truth value.

```js
        {!title && (
          <h1 className="text-3xl leading-10 tracking-tight mb-4 sm:mb-0">
            Overview
          </h1>
        )}
```

I think #1493  will fix it.

**Comment by seeintea** [comment]
> If the `overview` of frontmatter is `true`, the page will use [`Overview`](https://rspress.dev/api/client-api/api-components#overview) component to render. And Overview component will not render the h1 title if `title` is truth value.
> 
>         {!title && (
>           <h1 className="text-3xl leading-10 tracking-tight mb-4 sm:mb-0">
>             Overview
>           </h1>
>         )}
> I think [#1493](https://github.com/web-infra-dev/rspress/pull/1493) will fix it.

but for other types of pages, is it possible to use the title in `frontmatter` if it is not given?
