### ISSUE TITLE
[Bug]: yarn dev pending when using some special characters as title

### ISSUE THREAD

**Issue by killdada** [web-infra-dev/rspress#1457]
### 版本信息

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz
    Memory: 17.40 GB / 31.95 GB
  Browsers:
    Edge: Spartan (44.19041.1.0)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    rspress: ^1.32.0 => 1.32.0

### 问题详情

![Image](https://github.com/user-attachments/assets/84fa1770-1ac1-4670-a88a-a88d03819198)

### 复现链接

https://codesandbox.io/p/devbox/goofy-yalow-94jm3q?workspaceId=efd5821f-9fb5-42c6-81b3-e2f553205837

### 复现步骤

yarn dev 卡住

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspress/blob/e2ebf7a26cb19f5f8230c39b09aa62f7336b5752/packages/core/src/node/runtimeModule/siteData/extractPageData.ts#L128-L141

This is related to here, I will fixed soon this week.
