### ISSUE TITLE
[Feature]: @rspress/core need cjs output

### ISSUE THREAD

**Issue by ChenXplorer** [web-infra-dev/rspress#1479]
### What problem does this feature solve?

@rspress/core need cjs output

### What does the proposed API look like?

@rspress/core need cjs output

**Comment by Timeless0911** [comment]
What scenarios require cjs output?

**Comment by ChenXplorer** [comment]
> What scenarios require cjs output?

I don't want to use the rspress CLI method; I want to manually import rspress/core and implement the build myself. This way, I can migrate my old project and seamlessly convert the configuration.

**Comment by Timeless0911** [comment]
> I don't want to use the rspress CLI method; I want to manually import rspress/core and implement the build myself. This way, I can migrate my old project and seamlessly convert the configuration.

I think the JS Api of esm format is available to meet your demands.

**Comment by ChenXplorer** [comment]
> > I don't want to use the rspress CLI method; I want to manually import rspress/core and implement the build myself. This way, I can migrate my old project and seamlessly convert the configuration.
> 
> I think the JS Api of esm format is available to meet your demands.

butr, my current CLI is in CJS format, and importing @rspress/core results in an error，just like  since No "exports" main defined in /@rspress/core/package.json.  How should I solve this problem?

**Comment by Timeless0911** [comment]
`use ESM packages in CJS` is a classic topic, you can search a lot of information or articles in Google. eg. https://antfu.me/posts/publish-esm-and-cjs

**Comment by Timeless0911** [comment]
We shipped pure ESM packages to advocate the ecosystem to move from CJS to ESM at the beginning, so we do not plan to lean to dual package.

**Comment by ChenXplorer** [comment]
> We shipped pure ESM packages to advocate the ecosystem to move from CJS to ESM at the beginning, so we do not plan to lean to dual package.

okay，thx
