### ISSUE TITLE
[Bug]: custom component with css module, its style does not work on development

### ISSUE THREAD

**Issue by JounQin** [web-infra-dev/rspress#1484]
### Version

  System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 27.39 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 18.0.1
  npmPackages:
    rspress: ^1.33.1 => 1.33.1

### Details

![Image](https://github.com/user-attachments/assets/2333a2e3-f34b-4591-a3af-abd7a529caee)

![Image](https://github.com/user-attachments/assets/600f14da-b544-479d-b7b2-7d0330a97970)

![Image](https://github.com/user-attachments/assets/38126708-b57e-4850-9c7b-62c0b3fec0a2)

The css `className` is correct, but no style injected on development.

![Image](https://github.com/user-attachments/assets/47e92498-ef2f-4720-879d-870622c7c0c8)

But on preview mode, it works.

### Reproduce link

https://github.com/JounQin/rspress-reproduction

### Reproduce Steps

```sh
yarn
yarn dev
```

Then open `http://localhost:3000/zh/overview`

**Comment by JounQin** [comment]
It seems importing non css module `.scss` file (`import './index.scss'`) also does not work on development.

**Comment by Timeless0911** [comment]
![Image](https://github.com/user-attachments/assets/103f39bb-b7d1-49ea-a214-2f6657d5f94f)

I can not reproduce.

**Comment by JounQin** [comment]
@Timeless0911 Are you running on machine or codesandbox?

**Comment by Timeless0911** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/50201324?s=64&amp;u=7c0bcad937f94993e1710bcbfbf3e0c4334d1e1c&amp;v=4">@Timeless0911](https://github.com/Timeless0911) Are you running on machine or codesandbox?

On my personal macbook.

**Comment by JounQin** [comment]
Damn... It's caused by [Chrome Local Overrides](https://developer.chrome.com/docs/devtools/overrides)...

I wasted a whole day on it.
