### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'toString') when `markdown.mdxRs: false`

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#1489]
### Details

related PR: #1469 

If we use Blockquotes and Links together and set `markdown.mdxRs: false`

```mdx
> [foo](bar)
```

error will occured

![Image](https://github.com/user-attachments/assets/e201c75c-4651-4dfc-b134-727d31582ed2)

### Reproduce Steps

1. open arbitrary rspress projects
2. write in mdx file
```mdx
> [foo](bar)
```
3. `pnpm run dev`

**Comment by Timeless0911** [comment]
@ArnavK-09 Hey, can you fix this issue and write some e2e tests in https://github.com/web-infra-dev/rspress/tree/main/e2e/fixtures to test this feature?

**Comment by ArnavK-09** [comment]
> @ArnavK-09 Hey, can you fix this issue and write some e2e tests in https://github.com/web-infra-dev/rspress/tree/main/e2e/fixtures to test this feature?

I'll try to ot, but can you guide me how can I use local container plugin for realtime development with document or theme

I tried but it isn't working, it's still using published one not the locally developed one container plugin

**Comment by ArnavK-09** [comment]
> @ArnavK-09 Hey, can you fix this issue and write some e2e tests in https://github.com/web-infra-dev/rspress/tree/main/e2e/fixtures to test this feature?

I'll try to fix it but can you guide me how can I use locally available container plugin rather than published one into document or theme
I'll tried but isn't working in real time

**Comment by Timeless0911** [comment]
Using `pnpm.overrides` in your  `package.json` of Rspress project like

```json
"pnpm": {
  "overrides": {
    "@rspress/core": "link:../../../rspress/packages/core"
  }
}
```

**Comment by ArnavK-09** [comment]
👍
