### ISSUE TITLE
[Bug]: Tab component cannot be switched under iOS 15

### ISSUE THREAD

**Issue by baranwang** [web-infra-dev/rspress#1505]
### Version

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 109.00 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 17.4.1
  npmPackages:
    @rspress/shared: ^1.33.0 => 1.33.0 
    rspress: ^1.33.0 => 1.33.0 

### Details

收到用户反馈，iOS 15.1 下 `Tab` 组件无法切换，让用户试了一下 rspress 官网，同样可以复现

### Reproduce link

-

### Reproduce Steps

<video src="https://github.com/user-attachments/assets/a0d3a9e9-de49-4382-b757-a5b879296181" />

**Comment by Timeless0911** [comment]
Rspress 使用 Rsbuild 进行编译构建，浏览器兼容问题可以查看 Rsbuild 文档配置合适的 browserlist https://rsbuild.dev/zh/guide/advanced/browserslist#%E8%AE%BE%E7%BD%AE-browserslist

**Comment by Timeless0911** [comment]
可以贴一下浏览器控制台具体的报错信息

**Comment by baranwang** [comment]
@Timeless0911 我手边没有 iOS 15 设备诶，因为看到 rspress 官网也是同样复现的，也许是不是可以用 bits 的云真机注入 vconsole 帮忙看一下（我是给一个社区的开源项目搭的文档站，占用公司资源不太好（狗头

**Comment by baranwang** [comment]
@Timeless0911 利用模拟器复现问题，发现是页面初始化时 js 执行错误，导致整个页面所有利用 js 的点击事件失效

![Image](https://github.com/user-attachments/assets/9bedb63d-865c-431b-b7b5-bd15c2963b0e)
![Image](https://github.com/user-attachments/assets/4d656d87-e674-4e02-a309-4b697a975357)

```
                var tx = /`(.*?)`/g,
                    tv = RegExp("\\*{2}(?!\\*)(.*?)(?<!\\*)\\*{2}", "g"),
                    tg = RegExp("\\*(?!\\*)(.*?)(?<!\\*)\\*", "g");
```
