### ISSUE TITLE
[Bug]: Error when using absolute path to reference online resources (non-local resources) in less

### ISSUE THREAD

**Issue by ChenXplorer** [web-infra-dev/rspress#1515]
### Version

macos

### Details

 Module build failed:
  ╰─▶   × Error: HookWebpackError: Cannot find module '/image/font/xxx.ttf'
        │

### Reproduce link

/

### Reproduce Steps

/

**Comment by chenjiahan** [comment]
See https://github.com/web-infra-dev/rsbuild/issues/1948

**Comment by ChenXplorer** [comment]
> See [web-infra-dev/rsbuild#1948](https://github.com/web-infra-dev/rsbuild/issues/1948)

i can not resolve this problem,

when add the following code:
  builderConfig:{
    output: {
      externals: [/\/image\/font/g],
    },
  },

error :
 × Module build failed:
  ╰─▶   × Error: HookWebpackError: Invalid regular expression flags
