### ISSUE TITLE
[Bug]:How can I correctly locate the ssg build error

### ISSUE THREAD

**Issue by citrusjunoss** [web-infra-dev/rspress#1528]
### Version

system： macos
npmPackages：
    "react-photo-view": "^1.2.6",
    "rspress": "^1.35.1",
    "rspress-plugin-file-tree": "^0.4.0",
    "rspress-plugin-live2d": "^0.3.0",
    "rspress-plugin-reading-time": "^0.3.0",

### Details

How can I correctly locate the ssg build error, the stack information provided by the console can't be debugged

![Image](https://github.com/user-attachments/assets/8b54b6f2-f43f-443f-9ce0-9bead852cacf)

I tried a global search for window, it's not in the source code, it exists in a third party dependency, but need more log information to help me locate it, can you help me?

### Reproduce link

xxxx

### Reproduce Steps

1. npm run build

**Comment by SoonIter** [comment]
1. set the config below in `rspress.config.ts`

```typescript
defineConfig({
	builderConfig: {
		tools: {
			rspack: {
				optimization: {
					moduleId: 'named'
				}
			}
		}
	}
})
```

2. `DEBUG=rsbuild rspress build`

3. click the error capture stack, and jump to the `main.cjs`
investigate which 3rd library does not support SSR

**Comment by SoonIter** [comment]
thanks for your trying Rspress,

this is a common question, and we may need to optimize the `Failed to load SSG bundle` error message

**Comment by citrusjunoss** [comment]
It's working fine.
