### ISSUE TITLE
[Bug]: Title with "\<" (escaped brackets) will crush the API overview

### ISSUE THREAD

**Issue by Huxpro** [web-infra-dev/rspress#1536]
### Version

  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.50 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.71
    Safari: 18.1
  npmPackages:
    @rspress/plugin-client-redirects: ^1.28.2 => 1.32.0 

### Details

Type-based doc generation tools e.g. Typedoc, may render title with TS generic syntax `Component\<P, S\>` and will cause the inner markdown renderer of sidebar menu crush:

![Image](https://github.com/user-attachments/assets/36c43ff5-9516-45a1-9438-87dbdd41cba4)

### Reproduce link

N/A

### Reproduce Steps

Have markdown titled as:

```md
# Class: Component\<P, S\>
```

**Comment by Huxpro** [comment]
Besides of fixing this particular issues, we should use more `ErrorBoundary` to prevent the page from being completely blank

**Comment by Huxpro** [comment]
Emm another weird case

![Image](https://github.com/user-attachments/assets/113eb6fa-57a6-4f64-bcff-7adf3596f9e6)

**Comment by Timeless0911** [comment]
> Type-based doc generation tools e.g. Typedoc, may render title with TS generic syntax Component\<P, S\> and will cause the inner markdown renderer of sidebar menu crush:

This is because in the parsing process of htmr when rending inline markdown text, `<P` has a special meaning in htmr, you can replace it with other variable names `<Z` maybe.

I prefer to use `` when rending code like text.

```mdx
# Class: `Component<d, S, SS>`
```

![Image](https://github.com/user-attachments/assets/b85430e7-0abd-447c-ba20-0dba9c357222)

**Comment by Huxpro** [comment]
> > Type-based doc generation tools e.g. Typedoc, may render title with TS generic syntax Component\<P, S\> and will cause the inner markdown renderer of sidebar menu crush:
> 
> This is because in the parsing process of htmr when rending inline markdown text, `<P` has a special meaning in htmr, you can replace it with other variable names `<Z` maybe.
> 
> I prefer to use `` when rending code like text.
> 
> ```mdx
> # Class: `Component<P, S, SS>`
> ```
> 
> ![Image](https://github.com/user-attachments/assets/dc7ed7ac-c642-4aae-a7aa-7fc62c8f2f6d)
> 
> 

As I had mentioned, this is generated by tools that I have no control over its output. 

As a rule of thumb: Rspress should not crush within its own anyways - you should either support it or report the error gracefully and specifies clearly what's supported and what's not.

**Comment by Timeless0911** [comment]
> As I had mentioned, this is generated by tools that I have no control over its output.
> 
> As a rule of thumb: Rspress should not crush within its own in any cases - you should either find a way to support the inputs, or report unsupported inputs gracefully and specifies clearly what's supported and what's not - so it's possible for me to come out with a workaround.

Yes, we need better solutions for some runtime errors. The above are some workarounds which can make your codes work temporarily.

**Comment by Huxpro** [comment]
![Image](https://github.com/user-attachments/assets/e98357ab-2acc-4643-8640-59d2e4806a22)

It seems like `<Aside>` can suffer from this as well
