### ISSUE TITLE
[Bug]: Dev Server Crush During Restart

### ISSUE THREAD

**Issue by Huxpro** [web-infra-dev/rspress#1550]
### Version

  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 4.09 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.1
  npmPackages:
    @rspress/plugin-client-redirects: ^1.28.2 => 1.32.0 

### Details

![Image](https://github.com/user-attachments/assets/a93819e5-ddf8-4285-8312-a5a37d3e9657)

### Reproduce link

N/A

### Reproduce Steps

Let me know if you can't repro this I can give you an internal link

**Comment by Timeless0911** [comment]
This should be an issue with the internal layer package.
