### ISSUE TITLE
[Feature]: expose components from @rspress/theme-default

### ISSUE THREAD

**Issue by liuwenzhuang** [web-infra-dev/rspress#1569]
### What problem does this feature solve?

I want to extend default theme, like add navmenu components. but I couldn't use components from @rspress/theme-default. If use self custom component, the compatibility with the original style will be difficult to guarantee.

### What does the proposed API look like?

import { SomeComponent } from 'rspress/default'

**Comment by Timeless0911** [comment]
You can read https://rspress.dev/guide/advanced/custom-theme#3-custom-home-page-and-404-page

```tsx
import Theme from 'rspress/theme';
import { Layout as BaseLayout } from 'rspress/theme';
import { Nav as BaseNav } from 'rspress/theme';

const Layout = () => {
  return <BaseLayout />;
};

export const Nav = () => {
  return (
    <>
      custom word
      <BaseNav />
    </>
  );
};

export default {
  ...Theme,
  Layout,
};

export * from 'rspress/theme';

```

![Image](https://github.com/user-attachments/assets/eb59fd16-a82d-41ed-aa11-d9fc31d3020d)

**Comment by liuwenzhuang** [comment]
I found how to extend deault theme, which I need is the specific sigular components from @rspress/theme-default, and replace *custom word* area which from your example. For example, if I want to add a custom outsides links in navbar, the NavGroup components from @rspress/theme-default  is the best choice.

**Comment by Timeless0911** [comment]
Why not use [socialLinks](https://rspress.dev/api/config/config-theme#sociallinks)? And currently we does not provide exports of internal components like `NavMenuGroup` to extend part of `Nav`.
