### ISSUE TITLE
[Bug]: 部署到github page页面后image请求路径错误

### ISSUE THREAD

**Issue by aliothor** [web-infra-dev/rspress#158]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 20.29 GB / 31.86 GB
  Browsers:
    Edge: Chromium (117.0.2045.60)
    Internet Explorer: 11.0.22621.1
```

### 问题详情

构建后assetPrefix配置没有生效，网站首页请求图片失败

### 复现链接

https://github.com/aliothor/blog

### 复现步骤

1、pnpm i
2、pnpm preview

**Comment by sanyuan0704** [comment]
感谢反馈哈，应该是图片地址缺少了 base 路径，我来马上修复哈

**Comment by aliothor** [comment]
好的，感谢您的回复，不过还有一个问题

**Comment by sanyuan0704** [comment]
这是初始化模板的问题哈，我来清除一下这个 import 语句，当做 mdx 之后会根据相对路径找模块，而脚手架里面是没有`fragments/mdx-rs.mdx` 这个文件的

**Comment by sanyuan0704** [comment]
@aliothor
