### ISSUE TITLE
[Bug]: plugin-preview not rerender after code change

### ISSUE THREAD

**Issue by liuwenzhuang** [web-infra-dev/rspress#1652]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 10.97 GB / 15.62 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    rspress: ^1.38.0 => 1.38.0
```

### Details

I have configure `@rspress/plugin-preview` plugin into rspress.config.ts，and in mdx file write code like below:

```tsx
export default () => <div>test 1</div>
```

open localhost:3000 after pnpm dev, the preview component show *test 1*, and then change the *test 1* to *test 2*, the preview component not rerender, the component still show *test 1*, the code area show *test 2* however.

![Image](https://github.com/user-attachments/assets/04651a86-20ff-486e-951d-28783772914b)

### Reproduce link

https://codesandbox.io/p/devbox/jxvk3m

### Reproduce Steps

1. pnpm i && pnpm dev
2. change code in `docs/index.mdx`
3. the preview component not rerender

**Comment by liuwenzhuang** [comment]
Maybe the reason is `react-fast-refresh` exclude files in `/node_modules/`, and the preview components is located in `node_modules/.rspress/virtual-demo/`.

**Comment by Timeless0911** [comment]
Yes, this is related to a change in Rsbuild https://github.com/web-infra-dev/rsbuild/pull/4058, we improve performance by ignoring node_modules formly. I think `@rspress/plugin-preview` plugin should watch `node_modules` to fix this issue.
