### ISSUE TITLE
[Bug]: ERR_REQUIRE_ESM: lodash-es is esm package, use mergeDocConfig from @rspress/shared/dist/node-utils.js will failed

### ISSUE THREAD

**Issue by liuwenzhuang** [web-infra-dev/rspress#1655]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 10.97 GB / 15.62 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    rspress: ^1.38.0 => 1.38.0
```

### Details

after build, `@rspress/shared/dist/node-utils.js` likes:

```js
// src/node-utils/merge.ts
var import_lodash_es = require("lodash-es");
```

but `lodash-es` is esm package, requie will failed:

```bash
var import_lodash_es = require("lodash-es");
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/lodash.js from node_modules/.pnpm/@rspress+shared@1.38.0/node_modules/@rspress/shared/dist/node-utils.js not supported.
Instead change the require of lodash.js in node_modules/.pnpm/@rspress+shared@1.38.0/node_modules/@rspress/shared/dist/node-utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (node_modules/.pnpm/@rspress+shared@1.38.0/node_modules/@rspress/shared/dist/node-utils.js:64:24) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Reproduce link

nope

### Reproduce Steps

nope

**Comment by Timeless0911** [comment]
I will change this to dynamic import then. And I wonder how can you find this API?

**Comment by liuwenzhuang** [comment]
> I will change this to dynamic import then. And I wonder how can you find this API?

modern.js use `@modern-js/plugin-rspress` will trigger this error, and I have a rspress plugin which use this API.

**Comment by liuwenzhuang** [comment]
> I will change this to dynamic import then. And I wonder how can you find this API?

change dynamic import will convert `mergeDocConfig` to async function, does it compatible with plugin?

**Comment by Timeless0911** [comment]
> > I will change this to dynamic import then. And I wonder how can you find this API?
> 
> change dynamic import will convert `mergeDocConfig` to async function, does it compatible with plugin?

Plugin hook should also support async function.
