### ISSUE TITLE
[Bug]: Copy public dir to dist failed

### ISSUE THREAD

**Issue by coratgerl** [web-infra-dev/rspress#1684]
### Version

```sh
System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 56.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 121.1.62.153
    Safari: 18.0
```

### Details

I have an issue during the build of my project on docker. Seems the bug is fixed on last version of rsbuild, but maybe rspress need to update rsbuild version.

PR that seems to fix this : https://github.com/web-infra-dev/rsbuild/pull/4220

> [app-landing-builder 5/5] RUN bun run build:
0.242 $ rspress build
0.686 🔥 Rspress v1.38.0
0.686
1.206 EEXIST: Copy public dir (/app/docs/public) to dist failed:
1.206 File or folder exists
1.206    errno: -17
1.206  syscall: "mkdir"
1.206    path: "/app/doc_build"
1.206
1.208

### Reproduce Steps

Here is my dockerfile: 

```ts
FROM oven/bun:latest AS app-landing-builder
WORKDIR /app

COPY ./packages/app-landing .

RUN bun install --frozen-lockfile
RUN bun run build

FROM oven/bun:latest AS app-landing-runner
WORKDIR /app

# Copy built files from builder stage
COPY --from=app-landing-builder /app/node_modules ./node_modules
COPY --from=app-landing-builder /app/doc_build ./doc_build
COPY --from=app-landing-builder /app/package.json ./package.json
COPY --from=app-landing-builder /app/rspress.config.ts ./rspress.config.ts

CMD ["bun", "preview", "--port", "3001", "--host", "0.0.0.0"]

```

**Comment by Timeless0911** [comment]
Got it, we will update it and release a new version in next week. You can downgrade rspress to use a version that depends on lower version of Rsbuild now.

**Comment by chenjiahan** [comment]
Fixed by Rsbuild: https://github.com/web-infra-dev/rsbuild/releases/tag/v1.1.12
