### ISSUE TITLE
[Bug]: the link of directory's index.html in sidebar is not rendered correctly

### ISSUE THREAD

**Issue by jackywu** [web-infra-dev/rspress#1706]
### Version

```sh
System:
    OS: macOS 13.7.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 6.78 GB / 32.00 GB
    Shell: Unknown
  Browsers:
    Edge: 131.0.2903.112
    Safari: 16.6
  npmPackages:
```

### Details

this is my files structure, each sub-folder like 'planet-helper' and 'evernote-helper' has it's own index.md which will be built into index.html by rspress.

![Image](https://github.com/user-attachments/assets/1ce031f3-c124-439d-bb1a-ab117ab05b46)

this is the rendered sidebar. when click the folder name such as "星球助手" whose doc is in 'planet-helper folder, then we're expect to go to the index page that should be `https://superassist.net/guide/planet-helper/index.html`
![Image](https://github.com/user-attachments/assets/762a58a9-f290-4ae5-87f6-11fdcfc115b7)
but  unfortunately we got a incorrect url in address bar of browser , like this
![Image](https://github.com/user-attachments/assets/710775ef-a7cb-483a-9333-8de64f771052)
we know the url should be `https://superassist.net/guide/planet-helper/index.html` or `https://superassist.net/guide/planet-helper/`.

the following is content of `/docs/_meta.js`.
```
[
  "index",
  {
    "type": "divider",
    "dashed": true
  },
  {
    "type": "dir",
    "name": "chatgpt",
    "label": "chatgpt"
  },
  {
    "type": "dir",
    "name": "evernote-helper",
    "label": "印象助手"
  },
  {
    "type": "dir",
    "name": "planet-helper",
    "label": "星球助手"
  },
  {
    "type": "dir",
    "name": "media-helper",
    "label": "自媒体助手"
  },
  {
    "type": "dir",
    "name": "palm-helper",
    "label": "Palm助手"
  },
  {
    "type": "dir",
    "name": "qa",
    "label": "常见问题"
  }
]

```

### Reproduce link

https://superassist.net/guide/planet-helper/index.html

### Reproduce Steps

1. create dir like `docs/guide/planet-helper`, and put a `index.md` in this folder.
2. run `npm run dev` to launch the local server that should be `http://localhost:3000/`
3. click the folder name '星球助手', then you got the incorrect url.
4. you could also see the issue on this online page <https://superassist.net/guide/planet-helper/index.html>

**Comment by Timeless0911** [comment]
It's as expected, see https://github.com/web-infra-dev/rspress/pull/1575.

You can add a `_meta.json` in `planet-helper` folder if you want to treat index as child sidebar as before.

**Comment by jackywu** [comment]
great, thanks
