### ISSUE TITLE
[Feature]: Enhance `navbar` to integrate more configuration

### ISSUE THREAD

**Issue by coratgerl** [web-infra-dev/rspress#1713]
### What problem does this feature solve?

Currently, we have no way to make the navbar sticky on mobile, which I think could be improved. I propose adding a navbar object in the theme config to allow configuration of various navbar elements, such as its position (sticky or not) on mobile and desktop.

Additionally, we could integrate the hideNavbar functionality into a hide field within the navbar object. If we decide to move hideNavbar, we could deprecate it first before fully migrating to avoid breaking compatibility.

I'm not sure what you think about this approach and whether it would be suitable. What are your thoughts?

I can propose myself to do this change.

### What does the proposed API look like?

```ts
themeConfig: {
   navbar : {
       position : {
           onMobile: 'sticky' | 'relative',
           onDesktop: 'sticky' | 'relative',
       },
       hide: 'never' | 'always' | 'auto',
       // Others potential configs in future ...
       closeIcon: boolean
   }
}
```

**Comment by Timeless0911** [comment]
Can we make `themeConfig.hideNavbar` configuration work on mobile instead? Adding `themeConfig.navbar` configuration is a bit too complicated I think.

**Comment by coratgerl** [comment]
If I correctly understand what `themeConfig.hideNavbar` does, it only hide or not the navbar, it is not related to the position of the navbar no ?

**Comment by Timeless0911** [comment]
> If I correctly understand what `themeConfig.hideNavbar` does, it only hide or not the navbar, it is not related to the position of the navbar no ?

What's the difference between `sticky` and `relative`, the current status is that when navbar is not hided, it will sticky at the top.

**Comment by coratgerl** [comment]
Ok I understand so there is a bug actually because on mobile the navbar is not sticky at the top. I will fix this in a PR so
