### ISSUE TITLE
[Feature]: plugin-jsdoc

### ISSUE THREAD

**Issue by SnowingFox** [web-infra-dev/rspress#172]
### 这个功能解决了什么问题？

解析jsdoc生成静态文档

### 你期望的 API 是什么样子的？

和typedoc用法类似
```[tasklist]
### Tasks
```

**Comment by sanyuan0704** [comment]
可以看看这个插件，已经支持了 jsdoc，不过文档还没放出来，在规划当中 https://github.com/web-infra-dev/rspress/tree/main/packages/plugin-api-docgen
