### ISSUE TITLE
[Bug]: 在cli进行新建项目的时候描述没有进行转义字符化导致的编译错误

### ISSUE THREAD

**Issue by DawnMagnet** [web-infra-dev/rspress#174]
### 版本信息

```sh
System:
OS: Linux 6.5 Garuda Linux
CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
Memory: 5.01 GB / 15.33 GB
Container: Yes
Shell: 5.9 - /bin/zsh
```

### 问题详情

在新建项目描述里填写存在`'`字符的时候，并没有将其转义，而是直接添加到了`rspress.config.ts`中。

例如如果在描述中输入"I'm good"，最终的配置中会出现`description: 'I'm good',`。

### 复现链接

任何环境均可复现

### 复现步骤

使用官方提供的创建步骤进行创建即可复现

**Comment by DawnMagnet** [comment]
已经尝试在 <https://github.com/web-infra-dev/rspress/pull/175> 进行解决

**Comment by sanyuan0704** [comment]
#175
