### ISSUE TITLE
[Feature]: Support monorepo

### ISSUE THREAD

**Issue by jas0ncn** [web-infra-dev/rspress#180]
### What problem does this feature solve?

Currently, rspress could not support perfectly, when we write docs in packages, and defined sidebar using `_meta.json`, it's not working.

The monorepo dir structure is usually as below:
```
- docs      # top level docs
   - _meta.json
- packages
  - pkg1
     - docs
     - _meta.json
  - pkg2
     - docs
     - _meta.json
  - pkg3
     - docs
     - _meta.json
```

### What does the proposed API look like?

Just add monorepo supporting, and better provide plugin API at the same time.

**Comment by sanyuan0704** [comment]
In default mode all the docs should be put in the same direcotry(That is `docs` in your case). And if you want to add some docs in other places, we recommend to use plugin and `addPages` hook to register the route of docs. Details: https://rspress.dev/plugin/system/plugin-api.html#addpages

 And in this way, you should configure the sidebar and nav bar in `themeConfig.nav/sidebar` of Rspress instead of using `_meta.json`. https://rspress.dev/api/config/config-theme.html#nav

**Comment by chenjiahan** [comment]
Should we support using glob patterns to match documents? It can be easier than the `addPages` API.

**Comment by sanyuan0704** [comment]
It is currently support by `route.include` config.https://rspress.dev/api/config/config-basic.html#routeinclude cc @jas0ncn 

> Should we support using glob patterns to match documents? It can be easier than the `addPages` API.

**Comment by jas0ncn** [comment]
> It is currently support by `route.include` config.https://rspress.dev/api/config/config-basic.html#routeinclude cc @jas0ncn
> 
> > Should we support using glob patterns to match documents? It can be easier than the `addPages` API.

Thanks, but even if using the `route.include` to match ducuments, we still need to configure sidebar manually, `_meta.json` is easier to use obviously😭

**Comment by flycj** [comment]
> > It is currently support by `route.include` config.https://rspress.dev/api/config/config-basic.html#routeinclude cc @jas0ncn
> > > Should we support using glob patterns to match documents? It can be easier than the `addPages` API.
> 
> Thanks, but even if using the `route.include` to match ducuments, we still need to configure sidebar manually, `_meta.json` is easier to use obviously😭

我通过这样的配置
![image](https://github.com/web-infra-dev/rspress/assets/5103045/7892c147-8b6f-4b50-a8b1-0c00fec3427d)
没有生成对应的可访问路径
检查方式是，写了一个测试插件，通过日志打印
![image](https://github.com/web-infra-dev/rspress/assets/5103045/c28d3070-87da-43c1-b365-0d2246e72433)

发现没有路由信息
而我的项目种确实有对应的md文件，这是什么问题呢？
![image](https://github.com/web-infra-dev/rspress/assets/5103045/1c6a8675-cc8b-4a8b-94db-6ea686ad2de8)
