### ISSUE TITLE
[Bug]: Unable to display images using `<img/>`

### ISSUE THREAD

**Issue by zhenghui-su** [web-infra-dev/rspress#183]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 7.05 GB / 15.86 GB
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.3570.0), Chromium (117.0.2045.60)
    Internet Explorer: 11.0.19041.3570
```

### If I use `<img/>`tags to import online images, they will not be displayed, but if I use '! [] () ` can be displayed

![image](https://github.com/web-infra-dev/rspress/assets/104132375/54e0f72c-6ccd-40a9-bccb-56e41f48c593)

### The result should be two images, but the page only has one

![image](https://github.com/web-infra-dev/rspress/assets/104132375/65175cc8-d025-47ad-ae7c-01bfe62d0ccb)

### Reproduce link

This is just a small question, so I don't have a project address

### Reproduce Steps

Using `img` tags and using `![]()` create two images and then view the page

**Comment by sanyuan0704** [comment]
Do you use the img tag in mdx file? The jsx grammer is only valid in mdx

**Comment by sanyuan0704** [comment]
@zhenghui-su

**Comment by zhenghui-su** [comment]
Thank you for your answer
