### ISSUE TITLE
[Bug]: firefox 下目录布局出错

### ISSUE THREAD

**Issue by impossible98** [web-infra-dev/rspress#186]
### 版本信息

```sh
System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 18.37 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Edge: 118.0.2088.46
    Safari: 17.0
```

### 问题详情

firefox 下左侧目录布局出错，官方文档网址布局就是有问题的

### 复现链接

https://rspress.dev/guide/start/introduction

### 复现步骤

用firefox 打开 https://rspress.dev/guide/start/introduction 就能看到

**Comment by sanyuan0704** [comment]
![image](https://github.com/web-infra-dev/rspress/assets/39261479/824d928f-ae73-4ef5-9ee2-21e9339f4fae)
 
具体是哪部分的布局问题？

**Comment by impossible98** [comment]
多2个目录滚条， 我的是windows版的firefox
![olk_87KnpghTkY.png](https://img1.imgtp.com/2023/10/15/D32RF8S5.png)

**Comment by sanyuan0704** [comment]
知道了，应该是 .rspress-scrollbar 的样式没有适配 firefox 导致的
