### ISSUE TITLE
[Feature]: Heading IDs customization support

### ISSUE THREAD

**Issue by hustcer** [web-infra-dev/rspress#198]
### What problem does this feature solve?

I am trying to migrate from docusaurus to rspress just to find that the customization of heading ids havn't been supported yet, something like this:  https://docusaurus.io/docs/markdown-features/toc#heading-ids

### What does the proposed API look like?

Some feature just like docusaurus provides

**Comment by sanyuan0704** [comment]
Thanks for feedback! I will support the feature right away.

**Comment by sanyuan0704** [comment]
Rspress v1.1.0 has support custom header id by default.https://rspress.dev/guide/basic/use-mdx.html#customizing-anchor-id

**Comment by sanyuan0704** [comment]
@hustcer
