### ISSUE TITLE
[Feature]: How to Support HTML Writing of Configuration Items

### ISSUE THREAD

**Issue by wolf-leo** [web-infra-dev/rspress#201]
### What problem does this feature solve?

I wrote it this way, but the result was

![_20231018104907](https://github.com/web-infra-dev/rspress/assets/37436228/4d2afab4-13c0-4a2f-a276-97ca6fcebc76)

![_20231018104739](https://github.com/web-infra-dev/rspress/assets/37436228/f6efb018-89d0-4db1-8469-4ecbe9f141e4)

### What does the proposed API look like?

HTML support

**Comment by sanyuan0704** [comment]
The text and tagline don't support html currently. Is anyone interested in implementing this feature?

**Comment by byteHulk** [comment]
> 文本和标语目前不支持 html。有人有兴趣实现这个功能吗？

我来试试?

**Comment by sanyuan0704** [comment]
> > 文本和标语目前不支持 html。有人有兴趣实现这个功能吗？
> 
> 我来试试?

可以的
