### ISSUE TITLE
[Bug]: HMR not work for sidebar label

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#231]
### Version

```sh
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.30 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.6
  npmPackages:
    @rspress/shared: ^1.1.1 => 1.1.1 
    rspress: ^1.1.1 => 1.1.1
```

### Details

After updating the `h1` of a markdown file, the sidebar label can not be updated, it cannot be updated even after refreshing the page.

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/85182d4d-d71f-4bed-9101-cbb5020c8f02)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/main/packages/document

### Reproduce Steps

1. Update `h1` in markdown file.

**Comment by sanyuan0704** [comment]
It is an important bug and we will follow up for long term.
