### ISSUE TITLE
[Bug]: App crash due to add _meta.json or yaml format error

### ISSUE THREAD

**Issue by recallwei** [web-infra-dev/rspress#235]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 206.80 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.96
    Safari: 17.0
  npmPackages:
    rspress: ^1.1.3 => 1.1.3
```

### Details

After creating `_meta.json`, the app will crash. Then it prompts that the port is already in use, I should restart the app manually.
![image](https://github.com/web-infra-dev/rspress/assets/62941121/e21c3061-61f1-4064-9564-f1e3de3ac51f)
I changed the frontmatter in `index.md`, and the app also crashed. Throw out a yaml exception, that makes a bad DX.
![image](https://github.com/web-infra-dev/rspress/assets/62941121/3a63d040-42f4-46c4-944e-44018709d910)

### Reproduce link

https://github.com/web-infra-dev/rspress/tree/main/packages/create-rspress/template

### Reproduce Steps

Use rspress default template.
1. Update frontmatter in `index.md`, deliberately creating yaml syntax error.
2. Add new page, then add a `_meta.json`.

**Comment by sanyuan0704** [comment]
Thank you very much for feedback. I understand that it hurt DX a lot and i will fix the problem right away.
