### ISSUE TITLE
[Bug]: Can't search with cyrillics data

### ISSUE THREAD

**Issue by BorisChumichev** [web-infra-dev/rspress#239]
### Version

```sh
System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1
    Memory: 815.19 MB / 16.00 GB
    Shell: 3.5.1 - /opt/local/bin/fish
  Browsers:
    Chrome: 118.0.5993.96
  npmPackages:
    rspress: ^1.0.0 => 1.1.3
```

### Details

Documents search feature does not work for Cyrillic texts

### Reproduce link

https://github.com/BorisChumichev/rspress-cyrillic-search

### Reproduce Steps

1. `git clone git@github.com:BorisChumichev/rspress-cyrillic-search.git`
2. `npm install`
3. `npm run dev`
4. Open project in your web browser and try to search for `птиц`
5. No results will be found although `docs/guide/index.md` contains several matches.

**Comment by ssoda01** [comment]
To solve this problem, you can add the cyrilic configuration to FlexSearch
```typescript
    // packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
    this.#cyrilicIndex = FlexSearch.create({ ... })
```
For this, I have provided a pr
I'm not sure if my pr is good enough to be merged, but maybe it will helps you.

Maybe using `searchHooks` would be a good way as well, details are at [Customize Search Functions - Rspress](https://rspress.dev/guide/advanced/custom-search.html)
