### ISSUE TITLE
[Bug]: themeConfig.socialLinks weixin does't work

### ISSUE THREAD

**Issue by recallwei** [web-infra-dev/rspress#240]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.15 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.96
    Safari: 17.0
  npmPackages:
    rspress: ^1.1.3 => 1.1.3
```

### Details

wexin icon does not work.
<img width="325" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/c6ab1e05-1240-4c41-9296-e1a15dbeabba">
<img width="246" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/67282bcc-fb82-41a6-9367-33a93bbb5c65">

### Reproduce link

https://web-dev.brucesong.xyz/

### Reproduce Steps

`themeConfig.socialLinks` add below:
```json
{        
  "icon": "weixin",
  "mode": "text",
  "content": ""
}
```

**Comment by sanyuan0704** [comment]
Yeah, it's a type error and the real value is `wechat` instead of `weixin` 😄
