### ISSUE TITLE
[Bug]:  Sidebar link have different weird behaviour

### ISSUE THREAD

**Issue by recallwei** [web-infra-dev/rspress#241]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.80 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.96
    Safari: 17.0
  npmPackages:
    rspress: ^1.1.3 => 1.1.3
```

### Details

<img width="315" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/fb4b947a-9ee6-48ef-bd43-3b7f26a716b2">
These links cannot redirect to their own sidebar.
Codebase: https://github.com/recallwei/recallwei/tree/main/docs

### Reproduce link

https://web-dev.brucesong.xyz/

### Reproduce Steps

Click nav links and sidebar links, they act in different behaviour.

**Comment by sanyuan0704** [comment]
It also confused a lot. But fortunately i have fixed the problem in #290
