### ISSUE TITLE
[Bug]: Right aside nav item doesn't highlight automatically while opening in a new tab

### ISSUE THREAD

**Issue by hustcer** [web-infra-dev/rspress#257]
### Version

```sh
System:
    OS: macOS 13.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 20.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.6
  npmPackages:
    rspress: ^1.2.0 => 1.2.0
```

### Details

 Right aside nav item doesn't highlight automatically while opening in a new tab

### Reproduce link

https://rspress.dev/zh/guide/basic/auto-nav-sidebar.html#%E6%97%A0%E9%85%8D%E7%BD%AE%E7%94%A8%E6%B3%95

### Reproduce Steps

1. Click and jump to the link: https://rspress.dev/zh/guide/basic/auto-nav-sidebar.html#%E6%97%A0%E9%85%8D%E7%BD%AE%E7%94%A8%E6%B3%95 to open it in a new tab
2. The page content scroll to viewport as expected, however the right aside of the nav item doesn't highlight properly
3. Even refresh the whole page doesn't work either

**Comment by sanyuan0704** [comment]
The latest 1.5.1 version has solved the problem
