### ISSUE TITLE
[Feature]: fill contribute guide

### ISSUE THREAD

**Issue by FireBushtree** [web-infra-dev/rspress#258]
### What problem does this feature solve?

After i clone the repo and run `pnpm install`, i do not know how to debug the code. 

### What does the proposed API look like?

I try to do like this:

1. at **repress** repo exec `pnpm link --global`
2. at **debug** repo exec `pnpm link --global rspress`
3. if i want to debug `package / core`. at **repress** repo exec `cd ./package/core` & `pnpm run dev`

after this action, so i can debug code. Am I doing the right thing? if right, i want to write these into `CONTRIBUTING.md`, if wrong, please give me some advice. :)

**Comment by sanyuan0704** [comment]
Nice! Welcome to add these guide docs.
