### ISSUE TITLE
[Feature]: Allow to configure prism languages

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#26]
### What problem does this feature solve?

Currently, the prism languages of Rspress is fixed, and users may want to support other languages, so we should provide a configure for it.

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/ea0a9a86-d10d-4b50-bbd8-87a6119e427d)

### What does the proposed API look like?

```js
export default defineConfig({
    markdown: {
      highlightLanguages: ['ejs', 'yaml'],
   },
});
```

**Comment by byteHulk** [comment]
- 新增一个类型吗? 
interface Doc {
  markdown: { highlightLanguages: string[] };
}  

- 通过虚拟模块把用户的 config 导入 registerLanguages 代码这里?

**Comment by sanyuan0704** [comment]
> * 新增一个类型吗?   
>   interface Doc {
>   markdown: { highlightLanguages: string[] };
>   }
> * 通过虚拟模块把用户的 config 导入 registerLanguages 代码这里?

可以的

**Comment by byteHulk** [comment]
#195 

不过这里好像并没有实现轻量引入, 看了下, 会自动打包 refractor / lowlight 的 index.js , 这两个 js 里都有全量注册语言的代码

<img width="965" alt="image" src="https://github.com/web-infra-dev/rspress/assets/33158585/9ecfc4ce-fa6a-4235-9931-cbf95aa1fd70">

<img width="665" alt="Pasted Graphic 1" src="https://github.com/web-infra-dev/rspress/assets/33158585/796a9193-0153-470e-af31-211e96464271">
