### ISSUE TITLE
[Bug]: cycle dependencies

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspress#264]
### Version

```sh
nothing
```

### Details

There are numerous cyclic dependencies obstructing the NX build.
For instance

```
@rspress/plugin-container-syntax:build --> rspress:build --> @rspress/core:build --> @rspress/plugin-medium-zoom:build --> rspress:build
```

NX is uncertain whether to compile ﻿rspress or ﻿@rspress/core first.

### Reproduce link

nothing

### Reproduce Steps

nothing

**Comment by bvanjoi** [comment]
I propose the extraction of ﻿`@rspress/runtime` so every plugin would only need to depend on it.

**Comment by sanyuan0704** [comment]
Good advice!

> I propose the extraction of ﻿`@rspress/runtime` so every plugin would only need to depend on it.
