### ISSUE TITLE
[Bug]: some relative URL in markdown is broken 

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#266]
### Version

```sh
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.31 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.6
  npmPackages:
    @rspress/shared: 1.2.0 => 1.2.0 
    rspress: 1.2.0 => 1.2.0
```

### Details

`/guide/basic/builder-config.html` is replaced to `/builder/en/guide/basic-config.html`

Input:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/871669d2-620f-4bb4-b59f-13c7d3ea39f6)

Output:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/f4d5e9a4-fa0b-423e-be2c-6130071936cd)

### Reproduce link

https://github.com/web-infra-dev/modern.js/tree/main/packages/document/builder-doc

### Reproduce Steps

1. pnpm dev
2. open http://localhost:8080/builder/en/guide/debug/debug-mode.html#builder-config-file

**Comment by sanyuan0704** [comment]
It seems not a relative url.

**Comment by chenjiahan** [comment]
My mistake, it is a pathname in URL.
