### ISSUE TITLE
[Bug]: Code highlight for bash is not work after build

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#272]
### Version

```sh
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.45 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
  npmPackages:
    @rspress/shared: ^1.2.1 => 1.2.1 
    rspress: ^1.2.1 => 1.2.1
```

### Details

Input:

````markdown
```bash
# Install the long-term support version of Node.js 18
nvm install 18 --lts

# Make the newly installed Node.js 18 as the default version
nvm alias default 18

# Switch to the newly installed Node.js 18
nvm use 18
```
````

`pnpm run dev`:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/6660b5fe-a11c-4bef-a006-ee3a6b4f1792)

`pnpm run build:doc && pnpm run preview`:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/e62770ac-3800-4d2c-81d0-03db173923f3)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/main/packages/document

### Reproduce Steps

1. clone https://github.com/web-infra-dev/rsbuild
2. cd pacakges/document
3. pnpm run dev
4. pnpm run build:doc && pnpm run preview

**Comment by FireBushtree** [comment]
`rspress` default not support `bash` language. Just see the [doc](https://rspress.dev/api/config/config-build.html#markdownhighlightlanguages).

## fix

Add `markdown.highlightLanguages` at `rspress.config.ts`.
<img width="327" alt="image" src="https://github.com/web-infra-dev/rspress/assets/32190667/f9c1d2b0-5711-42d4-b072-33b19ad79cec">

**Comment by chenjiahan** [comment]
Get👌 I will try it, thanks!

**Comment by sanyuan0704** [comment]
Maybe we can add `bash` in default languages. @FireBushtree

**Comment by FireBushtree** [comment]
ok, i wil do this. :)
