### ISSUE TITLE
[Feature]: support configure preview plugin's default behavior

### ISSUE THREAD

**Issue by kainstar** [web-infra-dev/rspress#275]
### What problem does this feature solve?

The preview plugin now treats all `jsx` or `tsx` code blocks as renderable React components, except for those with the `pure` meta. However, there are cases where we display the most of code blocks and render a small portion of them as a component.

Could we add an option property to control the default behavior of rendering code blocks as previews or simply displaying them?

### What does the proposed API look like?

1. add new option property in `@rspress/plugin-preview`

```ts
export type Options = {
  defaultBehavior: 'preview' | 'only-code'
}
```

2. add new meta identifier to enable preview mode for a code block
~~~mdx
```tsx preview
function App() {
  return "Hello World";
}
export default App;
```
~~~

**Comment by sanyuan0704** [comment]
Good advice! Are you interested in implementing this feature?

**Comment by kainstar** [comment]
Sure, I'll give it a shot later. Any suggestions on the API or property?

**Comment by sanyuan0704** [comment]
It's better to keep the meta string same as the default behavior string.
