### ISSUE TITLE
[Bug]: preview <code /> not working in nested jsx

### ISSUE THREAD

**Issue by kainstar** [web-infra-dev/rspress#277]
### Version

```sh
System:
  OS: macOS 12.5
  CPU: (8) arm64 Apple M2
  Memory: 94.36 MB / 24.00 GB
  Shell: 5.8.1 - /bin/zsh
Browsers:
  Chrome: 117.0.5938.132
  Safari: 15.6
npmPackages:
  @rspress/plugin-last-updated: ^1.2.1 => 1.2.1 
  @rspress/plugin-preview: ^1.2.1 => 1.2.1 
  @rspress/plugin-typedoc: ^1.2.1 => 1.2.1 
  rspress: ^1.2.1 => 1.2.1
```

### Details

The `<code src="path" />` syntax provide a simple way to use complex components. I want to customize the outer layout of the preview and wrap the `code` with a layout component like this:

```mdx
<div className="layout">
  <code src="../demos/index.tsx" />
</div>
```

However, it failed. The `code` is not transformed into the preview component and retains its original content.

![image](https://github.com/web-infra-dev/rspress/assets/15249633/8a5cff69-5b9f-4b4a-8eb3-17fba3d47bd8)

### Reproduce link

https://github.com/kainstar/reproduce/tree/main/rspress-preview-in-nested-jsx-not-working

### Reproduce Steps

1. `pnpm install`
2. open `http://localhost:8080`
3. only one preview block in page, expect two

**Comment by sanyuan0704** [comment]
Thank you for feedback. It'a bug from the AST traverse logic in preview plugin.
