### ISSUE TITLE
[Bug]: 设置 base 后， logo 无法显示，本地预览是有的，部署到 GitHub Pages 后就显示不出来了

### ISSUE THREAD

**Issue by yy1300326388** [web-infra-dev/rspress#284]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 501.39 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0
  npmPackages:
    rspress: ^0.1.1 => 1.1.3
```

### Details

我的网站 https://flutterads.github.io/site/
访问不显示 logo，我看编译后的文件是有的，但是访问时就没有，结果发现是少了 site
- https://flutterads.github.io/logo.png
- https://flutterads.github.io/site/logo.png

我的配置如下：

```
import * as path from 'path';
import { defineConfig } from 'rspress/config';

export default defineConfig({
  root: 'docs',
  base: '/site/',
  title: 'FlutterAds',
  description: '让你的 Flutter 应用广告收益翻倍',
  icon: "/icon.png",
  logo: "/logo.png",
  themeConfig: {
    search: false,
    socialLinks: [
      { icon: 'github', mode: 'link', content: 'https://github.com/FlutterAds' },
    ],
    footer: {
      message: '© 2023 FlutterAds Team. All Rights Reserved.',
    },
    prevPageText: '上一页',
    nextPageText: '下一页',
  },
});

```

![image](https://github.com/web-infra-dev/rspress/assets/8764899/29927585-4a38-4250-b8cc-be890b233c00)
![image](https://github.com/web-infra-dev/rspress/assets/8764899/e4326254-45af-4409-add5-5132142aabe0)

### Reproduce link

https://flutterads.github.io/site/

### Reproduce Steps

- pnpm run build
- Deploy to GitHub Pages

**Comment by sanyuan0704** [comment]
无法复现，你升级到 1.2.1 版本看看

**Comment by yy1300326388** [comment]
是你本地复现吗？我本地预览也是无法复现的，到 GitHub Pages 上就会出问题，我现在是将资源放了 2份，如下图。
![image](https://github.com/web-infra-dev/rspress/assets/8764899/b1538619-4b67-490e-9e81-42f4dd1a4889)

> 我升级到最新版本试试吧

**Comment by yy1300326388** [comment]
@sanyuan0704 
我使用最新的版本 build 后预览，logo 是可以了，但是页面中的图片还是不行

![image](https://github.com/web-infra-dev/rspress/assets/8764899/7d0e7b74-89da-4cdd-864a-155594904ed2)
![image](https://github.com/web-infra-dev/rspress/assets/8764899/80ec5acd-5941-4bf2-9e0e-e023502f622e)
![image](https://github.com/web-infra-dev/rspress/assets/8764899/a099bdf2-a65e-48e1-8d5f-b3b136d9442c)

```
<img src="/site/wechat.webp" width='220px'/> //加了 site 可以显示
![wechat](/wechat.webp) //无法显示
```

**Comment by sanyuan0704** [comment]
#298 正在修复中

**Comment by sanyuan0704** [comment]
v1.3.0 已修复

**Comment by yy1300326388** [comment]
我测试还是有问题哈
@sanyuan0704 具体看 PR 回复

**Comment by sanyuan0704** [comment]
https://github.com/web-infra-dev/rspress/pull/298

**Comment by yy1300326388** [comment]
已解决啦👍

需要看看这里的文档：https://rspress.dev/zh/guide/basic/static-assets.html

![](https://user-images.githubusercontent.com/39261479/279608985-cf3af3ef-97b4-4d8f-ac87-50a00f97cfa1.png)
