### ISSUE TITLE
[Bug]: 渲染代码片段标签丢失

### ISSUE THREAD

**Issue by shenxiang11** [web-infra-dev/rspress#287]
### 版本信息

```sh
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 42.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.117
    Edge: 118.0.2088.76
    Safari: 17.0
  npmPackages:
    @rspress/core: ^1.2.1 => 1.2.1 
    @rspress/plugin-playground: ../rspress/packages/plugin-playground => 1.2.1 
    rspress: ^1.0.0 => 1.0.1
```

### 问题详情

![image](https://github.com/web-infra-dev/rspress/assets/17292115/3cb0ba71-34a4-4228-86a7-6ab19fcff610)

图中，渲染的代码片段缺少标签

### 复现链接

https://rspress.dev/plugin/official-plugins/playground.html

### 复现步骤

当前官网 https://rspress.dev/plugin/official-plugins/playground.html 这个页面就存在问题，搜索 tsx pure 定位到对应的位置。

**Comment by sanyuan0704** [comment]
Yeah, thank you for feedback.
