### ISSUE TITLE
[Feature]: About Vue's Code Block

### ISSUE THREAD

**Issue by zhenghui-su** [web-infra-dev/rspress#316]
### 这个功能解决了什么问题？

Can be highlighted in the Vue code block instead of pure black

### 你期望的 API 是什么样子的？

I hope it's not so pure black
![image](https://github.com/web-infra-dev/rspress/assets/104132375/7ef4ef5b-d127-47f6-9cd6-d2df12d518ba)
There should be a highlight like this
![image](https://github.com/web-infra-dev/rspress/assets/104132375/b406daf4-cd09-4a49-a888-e04aeb63462d)

**Comment by Yukiniro** [comment]
Currently, rspress uses prism for syntax highlighting, but prism does not support vue for the time being. Here are the details https://github.com/PrismJS/prism/issues/1665.

However, you can use `` ```html `` instead.

**Comment by Yukiniro** [comment]
Shiki is introduced here #345 .
And shiki seems to support vue syntax highlight https://github.com/shikijs/shiki/blob/main/docs/languages.md

**Comment by zhenghui-su** [comment]
@Yukiniro Thank you for your answer. I understand

**Comment by Timeless0911** [comment]
I think this feature has been completed, reopen it if still have any issues.
