### ISSUE TITLE
[Bug]: Headings not support HTML character entities or escape characers

### ISSUE THREAD

**Issue by recallwei** [web-infra-dev/rspress#320]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 79.34 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0
  npmPackages:
    rspress: ^1.5.0 => 1.5.0
```

### Details

Headings and TOC does not support HTML character entities and escape characters.

What I expect to be:
```
User('sub')
```
---

But got:

<img width="239" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/5f83ab5e-a1be-406d-8639-f06c9e53648e">

---

<img width="253" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/9e2d7d7d-7af3-403d-9978-3f561a728755">

### Reproduce link

https://codesandbox.io/p/sandbox/awesome-sunset-fmx92l?file=%2Fdocs%2Foverview%2Findex.md%3A9%2C1

### Reproduce Steps

````
```md
# 概览

## @User(\'abc\')

\'  
&#39;

## @User(&#39;abc&#39;)
```
````

**Comment by 10Derozan** [comment]
You can unable this [config](https://rspress.dev/api/config/config-build.html#markdownmdxrs) to avoid this error.
I'll fix it at https://github.com/web-infra-dev/mdx-rs/pull/14
