### ISSUE TITLE
[Bug]: globalStyles doesn't work in rspress 1.5.0

### ISSUE THREAD

**Issue by hustcer** [web-infra-dev/rspress#325]
### Version

```sh
System:
    OS: macOS 14.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 288.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.1
  npmPackages:
    rspress: ^1.5.0 => 1.5.0
```

### Details

`globalStyles` doesn't work in `rspress` 1.5.0, However, if downgrade `rspress` to v1.4.1, everything works as expected

### Reproduce link

No link

### Reproduce Steps

```diff
- rspress 1.4.1
+ rspress 1.5.0
```
Nothing else has been changed, except the `rspress` version

**Comment by sanyuan0704** [comment]
How about 1.5.1?

**Comment by sanyuan0704** [comment]
I found it works 
![image](https://github.com/web-infra-dev/rspress/assets/39261479/59c39910-fdfe-4243-8f9d-b84c5f1f1cef)
![image](https://github.com/web-infra-dev/rspress/assets/39261479/0395c121-5b41-4d8f-aa27-5d1ef00ba473)
![image](https://github.com/web-infra-dev/rspress/assets/39261479/474b3142-47a5-4947-9eba-9d905656d1db)

**Comment by hustcer** [comment]
```console
$> pnpm i -D rspress@1.5.1
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @rspress/plugin-medium-zoom@1.5.1

This error happened while installing the dependencies of rspress@1.5.1
 at @rspress/core@1.5.1

The latest release of @rspress/plugin-medium-zoom is "1.5.0".

Other releases are:
  * beta: 1.1.1-beta.0
  * next: 0.0.0-next-20231020055855
  * nightly: 0.0.0-nightly-20231105160159

If you need the full list of all 103 published versions run "$ pnpm view @rspress/plugin-medium-zoom versions".
Progress: resolved 126, reused 91, downloaded 0, added 0
```

**Comment by chenjiahan** [comment]
It was released an hour ago, are you using some third-party npm registry?

![image](https://github.com/web-infra-dev/rspress/assets/7237365/ed598e0f-8685-4f08-8de4-c18f568fc48e)

https://www.npmjs.com/package/@rspress/plugin-medium-zoom?activeTab=readme

**Comment by hustcer** [comment]
Yeah, we installed it from https://npmmirror.com/. I have just synced it a minute ago, and the install finished successfully. However, the globalStyles still doesn't work. rspress.config:
```js
export default defineConfig({
  ...
  globalStyles: path.join(__dirname, 'styles/index.css')
  ...
}
```

**Comment by sanyuan0704** [comment]
You may don't need  add `:root`.

**Comment by sanyuan0704** [comment]
@hustcer

**Comment by hustcer** [comment]
> You may don't need add `:root`.

Thanks, still doesn’t work either, I will create a demo repo later.

**Comment by hustcer** [comment]
Here is a simple demo to reproduce this issue: https://github.com/hustcer/rspress-demo
If the `globalStyle` works the icon of `RSPress API` top nav item should be 18px x 18px

**Comment by sanyuan0704** [comment]
I found the problem. The raw css does not support nested class, so you should rename the `index.css` to `index.scss` and then the style will work.

**Comment by hustcer** [comment]
Ah, I see, thanks
