### ISSUE TITLE
[Bug]: markdown 解析

### ISSUE THREAD

**Issue by impossible98** [web-infra-dev/rspress#342]
### 版本信息

```sh
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Common KVM processor
    Memory: 5.88 GB / 7.76 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  npmPackages:
    rspress: ^1.0.0 => 1.5.0
```

### 问题详情

```
`` ` ``
```

解析会在末尾多出一个空格

![chrome_NuFDPCTvht](https://picdl.sunbangyan.cn/2023/11/09/c72b5abc82e3a400b9773779ceab243e.png)

### 复现链接

none

### 复现步骤

none

**Comment by shenjackyuanjie** [comment]
还有一些相似的 ` ` 空格解析错误问题
反正就在代码块里面随便塞一些前后带空格的就能遇见

**Comment by shulaoda** [comment]
I think this issue has been fixed. @Timeless0911

**Comment by Timeless0911** [comment]
I will close it, feel free to reopen if there still exists this issue.
