### ISSUE TITLE
[Bug]: Sidebar not displayed after switching the language

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#343]
### Version

```sh
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.39 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 16.6
  npmPackages:
    @rspress/shared: ^1.6.0 => 1.6.0 
    rspress: ^1.6.0 => 1.6.0
```

### Details

Sidebar not displayed after switching the language:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/ed38d927-0f51-418f-82b4-fe02678e250f)

### Reproduce link

https://rsbuild.dev/guide/start/

### Reproduce Steps

1. Visit https://rsbuild.dev/guide/start/
2. Switch language to Chinese

**Comment by sanyuan0704** [comment]
The link seems to be incorrect. It should be `/guide/start/index.html` instead of `/guide/start.html`, which has different semantics.

**Comment by chenjiahan** [comment]
Yeah, when I visit https://rsbuild.dev/guide/start/index, it will be redirect to https://rsbuild.dev/guide/start/, then switching language will get an incorrect URL

**Comment by chenjiahan** [comment]
I reopened this issue because it happen again in the Rsbuild document.

Reproduce step:

1. open https://rsbuild.dev/guide/start/
2. switch to Chinese

![image](https://github.com/web-infra-dev/rspress/assets/7237365/378dfed1-11c1-4d77-aeee-7c8da53df9f2)

**Comment by chenjiahan** [comment]
Still have this issue: https://rsbuild.dev/guide/start/index.html
