### ISSUE TITLE
[Feature]: `@rspress/plugin-last-updated`插件文档优化

### ISSUE THREAD

**Issue by hanhan9449** [web-infra-dev/rspress#351]
### 这个功能解决了什么问题？

插件在安装、修改`themeConfig.lastUpdated`为true后即可用。无需手动注册环节。

现使用文档提示1 先注册 2 再mdx中引用，按照文档会报错。
![image](https://github.com/web-infra-dev/rspress/assets/28822945/11e55674-494b-4de2-b582-a11293a530b8)

### 你期望的 API 是什么样子的？

期望将文档上部介绍-提示，移动到使用部分，移除不再可用的使用部分文档。
![image](https://github.com/web-infra-dev/rspress/assets/28822945/dbcd2989-06a4-456a-a6dc-8950d0a66fc2)

**Comment by sanyuan0704** [comment]
默认主题中不用手动加这个插件，文档已经更新
