### ISSUE TITLE
[Bug]: public directory cannot contain *.js files

### ISSUE THREAD

**Issue by haiweilian** [web-infra-dev/rspress#354]
### Version

```sh
@rspress/*,rspress}'

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 43.25 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.123
    Edge: 113.0.1774.35
    Firefox: 110.0
    Safari: 15.6.1
  npmPackages:
    @rspress/plugin-preview: ^1.6.0 => 1.6.0 
    rspress: ^1.6.0 => 1.6.0
```

### Details

正常来说静态资源不是放什么都可以的吗。
我在 public 目录下放了一个独立的演示示例以便我可以一起部署，但它额外的把 `*.js` 解析为一个页面。

![image](https://github.com/web-infra-dev/rspress/assets/34850199/304f8376-659e-4c88-a6fa-36e370390413)

### Reproduce link

https://github.com/haiweilian/taggd-manager/tree/next

### Reproduce Steps

npm install

npm run docs:build

**Comment by sanyuan0704** [comment]
Maybe you should add `public` dir in `route.exclude` config because the js in public dir should not be regarded as a page.

**Comment by haiweilian** [comment]
ok

```
route: {
  exclude: ['public/**'],
},
```

**Comment by sanyuan0704** [comment]
Does it work?

**Comment by haiweilian** [comment]
> @haiweilian Does it work?

Yes
