### ISSUE TITLE
[Bug]: The link in TOC is not correct when using custom anchor id 

### ISSUE THREAD

**Issue by jkzing** [web-infra-dev/rspress#357]
### Version

```sh
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 358.56 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  npmPackages:
    rspress: ^1.0.0 => 1.6.2
```

### Details

The anchor link in TOC is not correct when I use custom anchor id (`{#my-anchor}`) in .mdx file. And it works fine in .md file.

I already created a issue in the mdx-rs project https://github.com/web-infra-dev/mdx-rs/issues/13, I think we also need to track the issue here.

### Reproduce link

https://codesandbox.io/p/sandbox/great-kare-mq5znv?welcome=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloxqbi2800073b6oi2ossrwc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloxqbi2800033b6ophqq4eg6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloxqbi2800053b6o4tmektds%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloxqbi2800063b6o007bo4ga%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloxqbi2800033b6ophqq4eg6%2522%253A%257B%2522id%2522%253A%2522cloxqbi2800033b6ophqq4eg6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdocs%252Fguide%252Findex.mdx%2522%252C%2522id%2522%253A%2522cloxqfed902cl3b6ox74m3u7q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloxqfed902cl3b6ox74m3u7q%2522%257D%252C%2522cloxqbi2800063b6o007bo4ga%2522%253A%257B%2522id%2522%253A%2522cloxqbi2800063b6o007bo4ga%2522%252C%2522activeTabId%2522%253A%2522cloxqdwrf017a3b6o740l6p5a%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522id%2522%253A%2522cloxqdwrf017a3b6o740l6p5a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cloxqbi2800053b6o4tmektds%2522%253A%257B%2522id%2522%253A%2522cloxqbi2800053b6o4tmektds%2522%252C%2522activeTabId%2522%253A%2522cloxqd41600cw3b6o6kbdh7ke%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloxqbi2800043b6op86rd1x8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloxqbie6000heeij1gz33giy%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloxqd41600cw3b6o6kbdh7ke%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Reproduce Steps

1. run `npm run dev`
2. open `docs/guide/index.mdx` file to check the custom anchor and see it's not working in `/guide` page

**Comment by 10Derozan** [comment]
Fix this in https://github.com/web-infra-dev/rspress/pull/413

**Comment by sanyuan0704** [comment]
👏🏻
