### ISSUE TITLE
[Bug]: The Sidebar appears to be missing from some pages

### ISSUE THREAD

**Issue by recallwei** [web-infra-dev/rspress#360]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 1.46 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
  npmPackages:
    rspress: ^1.6.2 => 1.6.2
```

### Details

Weird behaviour.

Pages in /react-native/ missing sidebar.

<img width="1886" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/e9bf57ba-0ba9-47d5-8386-434a8e1a14cd">

Seems that I deleted dir /react/, sidebar display again.

### Reproduce link

https://codesandbox.io/p/sandbox/ancient-currying-722dtk?file=%2Fdocs%2F_meta.json%3A9%2C22

### Reproduce Steps

Check the repro.

Try to delete the /react/ dir.

Observe whether the sidebar is displayed in /react-native/ pages.

**Comment by 10Derozan** [comment]
I found this problem is brought by #324. 
The following logic is hit.
https://github.com/web-infra-dev/rspress/pull/324/files#diff-311a7780dfb8ded8cebb8fd3084c8f38486b703612b34a8484665b1b98a6519dR58-R65
