### ISSUE TITLE
[Bug]: darkMode: false失效

### ISSUE THREAD

**Issue by sylingd** [web-infra-dev/rspress#372]
### 版本信息

```sh
-
```

### 问题详情

HTML中存在该段代码：
![img_v3_0259_e1d7a380-dd8d-410e-84bd-445d6d0ea1ag](https://github.com/web-infra-dev/rspress/assets/5326684/74ebca19-c380-49bc-bb16-072d6623783e)

导致即使配置了themeConfig.darkMode = false，站点仍然会是黑色模式，该选项实际无效。

### 复现链接

-

### 复现步骤

1. 配置themeConfig.darkMode=false
2. 将电脑改为深色模式
3. 打开站点，站点仍然是深色模式

或者反过来也一样

**Comment by sanyuan0704** [comment]
感谢反馈！我们将在 darkMode 设为 false 之后取消注入这些脚本
