### ISSUE TITLE
[Bug]: The docs of config for plugins is not consistent in different language version.

### ISSUE THREAD

**Issue by Yukiniro** [web-infra-dev/rspress#374]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 282.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.117
    Edge: 118.0.2088.76
    Safari: 17.0
  npmPackages:
    rspress: ^1.2.1 => 1.2.1
```

### Details

```shell
If it involves adding and removing a plugin, you need to implement it through addPlugin and removePlugin:
```
The above content is in the Chinese version, but not in the English version

### Reproduce link

https://rspress.dev/plugin/system/plugin-api.html#config

### Reproduce Steps

1. go to https://rspress.dev/plugin/system/plugin-api.html#config
2. go to https://rspress.dev/zh/plugin/system/plugin-api.html#config

**Comment by Yukiniro** [comment]
I guess I should keep the above content and translate it, is that right?

**Comment by sanyuan0704** [comment]
> I guess I should keep the above content and translate it, is that right?

Yeah.
