### ISSUE TITLE
[Feature]: Supports `inject variables` in front matter

### ISSUE THREAD

**Issue by NWYLZW** [web-infra-dev/rspress#376]
### What problem does this feature solve?

Now we are able to set variables in the configuration, but unfortunately, we are unable to utilize them in the front matter of our markdown files.

### What does the proposed API look like?

```markdown
---
hero:
  # or yaml like github actions
  name: {{config.title/meta.title/title}}
  # or ejs
  name: <%= title %>
---
```
This behavior is specific to Vitepress, as it utilizes ejs for prerendering. You can find more information about this behavior in the [Vitepress template](https://github.com/vuejs/vitepress/blob/main/template/index.md?plain=1#L6C9-L6C21).

Now, with the ability to set the `_meta.json`, I this it can be injected into the front matter?

**Comment by NWYLZW** [comment]
Or use other prerendering technology? If this is a functionality that can be done I can implement it for.

**Comment by sanyuan0704** [comment]
I notice the template variable exists in the create cli instead of user project. In rspress, we do the same thing and use ejs to render the template code in create-rspress package.

**Comment by NWYLZW** [comment]
> I notice the template variable exists in the create cli instead of user project. In rspress, we do the same thing and use ejs to render the template code in create-rspress package.

Oh, I understand, it seems that vite does not save this as a runtime, it is just used for generation.
What I originally thought was that I didn’t want to write it once in the config file and again in home, which would be easy to forget when updating.

**Comment by sanyuan0704** [comment]
That will make frontmatter grammer more complex

**Comment by sanyuan0704** [comment]
That will make frontmatter grammer more complex and i recommend using config data to set default values for corresponding fields in home page.

**Comment by NWYLZW** [comment]
Are you referring to allowing users to actively go to the homepage to set relevant information, rather than using variable references or the like?

**Comment by sanyuan0704** [comment]
> Are you referring to allowing users to actively go to the homepage to set relevant information, rather than using variable references or the like?

Yeah

**Comment by NWYLZW** [comment]
Ok, Thanks
