### ISSUE TITLE
[Bug]: Code block automatically add a blank line, and Copy button should not copy the line number

### ISSUE THREAD

**Issue by recallwei** [web-infra-dev/rspress#383]
### Version

```sh
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 154.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    rspress: ^1.7.0 => 1.7.0
```

### Details

Codebase: https://github.com/recallwei/web-dev-handbook/blob/main/docs/linux/certbot.md

After Upgrade to v.1.7.0,

In my .md:
````
```bash
dnf install -y epel-release
dnf install -y certbot python3-certbot-nginx
```
````
But with an extra blank line:
<img width="844" alt="image" src="https://github.com/web-infra-dev/rspress/assets/62941121/74264c5c-4ff0-499a-b8c9-7712751b9d81">

And try to copy the code block, the result below contains line number:
```text
1dnf install -y epel-release
2dnf install -y certbot python3-certbot-nginx
3
```

### Reproduce link

https://web-dev.brucesong.xyz/linux/certbot.html

### Reproduce Steps

Add a code block.

**Comment by sanyuan0704** [comment]
Thanks for feedback. I will fix it right away.

**Comment by sanyuan0704** [comment]
@recallwei v1.7.1 has fixed
