### ISSUE TITLE
[Bug]: 相对路径引用以`.PNG`结尾的图片报错

### ISSUE THREAD

**Issue by hanhan9449** [web-infra-dev/rspress#395]
### 版本信息

```sh
windows 11 23E2
npm 10.1.0
node v20.9.0
但是错误和系统无关，构建的问题
```

### 问题详情

**相对路径**引用以`.PNG`结尾的图片报错，**绝对路径**无此问题。

建议再排查一些别的资源。

![image](https://github.com/web-infra-dev/rspress/assets/28822945/3ab9f138-750d-4e50-b587-39d3b7f3c9d8)

### 复现链接

https://github.com/hanhan9449/rspress-173-demo

### 复现步骤

- npm i
- npm run build
```[tasklist]
### Tasks
```

**Comment by hanhan9449** [comment]
`*.JPG`也有此问题

**Comment by sanyuan0704** [comment]
请使用正确的图片后缀

**Comment by sanyuan0704** [comment]
![image](https://github.com/web-infra-dev/rspress/assets/39261479/0e484ae7-6729-4602-88cf-410bf6fbb420)

**Comment by hanhan9449** [comment]
以 PNG 不是正确的图片后缀吗 QAQ

**Comment by hanhan9449** [comment]
iphone 导出就是.PNG结尾

**Comment by sanyuan0704** [comment]
好的哈，框架内部可能需要适配这种情况

**Comment by chenjiahan** [comment]
Rsbuild 的正则表达式里是有匹配大写情况的：
![image](https://github.com/web-infra-dev/rspress/assets/7237365/9f6f7303-7db2-448a-bdd0-4e911cfb0bb8)

这个问题可能是 Rspack 层面的，我用 webpack 试了下没问题
