### ISSUE TITLE
[Feature]: 能将内置组件暴露出来，供mdx使用吗？例如Code，Pre等

### ISSUE THREAD

**Issue by hanhan9449** [web-infra-dev/rspress#402]
### 这个功能解决了什么问题？

在mdx能使用与md相同的组件，有一致的样式。

### 你期望的 API 是什么样子的？

在mdx能使用与md相同的组件，有一致的样式。

目前`@rspress/theme-default`暴露了`getCustomMDXCompnent`，能获取到Code，Pre等组件，但local开发时使用会报错。

![image](https://github.com/web-infra-dev/rspress/assets/28822945/47a53faa-b357-405c-aba9-588cdec92aa2)

**Comment by byteHulk** [comment]
`import { getCustomMDXComponent } from "@rspress/theme-default"

export const { h1: H1 ,code:Code} = getCustomMDXComponent();
export const name = 'world'

# Hello {name.toUpperCase()}

<H1>h1</H1>
<Code language="js">export const H1 = (props) => {};</Code>

`

我这样试用了一下 好像没啥问题

**Comment by 10Derozan** [comment]
能否提供复现的方式以重启此 issue ？
