### ISSUE TITLE
[Feature]: Support write HTML in markdown file

### ISSUE THREAD

**Issue by sumy7** [web-infra-dev/rspress#407]
### 这个功能解决了什么问题？

Hello, I've noticed an issue where HTML content within Markdown files, specifically iframes from third-party applications like YouTube videos and CodeSandbox, are not rendering.
Is there any way to embed HTML within Markdown files? 

### 你期望的 API 是什么样子的？

simple usage:

# balabala

then a html iframe show a youtube video.

<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by byteHulk** [comment]
Hello rspress supports MDX, you can just create a `.mdx` file and write JSX directly.
```
# Hello World!

<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
```
Reference.
https://rspress.dev/guide/basic/use-mdx.html
https://mdxjs.com/docs/what-is-mdx/

**Comment by sumy7** [comment]
hi @byteHulk , thank you for your reply.
My blog posts have been migrated from Hexo and are all in Markdown format. Given the large number of articles, converting them to MDX could indeed pose compatibility issues.
I've found a temporary solution to this issue from [https://github.com/orgs/mdx-js/discussions/2231](https://github.com/orgs/mdx-js/discussions/2231)

it use `rehypeRaw` to process html inner *.md file
in `package.json`, add dependency
```json
{
  "peerDependencies": {
    "parse5": "^6.0.1"
  },
  "devDependencies": {
    "rehype-raw": "^6.1.1",
  }
}
```
then in `rspress.config.ts`
```typescript
import rehypeRaw from 'rehype-raw'

export default {
// ...
  markdown: {
    mdxRs: false,
    rehypePlugins: [
      [
        rehypeRaw,
        {
          passThrough: [
            'mdxFlowExpression',
            'mdxJsxFlowElement',
            'mdxJsxTextElement',
            'mdxTextExpression',
            'mdxjsEsm',
          ],
        },
      ],
    ]
  }
//...
}
```

 I've tried it and it works effectively. Thank you once again for your reply.
