### ISSUE TITLE
[Feature]: Auto-Translate Integration

### ISSUE THREAD

**Issue by EmNudge** [web-infra-dev/rspress#409]
### What problem does this feature solve?

As LLMs (such as ChatGPT) become better at translation, many teams are using them for better i18n of docs. While this has yet to be a perfect replacement for hand-written docs, it's a way to ensure they are up-to-date in a language you don't natively speak.

The downside is that this is a manual process that can often result in grammatical mistakes or overly verbose language with terms only sensible in a certain cultural context.

As LLMs improve, a lot of these problems get better, but this manual process still requires specific git updates with a very opaque system done by engineers often less proficient in the target language.

### What does the proposed API look like?

This can be implemented with external plugins or right into Rspress. A plugin might give more flexibility on how the LLM text is retrieved (via OpenAI or one of many other services).

This feature proposes a button next to content with the option to "translate to X" which will show an inline translation aside the original content. This is not a replacement for full i18n, but can be a great way to supplement areas where the current translation systems are lacking.

People may want the option to make requests at runtime or pre-compiled. If we pre-compile translation assets into `dist/i18n/[lang]/chunk{1, 2, 3, etc}` then we may be able to make both systems work without too much change in the underlying functionality. Either the assets already exist and are requested or the plugin makes a runtime request to an API and injects the content.

**Comment by sanyuan0704** [comment]
> This requirement feels applicable, is it possible to make a plug-in form, provide pre-compiled, I have an open source model, can start doing it first, and then replace it with a more effective model later?

Yeah, i think we can develop a plugin to implement it

**Comment by EmNudge** [comment]
Can this issue be closed now with the creation of https://github.com/byteHulk/rspress-plugin-translate and [associated docs](https://rspress.dev/plugin/community-plugins/translate)?
