### ISSUE TITLE
[Bug]: 代码块高亮失效

### ISSUE THREAD

**Issue by shenjackyuanjie** [web-infra-dev/rspress#419]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 57.98 GB / 95.91 GB
  Browsers:
    Edge: Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    rspress: ^1.7.5 => 1.7.5
```

### 问题详情

如题，代码高亮失效
实际案例：
https://f2ac97ec.nuitka.pages.dev/main/lib-not-dr/readme.html#nuitka-compiler-helper

下方的几个代码块无论有无 title 代码块高亮均失效

### 复现链接

https://f2ac97ec.nuitka.pages.dev/main/lib-not-dr/readme.html#nuitka-compiler-helper

### 复现步骤

https://f2ac97ec.nuitka.pages.dev/main/lib-not-dr/readme.html#nuitka-compiler-helper
源码：
https://github.com/shenjackyuanjie/nuitka-shenjack/commit/5a47c86ce89c68b0bc1308b1e6bb79ef2db79215
使用 CF pages 部署
无框架

```[tasklist]
### 相关 issue
- [ ] https://github.com/web-infra-dev/rspress/issues/364
```

**Comment by chenjiahan** [comment]
更好的解决方案是自动分析 markdown 里使用的代码块语言，并生成 highlight 配置。

mdx-rs 可以分析并提供对应的元数据，供 rspress 消费。

**Comment by shenjackyuanjie** [comment]
感谢！

**Comment by sanyuan0704** [comment]
#133
