### ISSUE TITLE
[Bug]: windows系统不适配，打包速度慢且内存溢出

### ISSUE THREAD

**Issue by zhangnongqiang** [web-infra-dev/rspress#431]
### 版本信息

```sh
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 534.84 MB / 15.70 GB
  Browsers:
    Edge: Chromium (119.0.2151.93)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspress/mdx-rs-darwin-arm64: ^0.4.2 => 0.4.2
    rspress: ^1.0.0 => 1.7.5
```

### 问题详情

运行npm run dev时启动速度慢，且容易内存溢出，完全无法使用。
![59a38a1d2d6169fda0454d50c0c8e89](https://github.com/web-infra-dev/rspress/assets/141222108/b6b221d3-2503-4a98-8cb2-d0c3c0c39a6a)

### 复现链接

无

### 复现步骤

windows电脑运行指令：运行npm run dev

**Comment by zhangnongqiang** [comment]
> 这个问题没有复现仓库的话不太好排查，能否提供一个复现呢

找到原因了，主要这个配置导致的
```
output: {
      copy: [{ from: './docs/public', to: '' }],
    }
```
windows电脑启动服务以后文件是锁死的，public文件过大，这时候进行文件拷贝操作都会卡死，改成动态引用就好了，给大家避坑，建议作者把流程改成先拷文件再启动服务试试

**Comment by chenjiahan** [comment]
get，所以 public 里面是有一些巨大的文件吗 😂 这个 copy 是 Rspack 内部实现的，所以会在 dev server 启动后的编译过程中触发

**Comment by sanyuan0704** [comment]
> > 这个问题没有复现仓库的话不太好排查，能否提供一个复现呢
> 
> 找到原因了，主要这个配置导致的
> 
> ```
> output: {
>       copy: [{ from: './docs/public', to: '' }],
>     }
> ```
> 
> windows电脑启动服务以后文件是锁死的，public文件过大，这时候进行文件拷贝操作都会卡死，改成动态引用就好了，给大家避坑，建议作者把流程改成先拷文件再启动服务试试

这个 copy 操作的目的是什么?

**Comment by zhangnongqiang** [comment]
> > > 这个问题没有复现仓库的话不太好排查，能否提供一个复现呢
> > 
> > 
> > 找到原因了，主要这个配置导致的
> > ```
> > output: {
> >       copy: [{ from: './docs/public', to: '' }],
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > windows电脑启动服务以后文件是锁死的，public文件过大，这时候进行文件拷贝操作都会卡死，改成动态引用就好了，给大家避坑，建议作者把流程改成先拷文件再启动服务试试
> 
> 这个 copy 操作的目的是什么? 在开发阶段会在你的这个 public 目录下启动一个静态资源服务，可以通过 dev server 直接访问到资源

我的理解：项目是ssr，运行dev时也会先打包到doc_build再启动一个本地服务，本地服务使用的是doc_build里的静态资源，所以需要copy出来，我把copy这一步注释掉以后，放到public里的图片就都看不到了

**Comment by zhangnongqiang** [comment]
> get，所以 public 里面是有一些巨大的文件吗 😂 这个 copy 是 Rspack 内部实现的，所以会在 dev server 启动后的编译过程中触发

文件不大，但很多,Windows文件系统本身缺陷导致文件占用时修改里面的内容会特别慢

**Comment by sanyuan0704** [comment]
> 资源

1. 本地开发不是 SSR
2. dev server 会对 docs/public 目录下的资源启用静态服务，比如对于`docs/public/logo.png`，那么你直接通过 /logo.png 路径访问图片是可以的

**Comment by zhangnongqiang** [comment]
> > 资源
> 
> 1. 本地开发不是 SSR
> 2. dev server 会对 docs/public 目录下的资源启用静态服务，比如对于`docs/public/logo.png`，那么你直接通过 /logo.png 路径访问图片是可以的

刚刚试了下，删除配置以后确实也可以 /logo.png 路径访问图片，那这个bug关了吧
