### ISSUE TITLE
[Feature]: rspress 现在支持 mermaid 了么

### ISSUE THREAD

**Issue by godkun** [web-infra-dev/rspress#449]
### What problem does this feature solve?

在 md 文件中，支持 mermaid 语法

### What does the proposed API look like?

在 md 文件中，支持 mermaid 语法

**Comment by sanyuan0704** [comment]
You can integrate `@theguild/remark-mermaid` in `markdown.remarkPlugins` of rspress config file. By the way, the plugin is implemented by js, so you should also set `markdown.mdxRs` as `false` to enable the javascript version markdown compiler.

**Comment by godkun** [comment]
好滴，谢谢回答

**Comment by yayxs** [comment]
@godkun 
You can see this example
https://github.com/yayxs/computer-organization-learn/blob/main/rspress.config.ts

**Comment by chenjiahan** [comment]
There is a community plugin for mermaid now:

https://github.com/linbudu599/rspress-plugins/tree/main/packages/rspress-plugin-mermaid
