### ISSUE TITLE
[Feature]: support tailwindcss plugin

### ISSUE THREAD

**Issue by sanyuan0704** [web-infra-dev/rspress#452]
### What problem does this feature solve?

Support tailwindcss by a rspress plugin, then the user can apply tailwindcss styles in the rspress site.

### What does the proposed API look like?

```ts
// rspress.config.ts
import { tailwindRspressPlugin } from '@rspress/plugin-tailwindcss';

export default {
  plugins: [tailwindRspressPlugin()]
}
```

**Comment by chenjiahan** [comment]
Rsbuild will automatically read `postcss.config.js`, users just need to follow the Tailwind CSS official guide: https://tailwindcss.com/docs/installation/using-postcss

**Comment by sanyuan0704** [comment]
ok, then i think we just need add a guide document for rspress to tell user how to integrate tailwindcss.

**Comment by chenjiahan** [comment]
yeah that would be nice
