### ISSUE TITLE
[Bug]: Discord link error

### ISSUE THREAD

**Issue by RSS1102** [web-infra-dev/rspress#456]
### 版本信息

```sh
system: win11
Chrome 已是最新版本
版本 120.0.6099.110（正式版本） （64 位）
```

### 问题详情

![image](https://github.com/web-infra-dev/rspress/assets/81673017/d8793917-49c1-4f04-8c89-e05ac7070aa4)

### 复现链接

https://discord.com/channels/977448667919286283/1161653869080756245

### 复现步骤

1. 点击README上的discord链接跳转无反应。

**Comment by chenjiahan** [comment]
Can you try this new link? https://discord.gg/csSX8TBy

**Comment by RSS1102** [comment]
> Can you try this new link? https://discord.gg/csSX8TBy

good
