### ISSUE TITLE
[Bug]: globby@14.0.0 require node >= 18 

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspress#461]
### Version

```sh
None.
```

### Details

@rspress/shared depends on globby@14.0.0 and not use it. It's require node >= 18.
so can i remove it ? or downgrade ?

### Reproduce link

None.

### Reproduce Steps

None.

**Comment by KyrieLii** [comment]
Rel: https://github.com/web-infra-dev/rspress/pull/437/files#diff-3752b1e4e3e2032593e21e9268ec0379680a59e4e7b8517d0d5492a71530d3e8

**Comment by sanyuan0704** [comment]
Yeah, we can remove it. I will add a pr later.

**Comment by KyrieLii** [comment]
> Yeah, we can remove it. I will add a pr later.

I can do it,  i found it because modern.js module generator testing fail in node 16 😂

**Comment by sanyuan0704** [comment]
> > Yeah, we can remove it. I will add a pr later.
> 
> I can do it, i found it because modern.js module generator testing fail in node 16 😂

ok
