### ISSUE TITLE
[Bug]: npm dev 预览时 内容更改无法自动刷新网页

### ISSUE THREAD

**Issue by shenjackyuanjie** [web-infra-dev/rspress#464]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 48.94 GB / 95.91 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    rspress: ^1.8.3 => 1.8.3
```

### 问题详情

创建一个预览项目
pnpm/npm run dev
打开一个浏览器预览
任意修改 index.md 内容
观察浏览器网页
1.7.5: 会自动刷新网页，更新内容
1.8.3: 无反应，需要自己刷新网页

### 复现链接

任意项目

### 复现步骤

创建一个预览项目
pnpm/npm run dev
打开一个浏览器预览
任意修改 index.md 内容
观察浏览器网页
1.7.5: 会自动刷新网页，更新内容
1.8.3: 无反应，需要自己刷新网页

**Comment by shenjackyuanjie** [comment]
我附加一些说明

在删除 pnpm lock 重新 pnpm install之后，这个功能回来了（离谱

**Comment by shenjackyuanjie** [comment]
我再补充一些
添加一个文件之后
这个功能失效了
![image](https://github.com/web-infra-dev/rspress/assets/54507071/7204cff3-3ca8-4384-b1dd-691961151aba)

**Comment by shenjackyuanjie** [comment]
继续补充说明
![image](https://github.com/web-infra-dev/rspress/assets/54507071/acc8854b-3dde-4def-ac71-8be8f2a97d04)

失效效果是在新建的这个文件中失效
其他文件可以正常刷新

**Comment by jinchaofs** [comment]
我尝试在Rsbuild中对Hmr客户端添加断开重连功能，看能不能通过吧

**Comment by shenjackyuanjie** [comment]
> 我尝试在Rsbuild中对Hmr客户端添加断开重连功能，看能不能通过吧

好欸，谢谢~

**Comment by sanyuan0704** [comment]
目前无法复现

**Comment by xc2** [comment]
@a145789 1.21.1 的话，用 resolutions 或 override 把 `@rspack/core` 改为 `0.5.4-canary-bf8f473-20240220125622` 版本试试

**Comment by shenjackyuanjie** [comment]
@a145789 
稍微问一下，现在还有这个问题吗？
没有的话我就 close 了

**Comment by xc2** [comment]
> @a145789 稍微问一下，现在还有这个问题吗？ 没有的话我就 close 了

现在还有这个问题。

@Boshen  rspress 这里有些这样的 request - 原始 request 是绝对路径，但是是 posix 斜杠。也会触发之前那个问题

```js
{
  changedFiles: Set(0) {},
  removedFiles: Set(8) {
    'C:/Users/imkf/Developer/rspress-site/node_modules/@rspress/plugin-container-syntax/container.css',
    'C:/Users/imkf/Developer/rspress-site/node_modules/@rspress/plugin-container-syntax\\package.json',
    'C:/Users/imkf/Developer/rspress-site/node_modules/@rspress/plugin-medium-zoom/src/components/MediumZoom.tsx',
    'C:/Users/imkf/Developer/rspress-site/node_modules/@rspress/plugin-medium-zoom/src/components\\MediumZoom.css',
    'C:/Users/imkf/Developer/rspress-site/node_modules/@rspress/plugin-medium-zoom\\package.json',
    'C:/Users/imkf/Developer/rspress-site/docs/index.md',
    'C:/Users/imkf/Developer/rspress-site/docs/hello.md',
    'C:/Users/imkf/Developer/rspress-site/docs/guide/index.md'
  }
}
```

rspress 的原始代码（virtual）

```js
import React from 'react';
import { lazyWithPreload } from "react-lazy-with-preload";
const Route0 = lazyWithPreload(() => import('C:/Users/imkf/Developer/rspress-site/docs/guide/index.md'))
const Route1 = lazyWithPreload(() => import('C:/Users/imkf/Developer/rspress-site/docs/hello.md'))
const Route2 = lazyWithPreload(() => import('C:/Users/imkf/Developer/rspress-site/docs/index.md'))
export const routes = [
{ path: '/guide/', element: React.createElement(Route0), filePath: 'guide/index.md', preload: async () => {
        await Route0.preload();
        return import("C:/Users/imkf/Developer/rspress-site/docs/guide/index.md");
      }, lang: '', version: '' },
{ path: '/hello', element: React.createElement(Route1), filePath: 'hello.md', preload: async () => {
        await Route1.preload();
        return import("C:/Users/imkf/Developer/rspress-site/docs/hello.md");
      }, lang: '', version: '' },
{ path: '/', element: React.createElement(Route2), filePath: 'index.md', preload: async () => {
        await Route2.preload();
        return import("C:/Users/imkf/Developer/rspress-site/docs/index.md");
      }, lang: '', version: '' }
];

```

**Comment by Boshen** [comment]
> import('C:/Users/imkf/Developer/rspress-site/docs/guide/index.md'))

这个带着 `/` 的 windows path 是哪里来的？我好不容易搞明白了 windows 下面都是 `\` 的情况 😓 

我需要先区分下传进来的数据有问题还是 resolver 内部实现有问题，感觉还是需要一个 minimal reproducible case。

**Comment by shenjackyuanjie** [comment]
神奇

**Comment by xc2** [comment]
> > import('C:/Users/imkf/Developer/rspress-site/docs/guide/index.md'))
> 
> 这个带着 `/` 的 windows path 是哪里来的？我好不容易搞明白了 windows 下面都是 `\` 的情况 😓
> 
> 我需要先区分下传进来的数据有问题还是 resolver 内部实现有问题，感觉还是需要一个 minimal reproducible case。

是 rspress 特意转出来的，我觉得 rspress 应该避免这样的 request。

https://github.com/web-infra-dev/rspress/blob/522bde99aeba6df11ab6f191355711b1d43313c5/packages/core/src/node/route/RouteService.ts?plain=1#L254-L274

https://github.com/web-infra-dev/rspress/blob/522bde99aeba6df11ab6f191355711b1d43313c5/packages/core/src/node/route/RouteService.ts?plain=1#L313-L320

https://github.com/web-infra-dev/rspress/blob/522bde99aeba6df11ab6f191355711b1d43313c5/packages/core/src/node/utils/normalizePath.ts?plain=1#L11


同时报给 oxc 是因为我试了下 webpack 和 node 的 require 都支持这样的绝对路径 request。

**Comment by xc2** [comment]
![image](https://github.com/web-infra-dev/rspress/assets/18117084/c21cbf8f-168b-472f-827e-3fd172a9d983)

**Comment by Boshen** [comment]
🤔 在 windows 下 path 会用 `\` 拼接。我感觉还是按照系统设定，传对应的分隔符比较合适。
