### ISSUE TITLE
[Bug]: 特殊文件名会导致 internal error

### ISSUE THREAD

**Issue by shenjackyuanjie** [web-infra-dev/rspress#465]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 48.94 GB / 95.91 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    rspress: ^1.8.3 => 1.8.3
```

### 问题详情

![image](https://github.com/web-infra-dev/rspress/assets/54507071/fbd24616-f08f-4906-b479-04141405d7d4)

![image](https://github.com/web-infra-dev/rspress/assets/54507071/7f71bd5c-04b0-4daa-8c31-196e03dd5996)

原文件名: `rua!.md`

### 复现链接

任意带有!的文件名

### 复现步骤

创建一个带有!的文件名
（别的特殊字符不确定了

**Comment by sanyuan0704** [comment]
! 字符和 rspack 里面的内联 loader 语法冲突，尽量避免使用哈 https://www.rspack.dev/zh/api/loader-api.html#%E5%86%85%E8%81%94-loaderinline-loaders
