### ISSUE TITLE
[Bug]: 自定义侧边栏目录显示某篇文档后，点击该文档无法收起指定目录

### ISSUE THREAD

**Issue by shenjackyuanjie** [web-infra-dev/rspress#466]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 48.94 GB / 95.91 GB
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    rspress: ^1.8.3 => 1.8.3
```

### 问题详情

这是一个显示文档的目录
点击之后会自动展开
![image](https://github.com/web-infra-dev/rspress/assets/54507071/d461453e-e724-400e-845d-dc87e3cc21b7)
但是再次点击之后无法自动收起所在目录

![image](https://github.com/web-infra-dev/rspress/assets/54507071/f940b8df-c91f-4f6d-8191-42cff1e6f700)
但是如果手动点击右侧目录栏，可以收回当前目录，并且不影响显示的目录

![image](https://github.com/web-infra-dev/rspress/assets/54507071/730ca0cd-a105-4998-a502-51d1c9d1f6d7)
![image](https://github.com/web-infra-dev/rspress/assets/54507071/a16e6d12-4094-482d-9297-fd8f77d6b8be)

对于 普通目录 来说
点击可以展开，再次点击可以收回

那么既然普通目录可以收回，显示文档的无法自动收回，但可以手动收回，这是一个没有在文档里提到的 特性/表现不一致的bug
https://rspress.dev/zh/guide/basic/auto-nav-sidebar.html#object

### 复现链接

任意项目（真的懒得做了）

### 复现步骤

请看问题详情

**Comment by sanyuan0704** [comment]
这是一个有意设计的 feature 哈。原因是点击「显示文档的目录」的子文档，然后再点击这个目录，预期并不应该是收起这个目录

**Comment by shenjackyuanjie** [comment]
> 这是一个有意设计的 feature 哈。原因是点击「显示文档的目录」的子层次的文档，然后再点击这个目录，预期并不应该是收起这个目录，而仅仅是跳到这个目录对应的文档

（那有没有可能加一个选项，让他支持点击收回呢？
那就在文档里加一下吧（
没看到文档里有提到这个feature
