### ISSUE TITLE
[Feature]: Title fallback

### ISSUE THREAD

**Issue by allen0234** [web-infra-dev/rspress#484]
### What problem does this feature solve?

自动生成侧边栏的时候，如果markdown文档未设置H1标题，那么在侧边栏里显示的文档链接名称是空白的

### What does the proposed API look like?

自动检测frontmatter里的title设置、文档H1标题等，自动选择frontmatter title、H1标题、文件名其中之一作为链接名称

**Comment by sanyuan0704** [comment]
Nice feature! I think it's necessary to give the fallback title when the h1 title is not set.
