### ISSUE TITLE
[Bug]: 文档中示例地址，打开是黄色网站

### ISSUE THREAD

**Issue by leylatop** [web-infra-dev/rspress#499]
### 版本信息

```sh
无
```

### 问题详情

https://github.com/web-infra-dev/rspress/blob/e97bbc6ebabaeb3f52ece1bee6f773769dc1639c/packages/document/docs/zh/guide/default-theme/navbar.mdx#L104-L107

Personal的http://xxx.com/ 打开会跳转到黄色网站

### 复现链接

无

### 复现步骤

1. 打开🪜
2. 打开浏览器，输入：http://xxx.com/
3. 回车

**Comment by chenjiahan** [comment]
Thanks for the correction, we will fix it as soon as possible

**Comment by sanyuan0704** [comment]
We have fixed it
