### ISSUE TITLE
[Bug]: Markdown解析shell代码块，文件名会被代码块中的第一行注释替换

### ISSUE THREAD

**Issue by Jingyitao** [web-infra-dev/rspress#500]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.02 GB / 15.86 GB
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### 问题详情

我在docs目录下创建 测试.md 根据文档说明，侧边栏应该是 测试，但是当我在文档中输入 shell 格式的代码块并在代码块中添加注释，重启项目后，该文件的文件名会被shell代码块的第一个注释替换。
![image](https://github.com/web-infra-dev/rspress/assets/76676473/d7539b0a-46c4-4af6-82fb-32d141793f84)
![image](https://github.com/web-infra-dev/rspress/assets/76676473/12eafe43-6549-47f9-9d67-718258602508)

### 复现链接

none

### 复现步骤

docs 下创建 测试.md
在该Markdown中输入shell代码块
```shell
#啦啦啦
nginx -s stop
```
重启项目 
文件名会被替换为 啦啦啦

**Comment by sanyuan0704** [comment]
这个边界 case 我们来修复一下哈，你可以在文档里面加个 h1 标题

**Comment by shulaoda** [comment]
This issue has been fixed. @Timeless0911
