### ISSUE TITLE
[Feature]: Support code group

### ISSUE THREAD

**Issue by SnowingFox** [web-infra-dev/rspress#53]
### What problem does this feature solve?

we can get some inspirations from https://vitepress.dev/guide/markdown#code-groups

input these code
![image](https://github.com/web-infra-dev/rspress/assets/26035718/e06f9984-9f40-418e-9fe2-726f769a5d4d)

generated to this

![image](https://github.com/web-infra-dev/rspress/assets/26035718/a6d47c6e-1f88-469d-8d7b-4671267adfcf)

### What does the proposed API look like?

just provide a new plugin to transform this syntax

**Comment by SnowingFox** [comment]
Is pr welcome to provide a new plugin package?

**Comment by sanyuan0704** [comment]
Is this syntax neccessary? Rspress has provided Tabs component https://rspress.dev/api/client-api/api-components.html#tabtabs which vitepress doesn't provide.

**Comment by SnowingFox** [comment]
> Is this syntax neccessary? Rspress has provided Tabs component https://rspress.dev/api/client-api/api-components.html#tabtabs which vitepress doesn't provide.

I was carelessness.
