### ISSUE TITLE
[Feature]: Support component demo preview for other framework, such as SolidJS

### ISSUE THREAD

**Issue by sanyuan0704** [web-infra-dev/rspress#542]
### What problem does this feature solve?

Now `@rspress/plugin-preview`/`@rspress/plugin-playground` only support react component demo preview. But in fact, we can render the demo code seperately and use renderer of different framework to preview the component code block.

### What does the proposed API look like?

````
```tsx framework=solid
export default function App() {
  return <h1>title</h1>
}
```
````

**Comment by 10Derozan** [comment]
Support in https://github.com/web-infra-dev/rspress/pull/578
