### ISSUE TITLE
[Bug]: unexpected escape characters `\` appear in title

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspress#552]
### Version

```sh
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 885.23 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 15.6.1
  npmPackages:
    rspress: ^1.9.3 => 1.9.3
```

### Details

when title content include `'` or `"`, rspress will output as `\'` or `\"`

source code:
```
### Division in Less file doesn't work?
```
expect display:

```
Division in Less file doesn't work?
```

actual display: 
![20240116-174005](https://github.com/web-infra-dev/rspress/assets/22373761/f95a9364-7325-4cd2-bdb5-6d19c1aad15e)

### Reproduce link

none

### Reproduce Steps

none

**Comment by shulaoda** [comment]
I think this issue has been resolved and should be closed. @Timeless0911
