### ISSUE TITLE
[Bug]: Importing named members with aliases causes an error from playground

### ISSUE THREAD

**Issue by haydnhkim** [web-infra-dev/rspress#584]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.16 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 121.0.2277.83
    Safari: 17.2.1
    Safari Technology Preview: 17.4
  npmPackages:
    @rspress/plugin-playground: ^1.11.1 => 1.11.1
    rspress: ^1.11.1 => 1.11.1
```

### Details

An error occurs when using import with named members with aliases in playground.

```js
import { PackageManagerTabs } from 'rspress/theme';
```

work’s find.
but, if you use `as`, you’ll get an error.

```jsx
import { PackageManagerTabs as Tabs } from 'rspress/theme';

const App = () => {
  return <Tabs command="test" />;
};

export default App;
```

error:
> Cannot read properties of undefined (reading 'map')

When importing a component from another package, the following error occurs.

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### Reproduce link

https://codesandbox.io/p/devbox/romantic-ramanujan-pnhw99

### Reproduce Steps

1. Go Reproduce link
2. Move hello world page
3. file: docs/hello.md

**Comment by sanyuan0704** [comment]
I have fixed it in #587
