### ISSUE TITLE
[Bug]: MDX containing React or Mermaid diagrams not working with mdxRS

### ISSUE THREAD

**Issue by RussellCanfield** [web-infra-dev/rspress#594]
### 版本信息

```sh
System: n/a
Browser: n/a
Packages:
"rspress": "1.11.1"
"@theguild/remark-mermaid": "0.0.6"
```

### 问题详情

MDX pages containing React, or MDX pages containing a simple mermaid markdown section are not rendering. Inspecting the console logs an error for either page in those scenarios.

Setting "mdxRS" to false, resolves the issue.

### 复现链接

N/A

### 复现步骤

Add these packages:
"rspress": "1.11.1"
"@theguild/remark-mermaid": "0.0.6"

Create index.mdx page, linking to "test.mdx"

in test.mdx:

Here is a mermaid diagram:

```mermaid
sequenceDiagram
    Alice ->> Bob: Hello Bob, how are you?
    Bob-->>John: How about you John?
    Bob--x Alice: I am good thanks!
    Bob-x John: I am good thanks!
    Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

    Bob-->Alice: Checking with John...
    Alice->John: Yes... John, how are you?
```

**Comment by sanyuan0704** [comment]
https://rspress.dev/guide/advanced/extend-build.html#mdx-compilation 
![image](https://github.com/web-infra-dev/rspress/assets/39261479/66011ec4-9f2e-49b2-8cd5-baab0582f02c)
