### ISSUE TITLE
[Bug]: Search Index not loading from Asset Prefix path

### ISSUE THREAD

**Issue by RussellCanfield** [web-infra-dev/rspress#60]
### Version

```sh
System: macOS 13.5.1
Browser: Chrome 113
RSPress 0.0.9
```

### Details

My doc site requires an assetPrefix since its hosted on a CDN in a sub directory. After setting the rspress.config -> builderConfig:output:assetPrefix, the build output does not concatenate the __ASSET_PREFIX__, it only shows '/static/'

After analyzing the source code here in github, it looks to be correct. However the compiled bundle does not show the assetPrefix. all other assets such as css, js, etc. respect the assetPrefix that I have defined they work just fine. It seems related to how the LocalProvider resolves "__ASSET_PREFIX__".

Again, everything works with my site but the search feature.

The easiest way to test is to set the output:assetPrefix, run a build and analyze the output file for "search_index" and you'll fine that there is no additional concat statement for the prefix.

### Reproduce link

https://www.google.com/

### Reproduce Steps

Sorry for no reproduce link, its hard to demonstrate this as a bad prefix url will prevent the site from rendering.

1. Create a simple rspress project using rspress 0.0.8 or 0.0.9
2. In the rspress.config.ts, set builderConfig -> output -> assetPrefix to a value such as "https://www.google.com"
3. Run npx rspress build
4. Go the build output directory, then static, then js, then the vendors~node_modules_modern-js*
5. Search for "/static/"
6. Notice there is no asset prefix present

**Comment by sanyuan0704** [comment]
Yeah, i reproduced the problem locally. I will fix it soon.

**Comment by liuwenzhuang** [comment]
Is is better to use  `__webpack_public_path__` for search index url? Consider  `assetPrefix` is a placeholder that will be replaced runtime, the search index url will be failed.

**Comment by SoonIter** [comment]
> Is is better to use `__webpack_public_path__` for search index url? Consider `assetPrefix` is a placeholder that will be replaced runtime, the search index url will be failed.

Could you please consider opening a [new issue](https://github.com/web-infra-dev/rspress/issues/new/choose) and describe the problem you are experiencing in more detail?

**Comment by liuwenzhuang** [comment]
> > Is is better to use `__webpack_public_path__` for search index url? Consider `assetPrefix` is a placeholder that will be replaced runtime, the search index url will be failed.
> 
> Could you please consider opening a [new issue](https://github.com/web-infra-dev/rspress/issues/new/choose) and describe the problem you are experiencing in more detail?

I submit a feature request: https://github.com/web-infra-dev/rspress/issues/1344. Thanks for your reply.
