### ISSUE TITLE
[Bug]: success icon is not correct

### ISSUE THREAD

**Issue by 10Derozan** [web-infra-dev/rspress#601]
### Version

```sh
the main branch
```

### Details

![image](https://github.com/web-infra-dev/rspress/assets/50694858/55df55b2-b64e-4c89-8524-cb366bf4185f)
Maybe We need change a svg?

### Reproduce link

empty

### Reproduce Steps

1. cd e2e/fixtures/plugin
2. pnpm run dev
3. click the copy button in code block

**Comment by sumy7** [comment]
this problem has been fixed by https://github.com/web-infra-dev/modern.js/pull/5322
this issue will be resolved once update the module-tools dependency to the next version

**Comment by 10Derozan** [comment]
> this problem has been fixed by [web-infra-dev/modern.js#5322](https://github.com/web-infra-dev/modern.js/pull/5322) this issue will be resolved once update the module-tools dependency to the next version

ok,thanks your reply.
