### ISSUE TITLE
Website 404 page not working on netlify hosting!

### ISSUE THREAD

**Issue by ArnavK-09** [web-infra-dev/rspress#621]
### Version

```sh
System:
  OS: Windows 10 10.0.19045
  CPU: (4) ia32 AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx
  Memory: 649.02 MB / 3.40 GB
Browsers:
  Edge: Chromium (121.0.2277.106)
  Internet Explorer: 11.0.19041.3636
```

### Details

![Screenshot_2024-02-10-12-14-25-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/web-infra-dev/rspress/assets/69188140/3091dfeb-0256-41a3-8e3f-71d8a5cc09c6)

### Reproduce link

https://rspress.dev/404

### Reproduce Steps

# any non existent page

**Comment by sanyuan0704** [comment]
I think the solution includes two point:
- generate 404.html in ssg phase https://github.com/web-infra-dev/rspress/blob/main/packages/core/src/node/build.ts#L134
- add redirect rule for the unmatched route in netfily config file https://answers.netlify.com/t/new-feature-browse-files-in-your-deploy-with-the-deploy-file-browser/105196

Do you have any idea?

**Comment by ArnavK-09** [comment]
> I think the solution includes two point:
> 
> * generate 404.html in ssg phase https://github.com/web-infra-dev/rspress/blob/main/packages/core/src/node/build.ts#L134
> * add redirect rule for the unmatched route in netfily config file https://answers.netlify.com/t/new-feature-browse-files-in-your-deploy-with-the-deploy-file-browser/105196
> 
> Do you have any idea?

something similar to astro adapters? for rspress for different hosts

https://github.com/withastro/adapters/blob/main/packages/netlify/src/index.ts#L88
https://docs.astro.build/en/guides/integrations-guide/netlify/

**Comment by ArnavK-09** [comment]
i guess _redirects r netlify config is missing in build 

![image](https://github.com/web-infra-dev/rspress/assets/69188140/73c612c7-bd6d-48ec-95fe-f5d606395784)
https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling

**Comment by ArnavK-09** [comment]
@sanyuan0704 
## can you tell me where 404.html is located??? so that i can fix err for netlify

![image](https://github.com/web-infra-dev/rspress/assets/69188140/70953a39-b2a9-4309-8f07-a5c411d5e0bf)

**Comment by ArnavK-09** [comment]
# #623
