### ISSUE TITLE
[Feature]: Update logo format for documentation

### ISSUE THREAD

**Issue by ArnavK-09** [web-infra-dev/rspress#625]
### What problem does this feature solve?

![image](https://github.com/web-infra-dev/rspress/assets/69188140/17568530-744c-4318-8e31-41005fdcc08c)

### What does the proposed API look like?

```html
<img src="https://lf3-static.bytednsdoc.com/obj/eden-cn/uhbfnupenuhf/rspress/rspress-logo.webp" alt="Rspress Logo">
```

**Comment by sanyuan0704** [comment]
Yeah, the optimization is neccesary for user experience.
