### ISSUE TITLE
[Docs]: Guide to Create Own Themes!

### ISSUE THREAD

**Issue by ArnavK-09** [web-infra-dev/rspress#629]
### What problem does this feature solve?

We can have more community powered rspress themes if their would be proper guide on how to create own custom theme

### What does the proposed API look like?

Like theme-default, blog etc..

**Comment by sanyuan0704** [comment]
Good idea! I think it can be divided into two points:

- Documentation for proper custom theme,  such as how to develop a complete theme, extend the abilities of current default theme, publish your own theme and reuse the theme from others in community. Although we have the doc https://rspress.dev/guide/advanced/custom-theme.html, it could be more detailed and useful.
- Theme package support for rspress itself. Such as register npm package named `@rspress/blog-theme` in `rspress.config.ts` and then users can integrate the blog theme from the community.
