### ISSUE TITLE
[Feature]: Limit Rspress version range in the template

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#63]
### What problem does this feature solve?

When we create a new Rspress project, the version of the `rspress` package is `latest` by default. We should use `^0.0.9`  to avoid automatic upgrades to versions with breaking changes

```json
{
  "name": "rspress-doc-template",
  "private": true,
  "dependencies": {
    "rspress": "latest"
  }
}
```

### What does the proposed API look like?

```json
{
  "name": "rspress-doc-template",
  "private": true,
  "dependencies": {
    "rspress": "^0.0.9"
  }
}
```

**Comment by chenjiahan** [comment]
Maybe `workspace:^` would be better.

**Comment by sanyuan0704** [comment]
The scaffold project isn't inlucded in pnpm workspace so it will crash when installing.

**Comment by chenjiahan** [comment]
Get 👌
