### ISSUE TITLE
[Feature]: theme-default export DocLayout component for Custom Theme Usage

### ISSUE THREAD

**Issue by sumy7** [web-infra-dev/rspress#630]
### What problem does this feature solve?

 I am writing to propose a feature request for the project. It would be highly beneficial if the internal `DocLayout` component could be exported for use in custom themes.

### What does the proposed API look like?

```javascript
import { DocLayout} from '@rspress/theme-default';
```

**Comment by sanyuan0704** [comment]
No problem.

**Comment by sumy7** [comment]
Good! :smile:
