### ISSUE TITLE
[Bug]: Incorrect right sidebar after navigating

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#636]
### Version

```sh
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.23 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 16.6
  npmPackages:
    @rspress/shared: 1.11.0 => 1.11.0
    rspress: 1.11.0 => 1.11.0
```

### Details

Incorrect right sidebar after navigating:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/bd15bba8-e2d6-48f0-a80d-5b15786d668a)

### Reproduce link

https://www.rspack.dev/config/output.html

### Reproduce Steps

1. open https://www.rspack.dev/config/output.html
2. switch between "Output" and "Module":

![image](https://github.com/web-infra-dev/rspress/assets/7237365/c7aade9a-7b8a-4ed0-9530-064b73079171)

**Comment by chenjiahan** [comment]
Repo: https://github.com/web-infra-dev/rspack-website

**Comment by sumy7** [comment]
I've looked into the cause of this issue.

It appears that a duplicate ID was generated for the article titles,
![image](https://github.com/web-infra-dev/rspress/assets/3841747/49f88534-9af1-4d8f-9f38-ee232e4b2b00)
which caused a problem with React rendering.

**Comment by sanyuan0704** [comment]
> I've looked into the cause of this issue.
> 
> It appears that a duplicate ID was generated for the article titles, ![image](https://private-user-images.githubusercontent.com/3841747/306160994-49f88534-9af1-4d8f-9f38-ee232e4b2b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTk3NjIsIm5iZiI6MTcwODQxOTQ2MiwicGF0aCI6Ii8zODQxNzQ3LzMwNjE2MDk5NC00OWY4ODUzNC05YWYxLTRkOGYtOWYzOC1lZTIzMmU0YjJiMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDg1NzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVhMWNjNDU0NTU5NzZkODU1Njc2OTA2NWIxMTRhZGU4ZDE5YWQ1ZDQyMmQ3NDlmNTYyYWUxYjE1NzkyYTJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Kgbnt5SvWxSAqZHjkGzu6e027SJexDsSCBFAD6yUvII) which caused a problem with React rendering.

Yeah, we may change the value of id in react component

**Comment by Yukiniro** [comment]
Rspress uses gitHub-slugger to generate an id. The '.' will be replaced with '', so the `output.targetExport` and `output.target.export` will generate the same id `outputtargetexport`. Changing only the id in a React component will cause other problems, as mentioned in the previous comment. Is a better solution would be to modify the slugger library or use a custom id in MDX?  Like this:

```mdx
## output.libraryExport

### output.library.export {#outputlibraryexport1}
```

`output.libraryExport` will generate `outputlibraryexport`
`output.library.export` will generate `outputlibraryexport1`

**Comment by chenjiahan** [comment]
> modify the slugger library

Changing the slugger library can be a breaking change, the [custom id](https://github.com/web-infra-dev/rspress/blob/main/packages/core/src/node/utils/extractTextAndId.ts) seems to be a better workaround for this issue 😄
