### ISSUE TITLE
[Bug]: CSS problem responsive UI and copy-success Icon

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspress#644]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 59.83 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.184
    Chrome Canary: 123.0.6306.0
    Safari: 17.2.1
```

### Details

Problem Recording

Problem 1: 
<img width="880" alt="image" src="https://github.com/web-infra-dev/rspress/assets/79413249/27b676c5-e23a-4f1e-9b61-124d54bd9722">

Problem 2:
<img width="752" alt="image" src="https://github.com/web-infra-dev/rspress/assets/79413249/cb372784-48a0-4965-9c5c-17bb775265d6">

### Reproduce link

https://rspress.dev/zh/

### Reproduce Steps

width: 900px

**Comment by sanyuan0704** [comment]
I will look into this problem
