### ISSUE TITLE
[Bug]: After configuring cleanUrls, package and deploy it to nginx. After some paths are loaded normally, refreshing again will result in a 404 error message

### ISSUE THREAD

**Issue by 1418875140** [web-infra-dev/rspress#665]
### 版本信息

```sh
System:
    OS: Windows 11 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 22.06 GB / 31.69 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    rspress: ^1.0.0 => 1.11.2
```

### 问题详情

After configuring cleanUrls, package and deploy it to nginx. After some paths are loaded normally, refreshing again will result in a 404 error message
![701c9444387d18c0037bd4d71088ccc](https://github.com/web-infra-dev/rspress/assets/112247282/f6717037-cd6b-4f8b-84a6-9e6b8b2247de)

### 复现链接

https://gitee.com/TSGU-OSC/website/tree/build/

### 复现步骤

Configure cleanUrls: true in the configuration file, and then package and upload it to nginx to access some links. The first time is normal, but the second time will report a 404 error

**Comment by 1418875140** [comment]
After downloading the doc_build folder from the address on the link, place it in nginx, run nginx, and access the "Club Announcement". The first visit is normal, but after refreshing, it will be 404

**Comment by 1418875140** [comment]
Not only this announcement page, but also other pages are the same

**Comment by 1418875140** [comment]
> Not only this announcement page, but also other pages are the same

https://github.com/web-infra-dev/rspress/issues/665#issuecomment-1963649280

**Comment by 1418875140** [comment]
Changing clearUrl to false will enable normal access

> Not only this announcement page, but also other pages are the same

**Comment by sanyuan0704** [comment]
After you set `cleanUrls` as true, the links in doc will not include `.html` suffix, which makes nginx server failed to find the resource
