### ISSUE TITLE
[Feature]: Set the title suffix of home page

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#687]
### What problem does this feature solve?

Provide an option to set the title suffix of the home page.

Current:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/67e826a9-9759-475b-a256-61f944981964)

Expected:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/7c1606de-6837-48f0-b6d3-de60fc7e8042)

### What does the proposed API look like?

How about provide a new frontmatter config for this:

```mdx
---
title: Rspress
titleSuffix: - Rspack-based Static Site Generator
---
```

**Comment by sanyuan0704** [comment]
---
title: Rspress
titleSuffix: - Rspack-based Static Site Generator
---
What's the mean of the `-` after `titleSuffix`?

**Comment by chenjiahan** [comment]
So the complete title can be `Rspress - Rspack-based Static Site Generator` or `Rspress | Rspack-based Static Site Generator`

**Comment by h7ml** [comment]
> So the complete title can be `Rspress - Rspack-based Static Site Generator` or `Rspress | Rspack-based Static Site Generator`

What is the connector between title and titleSuffix? I have seen other pages default to using `-`

**Comment by chenjiahan** [comment]
Both "-" and "|" are common separators in web page titles.

it's fine that Rspress generates all title with the "-" seperator. What we have to do is maintain consistency between different pages.
