### ISSUE TITLE
[Bug]: Shouldn't frontmatter.title override extracted H1?

### ISSUE THREAD

**Issue by Huxpro** [web-infra-dev/rspress#710]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 176.88 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.0
```

### Details

According to <https://rspress.dev/api/config/config-frontmatter.html#front-matter-config>:

```
By default, the page's h1 heading will be used as the title of the HTML document. But if you want to use a different title, you can use Front Matter to specify the title of the page.
```

I assumed this meant the `frontmatter.title`, when given, should always be chosen over h1 heading, but the h1 heading would be chosen in the sidebar. 

By inspecting the source code, it seems like this is the reason:

```js
// plugin-auto-nav-sidebar 

export async function extractH1Title(...) {
  ...
  const match = content.match(h1RegExp);
  
  if (!match) {
    // only fallback to frontmatter.title when h1 is not found
    const { frontmatter } = loadFrontMatter(content, filePath, rootDir);
    return frontmatter.title || fileNameWithoutExt;
  } else {
    return match[1] || fileNameWithoutExt;
  }
}
```

See: <https://github.com/web-infra-dev/rspress/blob/4fd420d599adaaa76645e6ec3fbeb483ffae74a2/packages/plugin-auto-nav-sidebar/src/utils.ts#L41-L46>

Shall we change this?

### Reproduce link

https://applink.larksuite.com/client/message/link/open?token=AmRKLqSagAAFZedZ1TCAAAY%3D

### Reproduce Steps

For instance, when given:

```
---
title: <canvas>
---

# `<canvas>`
```

I will have 

```
`<canvas>`
```

rather than

```
<canvas>
```

rendered in the sidebar.

**Comment by sanyuan0704** [comment]
Thanks for the detailed feedback. Now the pr #711 has corrected the priority of frontmatter.title.

Example:

```markdown
---
title: <canvas>
---

# `<canvas>`
```

![image](https://github.com/web-infra-dev/rspress/assets/39261479/3d33ce08-744d-4f09-ab65-7d4e7fc78de3)

**Comment by sanyuan0704** [comment]
![image](https://github.com/web-infra-dev/rspress/assets/39261479/6417ecc4-66a2-4377-90a0-6904964b55ad)

Currently the code-formatted h1 rendered in sidenav has supported monospaced fonts😄

**Comment by Huxpro** [comment]
@sanyuan0704 BEAUTIFUL! thanks for the work ;)
