### ISSUE TITLE
没有显示md中的图片

### ISSUE THREAD

**Issue by zrz4066** [web-infra-dev/rspress#712]
### 版本信息

```sh
yarn run v1.22.19
warning ..\package.json: No license field
$ rspress dev
🔥 Rspress v1.13.2

  > Network:  http://26.26.26.1:8080/
  > Network:  http://172.19.224.1:8080/
  > Network:  http://192.168.100.182:8080/
  > Network:  http://localhost:8080/

start   Compiling...
ready   Client compiled in 4.1 s
start   Compiling...
ready   Client compiled in 3.9 s
```

### 问题详情

一开始执行yarn run dev，不能编译，后来把图片改成内联，可以显示，之后把图片缩放了一下，不能显示md文件的图片
![image](https://github.com/web-infra-dev/rspress/assets/16775484/a678f207-6088-48ac-9844-bf74424aed36)

### 复现链接

none

### 复现步骤

一开始执行yarn run dev，不能编译，后来把图片改成内联，可以显示，之后把图片缩放了一下，不能显示md文件的图片。控制台没有错误信息
![image](https://github.com/web-infra-dev/rspress/assets/16775484/a1d1aa0c-4a84-445b-a53f-6246dc98cf3d)

**Comment by sanyuan0704** [comment]
md 内容贴一下把

**Comment by zrz4066** [comment]
以下是md内容
[LF.md](https://github.com/web-infra-dev/rspress/files/14504232/LF.md)

**Comment by sumy7** [comment]
@zrz4066 
把图片放在md相同的文件夹，然后通过相对路径引用试试

目录结构
```
blog
| - LF.md
| - lf-stlink.png
```

图片引用
```md
连接STLink和LF Reader后，打开PC烧写工具STM32 ST-LINK Utility.exe，把文件LF_boot_app_full.hex烧写进去。
![lf-stlink](./lf-stlink.png)
```
