### ISSUE TITLE
[Feature]: should nav item  be clickable when having both 'items' and 'link' ?

### ISSUE THREAD

**Issue by evanryuu** [web-infra-dev/rspress#73]
### What problem does this feature solve?

Say I have a nav config like this
```ts
  themeConfig: {
    nav: [
      { 
        text: 'Coding Guide', 
        link: '/guide/', 
        items: [
          { text: 'HTML', link: '/guide/html' },
          { text: 'Javascript', link: '/guide/js' },
          { text: 'CSS', link: '/guide/css' },
        ] 
      }
    ],
  }
```

After setting `items` to the nav, it is not clickable.
<img width="137" alt="image" src="https://github.com/web-infra-dev/rspress/assets/55378595/32c6a906-6ef9-4427-b24f-1ce2c1903c55">

I'm wondering if we can still redirect when `link` and `items` are both provided.

This is quite a common need indeed, just like in [Apple Store](https://www.apple.com/store), the nav could still redirect.

<img width="572" alt="image" src="https://github.com/web-infra-dev/rspress/assets/55378595/6f62a8d3-9b9f-4410-ab9f-cab930f2c4e9">

Vitepress does not support this, I'm thinking maybe we can do this in Rspress?

### What does the proposed API look like?

```ts
  themeConfig: {
    nav: [
      { 
        link: '...', 
        items: [] 
      }
    ],
  }
```

**Comment by sanyuan0704** [comment]
Sure, would you like to implement this feature?

**Comment by evanryuu** [comment]
> Sure, it's a good advice.

Thank you! I'll try to implement this feature. If I run into any problems I will update🤜
