### ISSUE TITLE
[Feature]: Mask color of image preview should be dark in dark mode

### ISSUE THREAD

**Issue by xalanq** [web-infra-dev/rspress#730]
### What problem does this feature solve?

When user click the image, the mask color of  image preview should be dark instead of light.

![image](https://github.com/web-infra-dev/rspress/assets/30496124/5d8b2a05-a5b6-457c-9554-83371cddb282)

### What does the proposed API look like?

None

**Comment by sanyuan0704** [comment]
Yeah, i also notice the detail. Are you interested in solving the problem?

**Comment by xalanq** [comment]
> Yeah, i also notice the detail. Are you interested in solving the problem?

ok, I'll make a PR.

**Comment by xalanq** [comment]
@sanyuan0704 How about #732, is that ok?

**Comment by sanyuan0704** [comment]
> @sanyuan0704 How about #732, is that ok?

Thank you, i have commented on this pr.
