### ISSUE TITLE
[Bug]: Custom CSS variables not work after bumping Rspress v1.14.0

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#743]
### Version

```sh
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.24 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.111
    Safari: 16.6
  npmPackages:
    @rspress/shared: 1.14.0 => 1.14.0
    rspress: 1.14.0 => 1.14.0
```

### Details

Custom CSS variables not work after bumping Rspress v1.14.0.

- Rspack website with `rspress@1.11.0`:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/93334d2d-1303-4ad2-98e7-d4376c499e8b)

- Rspack website with `rspress@1.14.0`:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/9a374005-493e-4db3-8903-16a7478cc2f3)

It seems to be a problem with the CSS order. CSS variables in the [theme/index.css](https://github.com/web-infra-dev/rspack-website/blob/bump_rspress_0308/theme/index.css) can not override the default CSS variables.

### Reproduce link

https://github.com/web-infra-dev/rspack-website/tree/bump_rspress_0308

### Reproduce Steps

1. pnpm i
2. pnpm dev

**Comment by sumy7** [comment]
To add to this, if Tailwind CSS is also enabled in the project, duplicate classes will appear in the final bundled css output.
