### ISSUE TITLE
[Bug]: From version 1.12.0, HMR does not trigger after saving markdown files

### ISSUE THREAD

**Issue by Tyneor** [web-infra-dev/rspress#745]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 2.94 GB / 15.69 GB
  Browsers:
    Chrome: 121.0.6167.185
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    rspress: 1.11.0 => 1.11.0
```

### Details

When I edit and save a .md file in version 1.11.0, the content in the browser updates accordingly.
It does not work in versions 1.12.0, 1.13.0 and 1.14.0: no updates in the brower and no:
> start   Compiling...
> ready   Client compiled in 0.38 s

in the console.

Edit: however it updates well if I edit the rspress.config.ts or one of the .json files

Sorry for the redundancy if the issue was already identified.

### Reproduce link

npm create rspress@latest

### Reproduce Steps

1. `npm create rspress@latest` ->rspress version 1.14.0 is installed
2. `npm i`
3. edit any .md file
4. no compiling, no updates

**Comment by xc2** [comment]
please try out adding the config to package.json:

```json
{
  "overrides": {
    "@rspack/core": "0.5.5-canary-5143936-20240302163447"
  }
}
```

npm >= 8 is required

**Comment by Tyneor** [comment]
It works, thank you very much!
I suppose this will be fixed in @rspack/core 0.5.7?
If that's fine, I will wait for the next version to be released before closing the issue.

**Comment by xc2** [comment]
> It works, thank you very much!
> 
> I suppose this will be fixed in @rspack/core 0.5.7?

Yes.


> If that's fine, I will wait for the next version to be released before closing the issue.

Sure, please feel free

**Comment by Mumujianguang** [comment]
```pnpm``` should add the config to ```package.json```
```
{
  "pnpm": {
    "overrides": {
      "@rspack/core": "nightly"
    }
}
```

**Comment by chenjiahan** [comment]
Fixed in the latest version
