### ISSUE TITLE
[Bug]: how to support monorepo's alias resolve?

### ISSUE THREAD

**Issue by wood3n** [web-infra-dev/rspress#756]
### Version

```sh
System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 298.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.112
```

### Details

my project dir like this. i use rspress in website directory, it depends on packages/app. it can't resolve `paths` in packages/app, so how to configure rspress to support deep nested tsconfig `paths`.

```shell
/
┣ .changeset/
┣ .husky/
┣ .vscode/
┣ node_modules/
┣ packages/
	- app
┣ website/
	- rspress.config.ts
┣ package.json
┣ pnpm-lock.yaml
┣ pnpm-workspace.yaml
```
<img width="1055" alt="image" src="https://github.com/web-infra-dev/rspress/assets/31716713/c40f9a25-d265-48c0-b6ca-684c60dca0b3">

### Reproduce link

[![Edit competent-galileo-xc2lkj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/competent-galileo-xc2lkj?file=%2Fwebsite%2Fpackage.json&workspaceId=b94e54e5-a849-485c-ba2e-8e4a00630acd&embed=1)

### Reproduce Steps

please open codesandbox above and `pnpm run dev:web`

**Comment by 10Derozan** [comment]
You need to compile your app code to replace this alias.
If you want to use source code, you need to add [Source Build Plugin](https://rsbuild.dev/plugins/list/plugin-source-build) in rspress builderConfig.

**Comment by wood3n** [comment]
> You need to compile your app code to replace this alias. If you want to use source code, you need to add [Source Build Plugin](https://rsbuild.dev/plugins/list/plugin-source-build) in rspress builderConfig.

I have tried Source Build, but got this error, see this reproduce: https://codesandbox.io/p/devbox/competent-galileo-xc2lkj?file=%2Fwebsite%2Fpackage.json&embed=1

<img width="986" alt="image" src="https://github.com/web-infra-dev/rspress/assets/31716713/878e3679-23e9-4439-aea9-bd28534146c3">

**Comment by wood3n** [comment]
> You need add this dep to `source.include`

I tried, but still error. This error is from an inner package called `react-helmet-async`, not my code can't be compiled.

<img width="1725" alt="image" src="https://github.com/web-infra-dev/rspress/assets/31716713/72b098a1-2c88-4b80-b4f9-1700074cc22c">

**Comment by 10Derozan** [comment]
I mean that you need add `react-helmet-async` to `source.include`

**Comment by 10Derozan** [comment]
https://codesandbox.io/p/devbox/competent-galileo-xc2lkj?file=%2Fwebsite%2Fpackage.json&embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltp8w71q000a3b6gca8z73y7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltp8w71q00043b6gia2ziooi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltp8w71q00083b6gf5hevtjo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltp8w71q00093b6g7ky86g68%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltp8w71q00043b6gia2ziooi%2522%253A%257B%2522id%2522%253A%2522cltp8w71q00043b6gia2ziooi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwx83kh009q3b6g5ps40gs7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fwebsite%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltwx83kh009q3b6g5ps40gs7%2522%257D%252C%2522cltp8w71q00093b6g7ky86g68%2522%253A%257B%2522id%2522%253A%2522cltp8w71q00093b6g7ky86g68%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltp8w71q00083b6gf5hevtjo%2522%253A%257B%2522id%2522%253A%2522cltp8w71q00083b6gf5hevtjo%2522%252C%2522tabs%2522%253A%255B%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by 9aoy** [comment]
@wood3n This is a bug about supporting source-build in mdx files, we will fix it in the next version.

**Comment by 10Derozan** [comment]
You can add `main: './src/index.ts'` to app/package.json to avoid it, later @9aoy will fix it.

**Comment by wood3n** [comment]
@9aoy @10Derozan @chenjiahan Thanks all. I hava been update rspress to latest version, But it still can't run, it seems like `react-helmet` is wrong.

<img width="1728" alt="image" src="https://github.com/web-infra-dev/rspress/assets/31716713/ac96b73f-b22e-44a5-a63b-782718be5b14">
