### ISSUE TITLE
[Feature] Re-export HomeHero from theme-default for customizable usages? 

### ISSUE THREAD

**Issue by Huxpro** [web-infra-dev/rspress#765]
### What problem does this feature solve?

I'm thinking of rendering `<HomeHero />` for certain sub-pages. Do you think this could be a good idea? 

### What does the proposed API look like?

```tsx
// docs/contents/zh/dir/dir/index.mdx

import { HomeHero } from 'rspress/runtime';

<HomeHero
  frontmatter={{
    hero: {
      name: "A Sub-Project",
      text: "A Sub-Project Under Main Project",
      actions: [
        {
          text: "Get Started",
          link: "/start/index.html",
          theme: "brand",
        }
      ]
    }
   }}
/>

```

**Comment by sanyuan0704** [comment]
Yeah, i think it's ok to export more automatic render abilities in theme-default. cc @10Derozan

**Comment by 10Derozan** [comment]
I have re-export all internal components which in rspress, in #817 .
And after this, you can use it from 'rspress/theme'

**Comment by 10Derozan** [comment]
It's in https://rspress.dev/api/client-api/api-components.html#homehero
