### ISSUE TITLE
[Bug]: Code blocks highlighted in different modes

### ISSUE THREAD

**Issue by zhenghui-su** [web-infra-dev/rspress#766]
### Version

```sh
Windows10
chrome
node: 16.15.0
use pnpm
```

### Details

Why can the code block here be highlighted in dev mode, but it is not highlighted in preview mode after packaging
And after I deployed it to the server, there was no highlight either

The code block here is Lua, but not limited to Lua, such as HTTP
dev mode
![image](https://github.com/web-infra-dev/rspress/assets/104132375/2056b733-283c-46f0-909b-215cdaae3cf7)
In preview mode after build
![image](https://github.com/web-infra-dev/rspress/assets/104132375/f8d48d9f-65d2-4d91-ae73-46ff0a1b4019)

dev mode
![image](https://github.com/web-infra-dev/rspress/assets/104132375/2cfcd74a-1dbb-4917-a518-76681ca69242)

preview mode
![image](https://github.com/web-infra-dev/rspress/assets/104132375/08bf2828-c1d0-46e1-8716-d7399ff9ff5d)

I did not use the @ rspress/plugin shiki plugin here
If I use it, it can solve this problem, but the spacing between the code in the code block and the border is missing for some reason，It fits tightly with the border 
![image](https://github.com/web-infra-dev/rspress/assets/104132375/b16fee37-c5d7-4c0e-88f3-611f28891b2f)

### Reproduce link

https://www.xiaosu2003.cn/guide/node/50-lua(%20%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8%20).html

### Reproduce Steps

Write to Markdown file

```lua
chen = 'chenchen'

print(chen)
```
Then view in dev mode，use `rspress dev`

Finally  build and view in preview mode，use `rspress build`，then use `rspress preview`

**Comment by sanyuan0704** [comment]
You should add the language the `markdown.highlightLanguages` config. https://rspress.dev/api/config/config-build.html#markdownhighlightlanguages

**Comment by zhenghui-su** [comment]
Using @ rspress/plugin shiki will make the code and borders tightly fit together
![image](https://github.com/web-infra-dev/rspress/assets/104132375/d159c159-1630-48eb-a29f-9a2fff46b634)
This is what I am using
![image](https://github.com/web-infra-dev/rspress/assets/104132375/08ca0949-9b6c-4b6c-a047-718439043780)

**Comment by sanyuan0704** [comment]
Ok, i will fix it and release a patch version right away.
