### ISSUE TITLE
[Bug]: Should not render code block in the aside links 

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#776]
### Version

```sh
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.25 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 16.6
  npmPackages:
    rspress: ^1.15.0 => 1.15.0
```

### Details

Should not render code block in the aside links, plain text can be better for reading:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/04f06787-1676-44d3-9e56-0250c5ea4304)

### Reproduce link

https://rsbuild.dev/config/dev/asset-prefix#compare-with-publicpath

### Reproduce Steps

1. git clone git@github.com:web-infra-dev/rsbuild.git
2. pnpm i
3. pnpm dev:doc

**Comment by sanyuan0704** [comment]
It's feature for inline markdown https://github.com/web-infra-dev/rspress/pull/721

**Comment by chenjiahan** [comment]
But the current style is really ugly..

![image](https://github.com/web-infra-dev/rspress/assets/7237365/65e54f7c-128b-439c-a7d4-58f1ed282201)

**Comment by sanyuan0704** [comment]
I will optimize the code style

**Comment by Huxpro** [comment]
Agree with @sanyuan0704 that this feature is highly wanted and only needs styling tweaks

**Comment by chenjiahan** [comment]
The current code block style LGTM 😄

![image](https://github.com/web-infra-dev/rspress/assets/7237365/04a1ba91-725d-40a5-950f-c8ed4dede7ec)
