### ISSUE TITLE
[Bug]:  Bug on the Side Bar Dropdown Changing to Blank Page

### ISSUE THREAD

**Issue by zhenghui-su** [web-infra-dev/rspress#779]
### Version

```sh
Win10
Chrome
Rspress @1.15.0
node: 16.15.0
```

### Details

After entering, click on the dropdown sidebar on the left, and the page will become blank
![image](https://github.com/web-infra-dev/rspress/assets/104132375/7875a48d-8dee-4da6-bf29-3943326e8a39)

![image](https://github.com/web-infra-dev/rspress/assets/104132375/597adfa3-4809-47d8-8c71-6b8acb476314)

### Reproduce link

no url

### Reproduce Steps

Click on any sidebar with content that can be pulled down, and the page will become blank

**Comment by xc2** [comment]
cause by https://github.com/web-infra-dev/rspress/pull/768

**Comment by sanyuan0704** [comment]
v1.15.1 has fixed it
