### ISSUE TITLE
The UX of 2nd sticky nav on mobile

### ISSUE THREAD

**Issue by Huxpro** [web-infra-dev/rspress#799]
### Version

```sh
Current website build
```

### Details

![IMG_9895](https://github.com/web-infra-dev/rspress/assets/5563315/20bcdd6e-4b38-437d-91c4-56e9e8724a7b)
 
There are 2 UX issues that can be improved from the screenshot:
1. The “on this page” nav is overflowed but unscrollable.
2. The 1st sticky nav, when scrolling down, will slide down and hide the 2nd sticky nav. I understand that this may be an intentional choice of design, comparing to Vitepress where the 1st nav is only visible all the way up, but it would have being a better UX during scrolling down if we can make the 1st nav “pushing” the 2nd nav down so both navs are visible simultaneously to make the UX even better.

### Reproduce link

https://rspress.dev/guide/start/introduction.html#differences-from-other-ssg-frameworks

### Reproduce Steps

See https://rspress.dev/guide/start/introduction.html#differences-from-other-ssg-frameworks on mobile. Scrolling up and down and observe how 1st sticky nav and 2nd sticky nav interacting with each other

**Comment by sanyuan0704** [comment]
The new 2nd sticky nav preview https://deploy-preview-802--aquamarine-blini-95325f.netlify.app/ by #802
