### ISSUE TITLE
[Feature]: RSS feed

### ISSUE THREAD

**Issue by slorber** [web-infra-dev/rspress#828]
### What problem does this feature solve?

We should be able to follow project release blog posts thanks to a RSS feed.

For example, I'd like to be notified whenever there is a new release here:
https://rsbuild.dev/community/releases/

Docusaurus blogs have this out of the box: https://docusaurus.io/blog/rss.xml

### What does the proposed API look like?

No idea what the API should look like sorry 😅 Maybe it's not even a goal of this project, or maybe it should be part of the "blog theme" that is in the roadmap? (https://github.com/web-infra-dev/rspress/issues/133)
```[tasklist]
### Tasks
```

**Comment by chenjiahan** [comment]
@xc2 has implemented an RSS plugin for the Rspack website (https://github.com/web-infra-dev/rspack-website/issues/543), maybe we can make it as an official Rspress plugin and integrate it into the Rsbuild / Rspress websites.

@xc2 Can you help with this? ❤️

**Comment by xc2** [comment]
i’m occupied by office tasks recently, so i’ll begin the work this weekend.

**Comment by chenjiahan** [comment]
Added:

- https://rsbuild.dev/rss/releases.xml
- https://rspack.dev/rss/blog-en.rss

**Comment by slorber** [comment]
Thanks

Rspack already had a feed afaik.

Rsbuild now has one, but it is still not discoverable because the meta tag is not added:

`<link data-rh="true" rel="alternate" type="application/rss+xml" href="[/rss/blog-en.rss](https://www.rspack.dev/rss/blog-en.rss)" hrefLang="en"/>`

![CleanShot 2024-04-05 at 14 28 59@2x](https://github.com/web-infra-dev/rspress/assets/749374/605f1c57-e424-4676-afbe-e1e55a82b432)

**Comment by chenjiahan** [comment]
Thanks for the feedback, it seems like a bug of `@rspress/plugin-rss`, @xc2 should we generate a meta tag for the home page?

**Comment by xc2** [comment]
> Thanks for the feedback, it seems like a bug of `@rspress/plugin-rss`, @xc2 should we generate a meta tag for the home page? 😄

Should add frontmatter `link-rss` for homepage.

https://rspress.dev/plugin/official-plugins/rss.html#linking-rss-to-document-pages

Eg 

```markdown
---
link-rss: release
---
```

```markdown
---
link-rss:
- release
- blog
---
```

**Comment by xc2** [comment]
> Also I think the feed should rather be sorted in the opposite order (newest first)

I'm using both inoreader and thunderbird, and both of them sort articles based on the pubDate by default  when i'm adding a subscription.

anyway I'll create a pr to add the sorting feature as i'm not sure if most of the rss readers will sort items well.

**Comment by slorber** [comment]
Yes most will sort themselves, but some will not. Also sooner or later you'll have users with large user bases and hundreds of blog posts and feeds of many megabytes and you'll need to add a truncate feed feature otherwise feed readers won't download a 100mb feed 😄

**Comment by xc2** [comment]
> Yes most will sort themselves, but some will not. Also sooner or later you'll have users with large user bases and hundreds of blog posts and feeds of many megabytes and you'll need to add a truncate feed feature otherwise feed readers won't download a 100mb feed 😄

thank you for your helpful advise.

there's way to truncate content atm: https://rspress.dev/plugin/official-plugins/rss.html#item though it is not applied by default as i didn't find a cheap and good enough strategy that can be applied as default solution.

**Comment by chenjiahan** [comment]
After fixing some bugs, [rsbuild.dev](https://rsbuild.dev/) can now be correctly recognized by ioreader. Thanks for all the suggestions ❤️

![image](https://github.com/web-infra-dev/rspress/assets/7237365/2b124eda-dd1a-4e18-afe6-e567a3ca62f2)
