### ISSUE TITLE
[Feature]: Support HMR for plugins

### ISSUE THREAD

**Issue by RussellCanfield** [web-infra-dev/rspress#85]
### What problem does this feature solve?

RSPress works great so I wanted to start with a thank you!

I'm not sure if this is a feature or a bug, but currently I am using RSPress 0.0.13, and using the @theguild/remark-mermaid plugin. I have noticed that HMR does not work for mermaid diagrams. Other code snippets, mdx files, etc. seem to work without any issues. Is it possible to support this feature?

### What does the proposed API look like?

I don't think there is an API change to support this feature, and probably iterating all the plugins may have a performance implication. It's possible that their plugin is responsible for the functionality/hook.

**Comment by sanyuan0704** [comment]
Can you provide a reproduce repo?

**Comment by sanyuan0704** [comment]
@RussellCanfield

**Comment by RussellCanfield** [comment]
Sorry for the delay!

Here is the repo:
https://github.com/RussellCanfield/rspress-mermaid

Basically run "dev", then I put the link under the "Hello World" link in the navbar. It's called "test.mdx"

For repro, just modify any text within the "```mermaid" code block, such as changing "Mobile app" to "Mobile app123". You will notice it doesn't hot reload, refreshing the page manually works.

Hope this makes sense!

**Comment by sanyuan0704** [comment]
That is a bug in `remark-mermaid` instead of rspress.I will fix it.

**Comment by sanyuan0704** [comment]
https://github.com/the-guild-org/docs/pull/1246

**Comment by sanyuan0704** [comment]
@theguild/remark-mermaid 0.0.5 has fixed it.

**Comment by sanyuan0704** [comment]
@RussellCanfield

**Comment by RussellCanfield** [comment]
Thank you very much :)
