### ISSUE TITLE
[Feature]: Support tooltip when hover Aside item

### ISSUE THREAD

**Issue by 10Derozan** [web-infra-dev/rspress#891]
### What problem does this feature solve?

When hover in item, we can show a tooltip for overflow.
![image](https://github.com/web-infra-dev/rspress/assets/50694858/8042469b-39ef-49ce-b121-9ebf073d69ac)

### What does the proposed API look like?

No API.

**Comment by ArnavK-09** [comment]
# 🙋‍♂️
