### ISSUE TITLE
[Bug]: relative resource import and display in plugin-preview

### ISSUE THREAD

**Issue by linbudu599** [web-infra-dev/rspress#902]
### Version

```sh
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 139.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 123.0.6312.87
    Edge: 110.0.1587.50
    Safari: 17.4
  npmPackages:
    @rspress/plugin-preview: ^1.16.2 => 1.16.2 
    rspress: ^1.16.2 => 1.16.2
```

### Details

The current code block based on the `rspress-plugin-preview` rendering does not correctly parse resources for relative paths, and also lacks the ability to display resources imported by relative paths.

```bash
  × Resolve error: Can't resolve './index.less' in '/PATH/TO/rspress-site/node_modules/.rspress/virtual-demo'
   ╭─[1:1]
 1 │ import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
 2 │ import "./index.less";
   ·        ──────────────
 3 │ function App() {
 4 │     return /*#__PURE__*/ _jsxDEV("h1", {
```

**Also, the presentation of relatively imported resources is an ability worth considering.**

### Reproduce link

_

### Reproduce Steps

Add `rspress-plugin-preview` to config file like:

```typescript
import * as path from 'path';
import { defineConfig } from 'rspress/config';
import { pluginPreview } from '@rspress/plugin-preview';

export default defineConfig({
  root: path.join(__dirname, 'docs'),
  plugins: [pluginPreview()],
});
```

```bash
docs
├── index.less
└── index.mdx
```

Import relative resource in mdx file:

````markdown
# Hi!

```tsx
import './index.less';

function App() {
  return <h1>Hello World</h1>;
}
export default App;
```
````

**Comment by sanyuan0704** [comment]
The code in the markdown code block will be extracted in a single file under a temporary directory, so it's better to use alias to import external modules.

**Comment by linbudu599** [comment]
Oh, I got confused with the difference between inline code blocks and reference code blocks, which are indeed available under reference code blocks.
