### ISSUE TITLE
[Feature]: Hide aside element when no heading present

### ISSUE THREAD

**Issue by linbudu599** [web-infra-dev/rspress#915]
### What problem does this feature solve?

If no headings exist on the current page, should the aside component for displaying headings be hidden by default? This allows the page content to be better centered within the viewport. If this behavior is not considered to be on by default, should a new configuration be added to support it as well?

The following images show the before and after effects of hiding aside:

![image](https://github.com/web-infra-dev/rspress/assets/48507806/9846f5d3-9156-47e8-89bf-6db0e60188d4)

![image](https://github.com/web-infra-dev/rspress/assets/48507806/67d03a2a-199e-46a9-bdb0-7e7f61e31a41)

### What does the proposed API look like?

noop

**Comment by Timeless0911** [comment]
see details https://github.com/web-infra-dev/rspress/pull/1031#issuecomment-2081570591
