### ISSUE TITLE
[Bug]: socialLinks中链接mode为img时，图片尺寸太小了，无法看清二维码

### ISSUE THREAD

**Issue by stevobm** [web-infra-dev/rspress#922]
### 版本信息

```sh
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 100.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 17.4.1
  npmPackages:
    rspress: ^1.17.1 => 1.17.1
```

### 问题详情

![screenshot-1712568870522](https://github.com/web-infra-dev/rspress/assets/5198256/3be4a19b-a032-44f8-ba0f-97aad4b4edbb)

### 复现链接

无

### 复现步骤

  rspress.config.ts文件中配置[sociallinks](https://rspress.dev/zh/api/config/config-theme.html#sociallinks)为图片链接时，比如{
        icon: 'qq',
        mode: 'img',
        content: '/qq-group.png',
      },
图片会非常小，导致二维码看不清。

**Comment by h7ml** [comment]
https://github.com/web-infra-dev/rspress/blob/3a8251f61dc1332f47ac4027e83cd3f7b401c9b2/packages/theme-default/src/components/SocialLinks/LinkContent.tsx#L66-L90


看了下``LinkContent`` 设置图片大小的值为``w-[50px] h-[50px]``

根据单一的需求去修改``img``的形式不是很友好。

这里感觉有必要扩充渲染``dom``形式 由使用者传入自定义内容。

**Comment by h7ml** [comment]
@Timeless0911   Can LinkContent be extended like this, I'm not sure if it will affect other features. One more thing, I didn't find a unit test to test this pr

**Comment by Timeless0911** [comment]
@h7ml I think for the image scenario, we only need to add a classname, such as `rspress-social-links-img`, so that users can customize its style?

**Comment by h7ml** [comment]
> @h7ml I think for the image scenario, we only need to add a classname, such as `rspress-social-links-img`, so that users can customize its style?

If you do this, will you pass `classname` directly to resolve it, or will there be a certain limited scope, such as using the style within the component?

I think it's better to expand to dom. There are no restrictions on this use

**Comment by Timeless0911** [comment]
@h7ml  I agree with your idea, I wonder if 50px is too small for the img scene, maybe we can make it larger by default?

**Comment by h7ml** [comment]
> @h7ml I agree with your idea, I wonder if 50px is too small for the img scene, maybe we can make it larger by default?

Increasing the default size of the image in the LinkContent component from 50px to a larger size sounds like a good idea if you think 50px is too small. You can adjust the size as per your requirements.
