### ISSUE TITLE
[Bug]: action.link in HomeHero Component doesn't generate link with language prefix

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#924]
### Version

```sh
-
```

### Details

https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/components/HomeHero/index.tsx#L66

![image](https://github.com/web-infra-dev/rspress/assets/50201324/d3cf50e7-7a3c-46d2-a2e4-d940b13ef21c)

we need to manually add zh prefix to config link in zh docs

### Reproduce link

https://github.com/web-infra-dev/rspress/blob/main/packages/document/docs/zh/index.md?plain=1#L17

### Reproduce Steps

- pnpm run dev

**Comment by shulaoda** [comment]
I think it should be resolved by the compiler, as most of the other links are done through the compiler.
In addition, if dynamic linking is required, it should be resolved through the theme to use `useLang` with `normalizeHref`.

**Comment by Timeless0911** [comment]
> I think it should be resolved by the compiler, as most of the other links are done through the compiler. In addition, if dynamic linking is required, it should be resolved through the theme to use `useLang` with `normalizeHref`.

This is a point that can be optimized. The experience should be the same as the link in the mdx file, with the lang prefix automatically added. Currently, the hero component has no related `normalizeHref` operation.

**Comment by shulaoda** [comment]
> > I think it should be resolved by the compiler, as most of the other links are done through the compiler. In addition, if dynamic linking is required, it should be resolved through the theme to use `useLang` with `normalizeHref`.
> 
> This is a point that can be optimized. The experience should be the same as the link in the mdx file, with the lang prefix automatically added. Currently, the hero component has no related `normalizeHref` operation.

So, how should I solve this problem? Compiler or Component (theme-default)

**Comment by Timeless0911** [comment]
> So, how should I solve this problem? Compiler or Component (theme-default)

I think component is better for theme related like i18n and multiversion. @sanyuan0704 What's your opinion?
