### ISSUE TITLE
[Feature]:  rspress/plugin-api-docgen needs a parameter to be transmitted to react-docgen-typescript withCustomConfig

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rspress#928]
### What problem does this feature solve?

rspress/plugin-api-docgen needs a parameter to be transmitted to react-docgen-typescript withCustomConfig configuration parameters

To solve this problem: https://github.com/styleguidist/react-docgen-typescript/issues/144

### What does the proposed API look like?

a props parameter.

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspress/blob/main/packages/plugin-api-docgen/src/types.ts#L51  It semms there is already a parameter option that is not exposed in the documentation

**Comment by Timeless0911** [comment]
We should support pass in a custom parser **instance** in https://github.com/web-infra-dev/rspress/blob/main/packages/plugin-api-docgen/src/docgen.ts#L56
