### ISSUE TITLE
[Feature]: Remove '.html' suffix of url links

### ISSUE THREAD

**Issue by xalanq** [web-infra-dev/rspress#93]
### What problem does this feature solve?

![image](https://github.com/web-infra-dev/rspress/assets/30496124/7c96a1f8-3b7b-4bed-8c2f-9f0091b28f2e)

### What does the proposed API look like?

nothing

**Comment by sanyuan0704** [comment]
Why do you want to remove the suffix?

**Comment by xalanq** [comment]
> Why do you want to remove the suffix?

Make urls shorter and look better

**Comment by sanyuan0704** [comment]
SSG output are html files, so bring .html to make the path more accurate and intuitive

**Comment by xalanq** [comment]
> SSG output are html files, so bring .html to make the path more accurate and intuitive

That's no doubt that the output files are html files. And I could also write some nginx rules to remove the '.html' suffix from the url.

BUT what I want is that the urls generated by rspress on `sidebar` and `navbar` should clean the '.html' suffix. Becoz It's so weird that there are still the '.html' suffix with the urls when user hover the `<a>` tag links in 2023, 21st century.

**Comment by sanyuan0704** [comment]
I think it's worth sacrificing URL length for compatibility. After removing the .html suffix, if you jump to a link and want to share the link with others, they may not be able to access the HTML file because there is no .html suffix.

**Comment by chenjiahan** [comment]
Vuejs: https://vuejs.org/api/

![image](https://github.com/web-infra-dev/rspress/assets/7237365/3ca92127-ece6-45c1-9bca-7c0588c6bdc2)

![image](https://github.com/web-infra-dev/rspress/assets/7237365/2e00895c-6b00-426c-88e2-698eb9891099)

**Comment by xalanq** [comment]
> Vuejs: https://vuejs.org/api/
> 
> ![image](https://user-images.githubusercontent.com/7237365/269184434-3ca92127-ece6-45c1-9bca-7c0588c6bdc2.png)
> 
> ![image](https://user-images.githubusercontent.com/7237365/269184206-2e00895c-6b00-426c-88e2-698eb9891099.png)

- React：https://react.dev/learn/installation
![image](https://github.com/web-infra-dev/rspress/assets/30496124/d0529351-016a-4cbf-9de1-332656aba1f3)

- GitBook: e.g. https://react.i18next.com/
![image](https://github.com/web-infra-dev/rspress/assets/30496124/de6f4328-ef82-4521-aa97-3206b4b16699)

- Docusaurus: https://docusaurus.io/docs/installation
![image](https://github.com/web-infra-dev/rspress/assets/30496124/260892cc-b80a-4ff5-b6b8-466e11693b54)

- Electron: https://www.electronjs.org/docs/latest/
![image](https://github.com/web-infra-dev/rspress/assets/30496124/a2cee5cf-b0b3-4bbf-9115-032cb75a00c8)

- MDN: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
![image](https://github.com/web-infra-dev/rspress/assets/30496124/3a761f42-759c-4cea-a9ad-592768756efd)

**Comment by chenjiahan** [comment]
This isn't a competition to prove which method has more adopters, it's just to prove that .html is still widely used.

**Comment by xalanq** [comment]
> This isn't a competition to prove which method has more adopters, it's just to prove that .html is still widely used.

OK. Could you provide a trigger to remove the suffix in configuration. It's very helpful and I really appreciate it. Thanks!

**Comment by chenjiahan** [comment]
Agreed, we should add a `cleanUrls` option to remove the trailing `.html` from generated URLs.

Ref: https://vitepress.dev/reference/site-config#cleanurls

**Comment by zoolsher** [comment]
https://rspress.dev/api/config/config-basic#routecleanurls

@xalanq The latest version of Rspress now supports `route.cleanUrls`. Could you please try it out?
