### ISSUE TITLE
[Bug]: Left sidebar disappeared when URL includes `.html`

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#933]
### Version

```sh
"rspress": "^1.17.1"
```

### Details

- https://www.rspack.dev/blog/announcing-0.6.html

![image](https://github.com/web-infra-dev/rspress/assets/7237365/018a993d-dcd0-4344-965c-a00c272a3caa)

- https://www.rspack.dev/blog/announcing-0.6

![image](https://github.com/web-infra-dev/rspress/assets/7237365/bc74cfe1-bd59-4549-9c60-a84d03767e8d)

### Reproduce link

https://github.com/web-infra-dev/rspack/tree/main/website

### Reproduce Steps

1. cd website
2. pnpm i
3. pnpm dev

**Comment by Timeless0911** [comment]
@sumy7 can you help take a look at this when you have time~

**Comment by sumy7** [comment]
hi @chenjiahan @Timeless0911 
I've looked into the issue and found that the problem occurs during the process of normalizing URLs into .html links.
https://github.com/web-infra-dev/rspress/blob/main/packages/shared/src/runtime-utils/index.ts#L245
The titles containing periods are mistakenly interpreted as having file extensions. As a result, the normalized links do not correctly match the data in the sidebar.

**Comment by chenjiahan** [comment]
I have upgraded to the latest version and the above bug has been fixed 👍

## Another bug

However, there is still a similar bug when using `cleanUrls: true`.

When `cleanUrls: true` is set, the generated URL will not contains `.html` suffix. But in some cases, we may still visit the page with `.html` URLs, and the sidebar will be disappeared:

![image](https://github.com/web-infra-dev/rspress/assets/7237365/87fe6392-41da-4608-9b25-c07fbce8ac70)

See:

- https://rsbuild.dev/guide/start/quick-start
- https://rsbuild.dev/guide/start/quick-start.html

It would be nice if Rspress can compatible with this case
