### ISSUE TITLE
[Feature]: Syncing PackageManagerTabs and Tabs Choices

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#937]
### What problem does this feature solve?

Users may want choices of the same kind of tabs to sync with each other when they choose from PackageManagerTabs.
![image](https://github.com/web-infra-dev/rspress/assets/50201324/c38eb420-5baf-4020-86f9-0d454ea085dd)

Also for the Tabs Component, we can also do the same thing to sync tab choices

### What does the proposed API look like?

E.g.: https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices

**Comment by iicdii** [comment]
FYI, Docusaurus stores the latest chosen tab in local storage.
