### ISSUE TITLE
[Feature]: Separate search index by version

### ISSUE THREAD

**Issue by jbroma** [web-infra-dev/rspress#947]
### What problem does this feature solve?

When searching through documentation, I would like to only display results relevant to the currently selected version.
Right now, all versions get combined into one search index.

Splitting the search index into separate entities by version would also reduce size needed to download upon opening the search panel.

### What does the proposed API look like?

To make it non-breaking, it could be introduced as an optional prop to `config.search` like this:

```ts
//rspress.config.ts
export default defineConfig({
  search: {
    versioned: true,
  },
});
```

**Comment by sanyuan0704** [comment]
> @sanyuan0704 I see the PR got merged, but the docs were not updated to reflect this change, I think it's important to mention that somewhere.

@jbroma Would you like to add some docs to reflect this change?

**Comment by jbroma** [comment]
sure thing, I'll add the english part 👍
