### ISSUE TITLE
[Bug]: Bugs related to version 1.18.1 startup

### ISSUE THREAD

**Issue by zhenghui-su** [web-infra-dev/rspress#951]
### Version

```sh
Win10
node：16.15.0
rspress: 1.18.1
plugin: @rspress/plugin-shiki 1.18.1
```

### Details

My version 1.17.1 can start, but when I update to 1.18.1, an error message will appear
![image](https://github.com/web-infra-dev/rspress/assets/104132375/81695876-8309-4c7b-b3bb-a7c9c3c711c7)
![image](https://github.com/web-infra-dev/rspress/assets/104132375/3f450764-2049-4451-bd98-5311e382733f)

### Reproduce link

no link

### Reproduce Steps

update  Rspress 1.18.1 ，run `pnpm run dev`

**Comment by zhenghui-su** [comment]
This error has nothing to do with Chinese
The reason should be that if the name attribute of _meta.json has a suffix like .io  .json
![a1de8baa4b482d3725010c3660cdd15](https://github.com/web-infra-dev/rspress/assets/104132375/af2862ff-bc5e-4091-9152-8c9cd86b5344)

![image](https://github.com/web-infra-dev/rspress/assets/104132375/4507ff0e-30e7-43bc-a756-7f7a7875a847)
If I add the md suffix, it will solve the problem
![image](https://github.com/web-infra-dev/rspress/assets/104132375/00a86a4a-b03f-4b42-b33a-03c522d463da)

**Comment by Timeless0911** [comment]
May I ask what the correspoding file name is?

**Comment by zhenghui-su** [comment]
> May I ask what the correspoding file name is?

like this
![image](https://github.com/web-infra-dev/rspress/assets/104132375/69a8a004-e69a-41e2-a4d9-ad909d146055)


I just need to add the. md suffix to the name attribute of _meta.json to solve the problem
![image](https://github.com/web-infra-dev/rspress/assets/104132375/cafbf1be-aadb-4d04-ba48-703ad89f53c7)

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspress/blob/3a8251f61dc1332f47ac4027e83cd3f7b401c9b2/packages/plugin-auto-nav-sidebar/src/utils.ts#L12

We detect the file path in this logic, it seems have a little problem in your case that file name already have a suffix similar to an extension.

**Comment by zhenghui-su** [comment]
> https://github.com/web-infra-dev/rspress/blob/3a8251f61dc1332f47ac4027e83cd3f7b401c9b2/packages/plugin-auto-nav-sidebar/src/utils.ts#L12
> 
> We detect the file path in this logic, it seems have a little problem in your case that file name already have a suffix similar to an extension.

Yes, that's the problem, so I solved it by adding a suffix to the name
