### ISSUE TITLE
[Bug]: Regarding the issue of the right sidebar not being displayed

### ISSUE THREAD

**Issue by zhenghui-su** [web-infra-dev/rspress#952]
### Version

```sh
win10
node: 16.15.0
rspress: 1.18.1
plugin: @rspress/plugin-shiki: 1.18.1
```

### Details

If I add italics to the text of the title, there will be a problem where the right sidebar cannot be displayed
![image](https://github.com/web-infra-dev/rspress/assets/104132375/5145ba7b-db8d-4e2e-934d-aa47b660c22e)
![image](https://github.com/web-infra-dev/rspress/assets/104132375/cefd8b80-9ad9-4108-94bc-a8f9ace3553c)

### Reproduce link

no link

### Reproduce Steps

Randomly add italics to the title text content of an MD file, and then start viewing the right sidebar

**Comment by shulaoda** [comment]
This issue is caused by the `plugin_toc` of `@rspress/mdx-rs`, and I have fixed it in [#28](https://github.com/web-infra-dev/mdx-rs/pull/28).
I still need to solve the issue of converting it in the sidebar in rspress, which will take a day.
