### ISSUE TITLE
[Bug]: CheckDeadLinks broken when `markdown.mdxRs` set to false

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rspress#965]
### 版本信息

```sh
-
```

### 问题详情

In this PR #955 , we modify the checkLinks function for remove only known extension, but in below code (checkDeadLinks logic in `mdxRs: false`)

https://github.com/web-infra-dev/rspress/blob/221da5e8ead5ec59a5f4fdc61b2a1dc534483377/packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts#L67-L76

The `internalLinks` variable will contain `.html` suffix， which caused the error:

![image](https://github.com/web-infra-dev/rspress/assets/50201324/ede74ac1-1d93-4aa2-bc63-5aca6d3db930)

In former logic, we remove all `.*` extensions, but now we only remove `DEFAULT_PAGE_EXTENSIONS = ['js', 'jsx', 'ts', 'tsx', 'md', 'mdx']`. 

Maybe we need to add a logic to remove the `.html` suffix after line 72?

### 复现链接

https://github.com/web-infra-dev/rspress/blob/main/packages/document/package.json#L15

### 复现步骤

1. `pnpm i`
2. modify https://github.com/web-infra-dev/rspress/blob/221da5e8ead5ec59a5f4fdc61b2a1dc534483377/packages/document/rspress.config.ts#L17

add `mdxRs: false` config

```ts
markdown: {
    checkDeadLinks: true,
    mdxRs: false,
},
```
3. `pnpm dev`

**Comment by Timeless0911** [comment]
@jbroma Hi, can you help confirm this?

**Comment by jbroma** [comment]
@Timeless0911 yeah, I didn't realize `remarkCheckDeadLinks` only applies when `markdown.mdxRs` is set to false. Nice find 👍 

We should probably handle `.html` separately inside of `normalizeRoutePath` in `RouteService.ts`, similarly to how it's done in `packages/runtime/src/utils.ts`:
```ts
export function normalizeRoutePath(routePath: string) {
  return decodeURIComponent(routePath)
    .replace(/\.html$/, '')
    .replace(/\/index$/, '/');
}
```
