### ISSUE TITLE
[Bug]: 中文斜体样式不生效

### ISSUE THREAD

**Issue by soulwu** [web-infra-dev/rspress#984]
### 版本信息

```sh
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 110.27 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 124.0.6367.61
  Safari: 17.2.1
npmPackages:
  rspress: ^1.0.0 => 1.18.2
```

### 问题详情

在markdown中对中文使用斜体，样式不生效

![image](https://github.com/web-infra-dev/rspress/assets/1633638/7d390ab1-2221-4af9-abf5-6faccdbc111a)

原因是全局样式设置了`font-synthesis: none`，会导致某些中文字体的斜体失效，需要让`em`标签允许字体合成`font-synthesis: style;`

### 复现链接

https://codesandbox.io/p/devbox/dazzling-drake-f8vypm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv6c8v1v00053b6qsu0xwcbg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv6c8v1u00023b6qzk9q7kf9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv6c8v1u00033b6q3d6vw5su%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv6c8v1u00043b6q9cbglngk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv6c8v1u00023b6qzk9q7kf9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6c8v1u00013b6qf7yfxnnm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv6c8v1u00023b6qzk9q7kf9%2522%252C%2522activeTabId%2522%253A%2522clv6c8v1u00013b6qf7yfxnnm%2522%257D%252C%2522clv6c8v1u00043b6q9cbglngk%2522%253A%257B%2522id%2522%253A%2522clv6c8v1u00043b6q9cbglngk%2522%252C%2522activeTabId%2522%253A%2522clv6c9eth001y3b6rhkasyljn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522id%2522%253A%2522clv6c9eth001y3b6rhkasyljn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fhello%252Findex.html%2522%257D%255D%257D%252C%2522clv6c8v1u00033b6q3d6vw5su%2522%253A%257B%2522id%2522%253A%2522clv6c8v1u00033b6q3d6vw5su%2522%252C%2522activeTabId%2522%253A%2522clv6c99kc000z3b6r9pt0c0kh%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clv6c99kc000z3b6r9pt0c0kh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 复现步骤

内容中任何`*中文*`内容，斜体样式均不生效。

**Comment by Timeless0911** [comment]
We will adjust our global styles to `font-synthesis: style`.

You can also use global styles to override [global styles](https://rspress.dev/zh/plugin/system/plugin-api#globalstyles) yourself.
