### ISSUE TITLE
[Bug]: Changing language on 404 page does nothing

### ISSUE THREAD

**Issue by jbroma** [web-infra-dev/rspress#995]
### Details

When on 404 page, changing language does nothing and only appends new lang to the URL. 
Similar thing happens when using multiVersion and changing versions while on 404 page.

The question here is: what should be the desired behaviour?

### Reproduce link

https://rspress.dev/404 (or any non-existent route)

### Reproduce Steps

1. Go to the 404 page on `rspress.dev`
2. Change language
3. Observe 'zh' being added to the URL indefinetly, after few times it looks like this:

<img width="509" alt="image" src="https://github.com/web-infra-dev/rspress/assets/20626315/e31fe888-eb39-4104-a7b3-a40ef6a08a69">

**Comment by Timeless0911** [comment]
The desired behavior is that the 404 page does not have multi-version and language switching, and there should be some bugs now when we switching.
